### ISSUE TITLE
Occasional "error.originalError.errors.map is not a function" errors

### ISSUE THREAD

**Issue by ashley-conpago** [mercurius-js/mercurius#1024]
I very sporadically get errors in my project's tests `"error.originalError.errors.map is not a function"` which I've traced back to [here](https://github.com/mercurius-js/mercurius/blob/master/lib/errors.js#L49) in mercurius. could easily do a PR do add `Array.isArray()` there but this might hint at something else (me?) passing the wrong args to `defaultErrorFormatter`

**Comment by mcollina** [comment]
I think this is a bug here, would you like to send a PR?

**Comment by faizplus** [comment]
Hey @ashley-conpago, can you please add steps to reproduce this error?
