### ISSUE TITLE
GraphiQL issues in newest release

### ISSUE THREAD

**Issue by EDjur** [mercurius-js/mercurius#1046]
Hi! 👋 

There seems to have been some change in how the GraphiQL endpoint is mapped in the new release.

I register one of my Mercurius instances on Fastify like this:

```
server.register(
  async (serverInstance) => {
    await serverInstance.register(mercurius, {
      schema,
      resolvers,
      loaders,
      graphiql: true,
      path: "",
      context,
    });
  },
  { prefix: "/graphql" }
);
```

Now, if I go to `myApp/graphql/graphiql`, all POST requests try to access `/graphql/graphql`.

```
{
  "message": "Route POST:/graphql/graphql not found",
  "error": "Not Found",
  "statusCode": 404
}
```

This didn't use to happen in previous versions.

Thanks!

**Comment by mcollina** [comment]
If you can send a PR it would be amazing, otherwise it might take a few days to fix.

**Comment by nandorodrigu3s** [comment]
hi there, guys. 
@mcollina I'm facing this situation too so I decided to create the PR.

here is the link
https://github.com/mercurius-js/mercurius/pull/1052
