### ISSUE TITLE
Implement Relay style pagination

### ISSUE THREAD

**Issue by luke88jones** [mercurius-js/mercurius#1067]
I think it would be useful to provide either plugin or a set of tools to assist with implementing Relay style pagination in Graphql. 

See the [relay docs](https://relay.dev/docs/v10.1.3/graphql-server-specification/) or the [GraphQL pagination spec](https://graphql.org/learn/pagination/) for more details. 

The initial aim of this work would be as below.

- automatically include GQL types for entities required to implement pagination e.g. `Node` 
- simplify the creation of `Connection` and `Edge` GQL types. 
- provide a way to simplify the creation of connection objects in resolvers (library functions/directives/additional resolvers) 
    - include some basic cursor generation to enable easier transition to global identifiers in the future 
- provide forward-only pagination 

Extensions
- add the ability to create globally unique Ids and provide the root `node` query as defined by the spec 
- provide backward pagination

**Comment by mcollina** [comment]
That's a great idea.

I think it can be a plugin or an helper library. Should I create you a repository?

**Comment by luke88jones** [comment]
@mcollina Thanks! I was playing with some different ideas yesterday. I think I'm starting to get somewhere so a repository would be great thanks!

**Comment by mcollina** [comment]
https://github.com/mercurius-js/relay-pagination

**Comment by luke88jones** [comment]
@mcollina Do we have a preference for using JS or typescript? I see there are mainly JS libraries but a few TS ones have been added recently.

**Comment by mcollina** [comment]
whatever you chose ;).

**Comment by luke88jones** [comment]
Hey @mcollina after developing a solution for this it didn't end up being Mercurius specific. After a discussion with @simoneb we intend to release it under https://github.com/nearform/relay-pagination-directive the repo you've created can be cleaned up. Thanks for your assistance

**Comment by mcollina** [comment]
perfect
