### ISSUE TITLE
Timing problems with nested resolvers throwing errors

### ISSUE THREAD

**Issue by p-kuen** [mercurius-js/mercurius#1098]
I am facing some timing issues with graphql when simultaneously fetching and deleting some elements.

We are using a client which deletes an element and immediately (without awaiting the delete) fetches the elements again.
The fetch includes some nested resolvers, e.g.

```gql
{ elements {id name child {id name}} }
```

The `child` field is non-nullable because in this case an element always needs a child. So this is the schema
```gql
type Element {
  id: ID!
  name: String!
  child: Element!
}

type Query {
  elements: [Element!]!
}
```

We are assuming the resolver of the `child` field needs some time (in this case mocking some database delay):
```ts
Element: {
  child: async function (element: TestElement) {
    // mock a delay in child resolver
    await setTimeout(10);

    return elementChilds[element.id];
  },
},
```

The client runs a fetch query and a delete mutation at the same time. When resolving the child, the id of the parent does not exist anymore in the `elementChilds` store, so it returns undefined and the whole query fails.

I also created a reproduction repository to better understand the issue: https://github.com/p-kuen/mercurius-nested-async-repro

I don't think this is an issue only with mercurius but with many other graphql server libraries.

I am wondering how to solve this problem. I just thought about multiple variants:
1. Handle the errors on the client -> I am not a big fan of this solution, because a client should expect a successful fetching of all elements with the child.
2. Include the `child` already when resolving the parent, so no delay happens on the child resolver. -> this is against all benefits I have when using graphql
3. Work with caches somehow?

I am sure some other people also having this problem. For example I found this short discussion regarding prisma: https://github.com/prisma/prisma/discussions/4225. In this case the developer solved it by just returning null (because it's a nullable field eitherway). This only works for nullable fields, but not for non-nullable fields, so it's not an ideal solution for me.

How do you solve this problem? What is best practice?

**Comment by mcollina** [comment]
There are no good solutions for this, it's part of the nature of distributed systems. Using a fire-and-forget actions and assume things happens in order is _incorrect_.
