### ISSUE TITLE
Preparing for Fastify v5 release

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#1107]
Hi! I've pre-emptively started to take a look at what's required for supporting Fastify v5. As I understand it, once Fastify v5 is released, we need to:
 - [x] Upgrade `fastify` in dev deps to `^5.0.0`
 - [x] Follow `fastify` upgrade guide
 - [x] Upgrade `@fastify/error` to `^4.0.0` (seems like this is already sorted as there is no `next` tag in npm? I could be wrong here!) and follow any upgrade guide
 - [x] Upgrade `@fastify/static` to `[next-major-version]` and follow any upgrade guide
 - [x] Upgrade `@fastify/websockets` to `[next-major-version]` and follow any upgrade guide
 - [x] Upgrade `fastify-plugin` to `[next-major-version]` and follow any upgrade guide
 - [x] Ensure tests run and fix anything that's necessary
 - [x] Semver major release for all of the above

I've done an initial pass to get an idea of things on my local machine using the `next` tag and all appears to be okay so far (`npm run test` works with no issue), although I'll wait until the upgrade guide(s) to be 100% confident about this and I'm not fully aware of the required v5 changes :)

My testing changes so far (deps removed for brevity):

```diff
  "devDependencies": {
-   "fastify": "^4.17.0",
+   "fastify": "next",
  },
  "dependencies": {
-    "@fastify/error": "^3.0.0",
+    "@fastify/error": "^4.0.0",
-    "@fastify/static": "^7.0.0",
+    "@fastify/static": "next",
-    "@fastify/websocket": "^10.0.0",
+    "@fastify/websocket": "next",
-    "fastify-plugin": "^4.2.0",
+    "fastify-plugin": "next",
  },
```

Let me know what you think so far!

**Comment by mcollina** [comment]
Indeed. There should be no changes that impact this directly, but I may be wrong.

**Comment by voxpelli** [comment]
Trying to help out by making a PR for the above: https://github.com/mercurius-js/mercurius/pull/1110

Node engine range was already bumped in: #1109

**Comment by jonnydgreen** [comment]
Thank you for sorting this! 🚀  Apologies for the delay in replying/reviewing, was at a wedding this weekend!

Before we move onto the other Mercurius plugins, I guess we need to:
- verify it works for the stable v5 release and update the package.json accordingly
- then release a semver major mercurius release

If you agree, I'll update the things to do in the description and reopen this issue :)

wdyt?

**Comment by voxpelli** [comment]
> update the package.json accordingly

This isn’t strictly needed, the current version range will include all v5 stable versions as well

> then release a semver major mercurius release

I think official Fastify plugins have released new majors already, but has marked them as pre-releases in GitHub and npm, could do the same here, either that or a beta / rc release

**Comment by jonnydgreen** [comment]
> This isn’t strictly needed, the current version range will include all v5 stable versions as well

Yeah very true!

> I think official Fastify plugins have released new majors already, but has marked them as pre-releases in GitHub and npm, could do the same here, either that or a beta / rc release

Good shout - allows us to get ahead of things!

What are your thoughts @mcollina ?

**Comment by jonnydgreen** [comment]
Thanks for doing the pre-release earlier! :) I've got a free day on Wednesday so I'll aim to get the mercurius plugins aligned then! @voxpelli if you wanna help out on this as well, gimme a shout :)

**Comment by voxpelli** [comment]
@jonnydgreen Sadly not using any of the mercurius plugins, so won't come naturally, and I have a bit of a deadline right now, but generally I'm very open to contribute!

**Comment by jonnydgreen** [comment]
Quick update on this (will add more as I go through all the plugins):
 - [x] Mercurius federation - looks like this is done, thanks @mcollina ! :) 
 - [x] Mercurius gateway - looks like this is done, thanks @mcollina ! :)
 - [ ] Mercurius auth - one of the tests is breaking with an unhandled promise rejection, looking into it!
 - [x] Mercurius cache - looks like this is done, thanks @mcollina ! :)
 - [ ] Mercurius upload
 - [ ] Mercurius validation

**Comment by mcollina** [comment]
All done
