### ISSUE TITLE
Handle Redis pubsub subscription failures.

### ISSUE THREAD

**Issue by PhanindraNeralla** [mercurius-js/mercurius#1114]
We use fastify and mercurius. 
We also use graphql subscriptions using redis pubsub (graphql-redis-subscriptions and io-redis) and setting up the schema of Resolvers ( Queries, Mutations, Subscriptions) while registering mercurius plugin onto fastify server.

Now, once app is up and running and later if Redis is down due to any reason, subscriptions are erroring out and causing app to crash. ( Handled using redisClient.on('error') , process.on('unhandledExceptions') etc , but still it doesnt help ).
Any idea how fastify/mercurius handles such cases? - like, we should be able to safely disable subscriptions OR return empty object for subscriptions while redis is down

My observations include, setting up error handlers only while setting up Fastify server. Not after that.
i.e. Once server is running and we have Redis down, how can we make sure our Fastify server handle subscriptions gracefully.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by AlessioScarfone** [comment]
After discussion with @PhanindraNeralla, we identified that the necessary fixes to implement graceful error handling have to be implemented in the `graphql-redis-subscriptions` library, which is responsible for managing the connection with Redis and not inside mercurius. 
I created a [test repository](https://github.com/AlessioScarfone/mercurius-redis-subscription) that exposes a GraphQL subscription connected to Redis with mqemitter-redis or graphql-redis-subscriptions to test this behaviour.
For example with `mqemitter-redis`, by catching the error from the emitter ( `emitter.state.on('error',...)` ), the server continues to run, and the query continues to respond correctly even if Redis is down.

NOTE: The `RedisPubSub` provided by `graphql-redis-subscriptions` is used as a custom "pubsub" for mercurius, instead, the emitter provided by "mqemitter-redis" is used as an emitter for mercurius

**Comment by simoneb** [comment]
Thanks for looking into this @AlessioScarfone . Based on your findings, I'm going to close this issue as the solution to this problem lies in user space.
