### ISSUE TITLE
Hash for persisted queries stored for standard POST requests

### ISSUE THREAD

**Issue by marcoreni** [mercurius-js/mercurius#1123]
We noticed that Mercurius persists queries that are not stored even if the query is not part of a persisted query flow, and without equality checks in respect of what has been sent from the client:

https://github.com/mercurius-js/mercurius/blob/master/lib/routes.js#L280

Apollo has a different behavior, where queries are persisted only as part of an APQ flow and only if the hash sent by the client matches the hash calculated on the server.

This has a couple of benefits:
1- avoid storing non-needed queries on the cache, in scenarios where the server allows to use both Persisted Queries and standard POST queries at the same time
2- avoid storing the same query multiple times and surface implementation errors (eg. if the client computes a wrong hash, the server won't ever find the corresponding query and will always store the query on a different hash).

Since the reference for Persisted Queries on Mercurius Docs is Apollo, would it be possible to align the behaviors? I'm willing to work on a PR.

**Comment by mcollina** [comment]
Sure thing! A PR would be amazing.
