### ISSUE TITLE
Feature Request: Tracing support

### ISSUE THREAD

**Issue by tHBp** [mercurius-js/mercurius#179]
Consider adding tracing support to enable checking runtime performance of queries and downstream API/Database calls.

Apollo supports the same [via a plugin](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-tracing).

It can be either directly part of the core, or be implemented as a plugin. But for the latter, I guess we'd have to roll out a plugin architecture.

**Comment by mcollina** [comment]
Would you like to work on this? I think it would be a nice feature to add.

**Comment by tHBp** [comment]
Sure, will try to complete a first revision over the weekend.

**Comment by xamgore** [comment]
Precious information can be found in the [apollo-tracing](https://github.com/apollographql/apollo-tracing) repository.

**Comment by pscarey** [comment]
@xamgore @tHBp

I'd like to flag that the only solution here isn't just Apollo's approach, but also the tracing could be implemented with [OpenTelemetry](https://opentelemetry.io/). Adding an OpenTelemetry exporter would be a viable way of supporting many more tracing backends in a performant way.

Wrapping all resolvers in a Schema to achieve detailed tracing (by analysing the GraphQL `info` object which includes `type`, `path`), is viable, but can have *large* performance impacts. We have implemented this approach on certain APIs for advanced Audit Logging, so it's worth the hit, but ensuring performance is not overly impacted is key for tracing.

A viable approach here may be:
- Wrapping and timing only the key schema/resolvers (i.e. where a `resolve` function has been provided).
- Only tracing execution time a configurable percentage of the time.

It might be that timing every resolver is possible, but performance impacts should be kept in mind (Apollo is certainly able to achieve this in Apollo Engine / Graph Manager).

I can provide some additional info on how you might go about wrapping the schema if either of you is interested in this.

**Comment by mcollina** [comment]
I would actually prefer adding OpenTelemtry support.

**Comment by PacoDu** [comment]
I think we will just need some documentation that explains how to use opentelemetry with mercurius. Some packages are about to be released for graphql instrumentation: [@opentelemetry/instrumentation-graphql](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/plugins/node/opentelemetry-instrumentation-graphql). I've not tested this package yet.

**Comment by PacoDu** [comment]
> Could we ship that as a small module with a few tests in this org?

I'm not sure this should be a module, from what I understand about opentelemetry, the tracer definition is for the end user. What we can do on our end is to add some mercurius specific span, maybe on loaders, cache, jit ? 

https://open-telemetry.github.io/opentelemetry-js/#library-authors

**Comment by mcollina** [comment]
I think it would be awesome to wrap resolvers and loaders.

**Comment by PacoDu** [comment]
> I think it would be awesome to wrap resolvers and loaders.

I think it needs more expérimentation but the resolvers are already covered automatically via graphql-instrumentation, a parameters allows to configure the depth of the tracing

**Comment by mcollina** [comment]
I have a feeling it won't work for graphql-jit, but maybe I'm too pessimistic.

**Comment by PacoDu** [comment]
> I have a feeling it won't work for graphql-jit, but maybe I'm too pessimistic.

Yes it wont.

About fastify and opentelemetry, the current landscape is a bit confusing because there is multiple initiative like https://github.com/autotelic/fastify-opentelemetry and https://github.com/mkinoshi/fastify-opentelemetry.

see https://github.com/open-telemetry/opentelemetry-js-contrib/issues/41

fastify-opentelemetry doesn't seem up to date with the latest version of fastify (it uses deprecated hooks). I haven't tested autotelic version yet.

@mcollina Is there any plan to move this kind of integration under the fastify org ?

**Comment by mcollina** [comment]
https://github.com/autotelic/fastify-opentelemetry should do the trick.
