### ISSUE TITLE
Add more validations for federated schemas

### ISSUE THREAD

**Issue by paolochiodi** [mercurius-js/mercurius#230]
While working on https://github.com/mcollina/fastify-gql/pull/227 and https://github.com/mcollina/fastify-gql/issues/184 I have noticed that the fastify-gql implementation is lacking at least two features from Apollo server.

One of them is that Apollo server performs additional validations on the federated schema that fastify-gql doesn't.
It also skips more validations then fastify-gql.

In #227 I only removed the one rule to fix #184, but we should probably uniform them to Apollo's.

Code: 

- https://github.com/apollographql/apollo-server/blob/main/packages/apollo-federation/src/composition/composeAndValidate.ts#L12
- https://github.com/apollographql/apollo-server/blob/main/packages/apollo-federation/src/composition/composeAndValidate.ts#L20
- https://github.com/apollographql/apollo-server/blob/main/packages/apollo-federation/src/composition/composeAndValidate.ts#L28
- https://github.com/apollographql/apollo-server/blob/63eb5d30d46d9c4d968fb23ecabdb691b8988a10/packages/apollo-federation/src/composition/compose.ts#L362

Additional rules:

- https://github.com/apollographql/apollo-server/blob/63eb5d30d46d9c4d968fb23ecabdb691b8988a10/packages/apollo-federation/src/composition/rules.ts

Tests:

- https://github.com/apollographql/apollo-server/blob/63eb5d30d46d9c4d968fb23ecabdb691b8988a10/packages/apollo-federation/src/composition/__tests__/composeAndValidate.test.ts

**Comment by santiagoalmeidabolannos** [comment]
I can take it

**Comment by tiagoheliob** [comment]
Is this still an occurring issue @mcollina?

**Comment by mcollina** [comment]
I'm going to close this as I never felt we needed more validations.
