### ISSUE TITLE
Incorrect Error object returned

### ISSUE THREAD

**Issue by paul590** [mercurius-js/mercurius#252]
Hello fastify team @RafaelGSS , the issue that i am seeing is when i run a query and receive an error it looks as follows:

```
{
  "error": {
   "data": null,
   "errors": [
   {
   "message": "error message thrown",
   "locations": [
   {
   "line": 2,
    "column": 3
    }
    ],
    "path": [
     "test"
    ]
   }
  ]
 }
}
```

however, if i run the same query again I see the error as below:

```
{
 "data": null,
 "errors": [
  {
  "message": "error message thrown",
  "locations": [
   {
   "line": 2,
   "column": 3
   }
   ],
   "path": [
   "test"
   ]
  }
 ]
}
```

Notice how there is an error object that wraps the actual error at first but then disappears with the cache of the error. The issue happens when using custom errors. is there a way to remove this error wrapping and have the library return the same error? Thank you so much for your help!! Here is the link to the open repo: https://github.com/paul590/toSendGraphQL

**Comment by RafaelGSS** [comment]
ref: https://github.com/fastify/help/issues/227 I'll take a look later.

**Comment by RafaelGSS** [comment]
@paul590 I could not reproduce your first example. Always return the same value (expected) for me:

```
{
  "data": {
    "test": null
  },
  "errors": [
    {
      "message": "Error test",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "test"
      ]
    }
  ]
}
```

However, I think I understand your other problem, is about your error handler, not works for `throw new Error...` but works when you pass a function that not already defined right? e.g: `query { anyFunctionThatNotExistsHere(code: "test") }` in your code.

Some considerations on that, I think that this is expected because following the [GraphQL - Error Spec](http://spec.graphql.org/draft/#sec-Errors) is a pattern to response errors in with this format. So, if your first example works as you sent, sounds a bug, but here I could not reproduce that.

As I can understand, you would like a `errorHandler` to runtime (e.g throw new Error). I recommend to check the types doc, maybe these two properties will help you:

```ts
  /**
   * Change the default error handler (Default: true).
   * If a custom error handler is defined, it should return the standardized response format according to [GraphQL spec](https://graphql.org/learn/serving-over-http/#response).
   * @default true
   */
  errorHandler?:
    | boolean
    | ((
        error: FastifyError,
        request: FastifyRequest,
        reply: FastifyReply
      ) => ExecutionResult);
  /**
   * Change the default error formatter.
   */
  errorFormatter?: ((
    error: FastifyError | GraphQLError | Error
  ) => {
    statusCode?: number
    response?: {
      data?: object
      errors: any[]
    }
  });
```

But, I tried here and when `throw new Error` occurs the `errorHandler` passed by props is not called, because already have an error handler inside `'graphql'` and it returns a `.errors` property. Do you know if this behaviour is expected? @mcollina

**Comment by mcollina** [comment]
@RafaelGSS I don't understand the question.

**Comment by RafaelGSS** [comment]
Runtime errors not pass by `errorHandler` property sent in: 
```
    server.register(fastify_gql_1.default, {
        errorHandler: (error, request, reply) => {
          const testError = {
            test: "here is never called on runtime errors"
          };
          reply.send(testError);
        },
    });
```

**Comment by mcollina** [comment]
The error format for a graphql endpoint is known. If a resolver throws, the error is captured and converted to said format. The error handler is invoked for all other cases.

You can customize the format with the error formatter.

**Comment by RafaelGSS** [comment]
So @paul590. My answer can help you :smile:

**Comment by paul590** [comment]
@RafaelGSS  and @mcollina thank you for your help with this issue! A couple of questions: 

- I read the documentation regarding the error formatter and it seems no matter what information I add it does not like and get the error 'No overload matches this call.'. For example I am looking to do something like this:

       errorFormatter: (error) => {
            statusCode: 400,
            message: error.message
        }

Also, regarding the 500 error, I noticed on the sample project that I created the error is currently been thrown with a 200 status code. I am using the following to throw the error: 

      throw new Error("Error test");

Thank you for your help!

**Comment by RafaelGSS** [comment]
Can you update the reproduction code in your repository? It helps to discover the behavior. Don't forget of comment the expected result

**Comment by paul590** [comment]
@mcollina thank you! Sorry what do you mean by PR? I can definitely contribute to make changes if that works!

**Comment by mcollina** [comment]
PR = Pull Request on Github.

**Comment by paul590** [comment]
@mcollina perfect thank you for the clarification

**Comment by paul590** [comment]
@mcollina @RafaelGSS I believe I have found the possible issue. Having added the error formatter, when I run a query that produces a 500 error, I will see the error go through the error formatter first, the go to the error handler. The issue is that it will fail if I try to use the error object on the error handler due to the data variable being null. Is this a bug?

If I have a query that produces a 400 error, the error will go directly to the error handler, by passing the error formatter. Is this also a bug, or this is how it is suppose to handle these type of errors. 

I have updated the repo and the README with this information to reproduce. https://github.com/paul590/toSendGraphQL

Thank you again for all your help!

**Comment by RafaelGSS** [comment]
Hey @paul590!

Is a pleasure to help you, but the repository provided is not a reproducible code for some reasons:
- Your code has much more than an example code -- `mongodb-memory-server` and other dependencies that are not related to the current issue.
- When I just try to run the example provide from README the application not start (for problems in the dependencies said above)

I recommend that you revisit your application and create a **minimal** reproducible code. However, I think that your problem is not a bug but an expected behavior.

**Comment by paul590** [comment]
Hi @RafaelGSS ,

thank you for looking into this. I added the memory server since I am able to reproduce a 500 error with that library. I can remove the library if needed, however, as per your answer the 400 and 500 errors are treated differently and separately from the error handler and error formatter? In this case if I want create a custom error I have to ensure it is both added to the handler and formatter? Thank you again!

**Comment by RafaelGSS** [comment]
I just saying that is harder to discover the problem without a minimal reproduction code. For example, you can reproduce 500 errors with a simple `throw new Error`.

**Comment by paul590** [comment]
Hi @RafaelGSS Thank you I understand! I have updated the repo with the new code. If more information is required please let me know. https://github.com/paul590/toSendGraphQL

**Comment by paul590** [comment]
Hi @RafaelGSS is there an update to this issue? Also, is there a way to allow GraphQL to also return extensions? as per the documentation? it does not seem to be included in the errors by default.

**Comment by mcollina** [comment]
You can always send a PR to fix this.

**Comment by paul590** [comment]
@mcollina @RafaelGSS I pulled the code as well on my end, I am looking to implement the ability for errors to also display the GraphQL Error extensions. is there a reason why we didnt have this ability? Also, it seems this fix would be on the fastify library and not fastify-gql is this correct?

**Comment by RafaelGSS** [comment]
@paul590 follow the PR linked above

**Comment by paul590** [comment]
@RafaelGSS Thank you shoud l I post my question about the GraphQl Error extension there as well?

**Comment by RafaelGSS** [comment]
I think that this issue could be closed since the current behavior is expected as explain [here](https://github.com/mercurius-js/mercurius/pull/280#issuecomment-700358125).
