### ISSUE TITLE
Switch to undici for federation

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#263]
https://github.com/nodejs/undici is significantly faster than nodejs http client.

**Comment by adamovittorio** [comment]
I'm in late.. it has been already worked out

**Comment by mcollina** [comment]
https://github.com/mercurius-js/mercurius/pull/327 is ready to land. However I feel it's a semver-major change and I'd like to bundle it with a few others.

**Comment by adamovittorio** [comment]
Thanks, it makes complete sense to me; I'm looking forward to trying it!
