### ISSUE TITLE
Automatic persisted queries (useGETForHashedQueries: true)

### ISSUE THREAD

**Issue by aldis-ameriks** [mercurius-js/mercurius#269]
I'm attempting to set up the "Automatic persisted queries" according to [Using GET requests with APQ on a CDN](https://www.apollographql.com/docs/apollo-server/performance/apq/#using-get-requests-with-apq-on-a-cdn).

Given fastify-gql config
```js
  app.register(GQL, {
    schema,
    resolvers,
    loaders,
    persistedQueryProvider: GQL.persistedQueryDefaults.automatic(),
  })
```

And apollo-client setup according to [apollo docs](https://www.apollographql.com/docs/apollo-server/performance/apq/).
```ts
const link = createPersistedQueryLink({ useGETForHashedQueries: true }).concat(createHttpLink({ uri: "/graphql" }));

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: link,
});
```

Apollo client attempts to make a GET request with hashed query in query parameters, however, fastify-gql keeps returning
```
{"data":null,"errors":[{"message":"Unknown query"}]}
```

The docs say
> This default is compatible with apollo-client, and requires no additional tooling to set up at the cost of some performance

`useGETForHashedQueries: false` sends the hashed query over `POST` and it works fine. Is `useGETForHashedQueries: true` supported by the automatic persisted queries to allow request caching behind CDN? Or does it require additional configuration?

**Comment by sastan** [comment]
This should be fixed with #307
