### ISSUE TITLE
Jit problems when operationName empty 

### ISSUE THREAD

**Issue by heri16** [mercurius-js/mercurius#276]
When operationName is not provided...

This line succeeds:
`buildExecutionContext(fastifyGraphQl.schema, document, root, context, variables, operationName)`
https://github.com/mcollina/fastify-gql/blob/23ac7db38c50642b67a6213b2de7458b35537a64/index.js#L435

But this line fails:
`compileQuery(fastifyGraphQl.schema, document, operationName)`
https://github.com/mcollina/fastify-gql/blob/23ac7db38c50642b67a6213b2de7458b35537a64/index.js#L424

**Comment by heri16** [comment]
Relates to #275 

Should we check for compilation failure, or should we solve this root cause?

**Comment by mcollina** [comment]
Maybe both?

**Comment by tiagoheliob** [comment]
@heri16 after some digging and tests I end up finding that it's not an issue, `graphql-jit` internally handles it as you can see in [here](https://github.com/zalando-incubator/graphql-jit/blob/50855a2540502ee78dd034bc55853c255a5500b5/src/execution.ts#L1429) in case the operation is `OPERATION_DEFINITION` and there is no `operationName` it assigns `operation = definition` which prevents it from throwing an exceptions down [here](https://github.com/zalando-incubator/graphql-jit/blob/50855a2540502ee78dd034bc55853c255a5500b5/src/execution.ts#L1440) that is the shape of a documentation definition in case you're wondering 

```
{
  "kind": "OperationDefinition",
  "operation": "query",
  "variableDefinitions": [],
  "directives": [],
  "selectionSet": {
    "kind": "SelectionSet",
    "selections": [
      {
        "kind": "Field",
        "name": {
          "kind": "Name",
          "value": "user",
          "loc": { "start": 31, "end": 35 }
        },
        "arguments": [],
        "directives": [],
        "selectionSet": {
          "kind": "SelectionSet",
          "selections": [
            {
              "kind": "Field",
              "name": {
                "kind": "Name",
                "value": "name",
                "loc": { "start": 52, "end": 56 }
              },
              "arguments": [],
              "directives": [],
              "loc": { "start": 52, "end": 56 }
            }
          ],
          "loc": { "start": 36, "end": 70 }
        },
        "loc": { "start": 31, "end": 70 }
      }
    ],
    "loc": { "start": 17, "end": 82 }
  },
  "loc": { "start": 11, "end": 82 }
}
```

@mcollina I believe you can go ahead and close this issue
