### ISSUE TITLE
Incoming change, new name, organization

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#284]
A few folks recommend me to change the name of this module as it's not really recognizable.

The new name will be [`mercurius`](https://www.npmjs.com/package/mercurius), which was recently transfered to me.

I would soon move this repo to the new org so we can have a slightly better collaboration model around this new project.

**Comment by PabloSzx** [comment]
Shouldn't this issue be closed? 👀

**Comment by mcollina** [comment]
yes! If you see stuff that can be closed, go ahead and close it!
