### ISSUE TITLE
Create logo!

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#295]
It would be great to have an awesome logo!

**Comment by mrazauskas** [comment]
This shape came to my head last night. Leaving it here.

Perhaps it makes sense to keep GraphQL’s hexagon? People recognise it. (3) is here just to try out something else. (4) simply shows how shape was build (based on GraphQL’s logo).

I was working more on (2), seemed more interesting. But right now I would vote for (2). “Mercurius is a GraphQL adapter” and an adapter is rather simple thing. (2) is an adapter. Might be (1) got over-engineered.

These are just quick drafts, of course. Looking forward for feedback.

<img width="400" alt="mecurius-1" src="https://user-images.githubusercontent.com/72159681/109680896-9d9b4e80-7b85-11eb-91ee-5421ae2e6fb6.png">
<img width="400" alt="mecurius-2" src="https://user-images.githubusercontent.com/72159681/109680901-9e33e500-7b85-11eb-8d3c-dd890021aca4.png">
<img width="400" alt="mecurius-3" src="https://user-images.githubusercontent.com/72159681/109680903-9e33e500-7b85-11eb-854a-00df7b2f09da.png">
<img width="401" alt="mecurius-4" src="https://user-images.githubusercontent.com/72159681/109680904-9ecc7b80-7b85-11eb-8a82-1e50e346eafc.png">

**Comment by mcollina** [comment]
I love these drafts! The one I like the most is the 4th one actually!

What do other think?

@PacoDu @PabloSzx?

**Comment by PabloSzx** [comment]
I like the 4th one too, but maybe making the grey a little bit darker, o even going for the simpler 2nd looks good too

**Comment by mrazauskas** [comment]
Glad you like it. Now I see how to improve it a bit. Will be back soon.

**Comment by PacoDu** [comment]
Thanks for these drafts ! I also like the 2nd and the 4th.

**Comment by mrazauskas** [comment]
Next round:

- full GraphQL logo behind
- the shape now looks more like a lightening. Before it reminded me some mountains
- M does not touch bottom line in this version.
- the look is overall more dynamic. I try to give a hint to Fastify’s performance
- perhaps it is better to stick with two colours? Seems enough.

<img width="400" alt="mecurius-5" src="https://user-images.githubusercontent.com/72159681/109810632-7189d700-7c32-11eb-9f91-57f7e0ccdcce.png">
<img width="400" alt="mecurius-6" src="https://user-images.githubusercontent.com/72159681/109810636-73539a80-7c32-11eb-9ab3-359869951d36.png">

**Comment by mcollina** [comment]
It seems enough! Could you add some text to the right as well?

**Comment by mrazauskas** [comment]
There are so many fonts. Would be interesting to compare the number of digital fonts and the amount of `npm` packages. It is a job to pick the right one. Here is what I was looking for:

- sans serif.
- open source font.
- spiky M (bottom spike could be enough, but then it definitely should not touch the base line).
- with monospaced companion (optional, but would be useful for website some day).
- a hint of tech in the character (optional, can make everything unnecessary complicated).

With this in mind I was looking around. Found few interesting options. Suddenly [IBM Plex](https://www.ibm.com/plex/) is looking at me and I am looking at it. Fulfils all fives requirements. And it is incredibly well made:

> Each glyph in the entire Plex family has been TrueType hinted (i.e. optimized for on-screen legibility in small sizes).

> The Plex Italics were engineered according to specific angles that work best with pixels to get the smoothest on-screen rendering.

Attention to every detail. In other words – it will scale.

Licensed under the SIL Open Font License.
Available as `npm` package and at https://github.com/IBM/plex.

<img width="1096" alt="mecurius-7" src="https://user-images.githubusercontent.com/72159681/109973721-6c478d80-7d01-11eb-8cc3-ea08ef9704e6.png">
<img width="1096" alt="mecurius-8" src="https://user-images.githubusercontent.com/72159681/109973731-6e115100-7d01-11eb-910f-2bfd4ae8ba20.png">
<img width="643" alt="mecurius-9" src="https://user-images.githubusercontent.com/72159681/109973735-6ea9e780-7d01-11eb-9d7b-d0ca864ca3f7.png">
<img width="643" alt="mecurius-10" src="https://user-images.githubusercontent.com/72159681/109973737-6f427e00-7d01-11eb-8324-72fa27707bcc.png">

**Comment by mrazauskas** [comment]
I will clean last details, create a repo with png & svg files and will send Transfer Request. Hm.. Or is there a better option?

In any case I have to create a repo with logos. And then let’s see.

**Comment by mcollina** [comment]
PTAL for all formats that are needed: https://github.com/fastify/graphics

**Comment by mcollina** [comment]
@mrazauskas you can just send a PR to https://github.com/mercurius-js/graphics.

**Comment by mcollina** [comment]
One of our designers in NearForm came up with the following design.

![Mercurius Concepts](https://user-images.githubusercontent.com/52195/110658283-d65ca880-81c1-11eb-802f-aa73f1e69b92.jpg)

What do you think of the 3rd design? It's very similar to the above, possibly a bit more streamlined.

**Comment by PacoDu** [comment]
I really like the 2nd and the 4th 😍, it's hard to choose between them. 

The 3rd is beautifully too but IMO the M shape alone reminds me more of a chart library than a graphql one.

**Comment by PabloSzx** [comment]
I like the 2nd one too, the color contrast looks very good.

> The 3rd is beautifully too but IMO the M shape alone reminds me more of a chart library than a graphql one.

I completely agree, maybe adding the GraphQL shape behind the M shape like the previous one would fix it

**Comment by cobraz** [comment]
IMHO, the logo above from @mrazauskas is the better option. It references GraphQLs logo. I would personally try to find some other colour scheme (that is purely my personal taste).

The alternatives that @mcollina sent are all super cool but has been branded «on their own». They don't reference GraphQL in any way; ergo Mercurius has to communicate what it is and over time build a relationship to their brand. I would rather take the _shortcut_ and use iconography from GraphQL.
