### ISSUE TITLE
Nexus Schema plugin

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#297]
It would be great to have a companion library on this same organization that combine mercurius with https://nexusjs.org/.

**Comment by gboston** [comment]
@mcollina Can you elaborate on this one? So you want a Fastify plugin that make the use of Nexus schema easier?

**Comment by mcollina** [comment]
It probably just need an example and some docs - I'm not sure. It's really nice from the docs but J have no experience with it.

(I don't really want anything, I just wrote a few ideas).

**Comment by gboston** [comment]
Yeah, currently looking into Mercurius in combination with Nexus. I'll check if I can make an example or something.
