### ISSUE TITLE
PostGraphile Plugin

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#298]
It would be great to create a companion module/plugin for https://www.graphile.org/postgraphile/.

**Comment by wesselvdv** [comment]
I’ve actually already built this for NestJS with the Fastify adapter. I hooked up the PostGraphile watch functionality to the reload schema functionality. I used PostGraphile as a library in this case.

**Comment by mcollina** [comment]
Is this Open Source?

**Comment by wesselvdv** [comment]
I can share what I had to built in order to make it work. I did hook up subscriptions as well, and the main area of attention was creating a context function that would provide the required context for the PostGraphile resolvers.

**Comment by mcollina** [comment]
I think sharing what you got would be of extreme interest!

**Comment by alemagio** [comment]
I'll try to integrate [fastify-postgraphile](https://github.com/alemagio/fastify-postgraphile) if no one else is working on this.

**Comment by wesselvdv** [comment]
It might be interesting now that some additional changes have been applied in how the http part of postgraphile is dealt with. See this PR: https://github.com/graphile/postgraphile/pull/1361

**Comment by alemagio** [comment]
Hi, I just made an attempt described [here](https://github.com/alemagio/fastify-postgraphile/blob/master/test/mercurius.test.ts).
The only issue is I was not able to avoid using the postgraphile function so the only way I could to make it work is to use my decorator `postgraphileGQL`.
I'm open to ideas and if anyone wants to jump in I'll be more than happy to collaborate. :smiley:

**Comment by mcollina** [comment]
@alemagio that's essentially the problem described above, take a look. Your example is not really integrating them in any way.

**Comment by alemagio** [comment]
@mcollina 
Sorry, should have mentioned [this](https://github.com/alemagio/fastify-postgraphile/blob/master/src/index.ts) too.
It basically uses the decorator created by mercurius instead of the simple `graphql` function after replacing the `schema` created by postgraphile in mercurius.
I know it's not ideal, it's just an attempt.

**Comment by mcollina** [comment]
You are not really verifying this works: https://github.com/alemagio/fastify-postgraphile/blob/1d1ca4290f9433f616951e51b2b1bb0dcbf8480a/test/mercurius.test.ts#L45-L77.

You are still calling `postgraphileGQL` which does not use mercurius.

**Comment by alemagio** [comment]
Maybe I'm not understanding it well, so feel free to slap me in the face if I'm wrong :sweat_smile: 

I added an option specific for mercurius (a dirty job actually) and in this scenario I use the decorator of mercurius to execute the query (https://github.com/alemagio/fastify-postgraphile/blob/1d1ca4290f9433f616951e51b2b1bb0dcbf8480a/src/index.ts#L46)
That is injected in the `QueryPerformer`
If `mercurius` option is false it uses `graphql`, if `mercurius` is true it uses `app.graphql

I don't even know what happens in fastify if a decorator calls another decorator honestly.

**Comment by mcollina** [comment]
Your test should cover:

1. remove this route handler https://github.com/alemagio/fastify-postgraphile/blob/1d1ca4290f9433f616951e51b2b1bb0dcbf8480a/test/mercurius.test.ts#L45-L47

2. call `/graphql` route provided by Mercurius routes to https://github.com/alemagio/fastify-postgraphile/blob/1d1ca4290f9433f616951e51b2b1bb0dcbf8480a/test/mercurius.test.ts#L52

**Comment by alemagio** [comment]
@mcollina 
Thanks for your help!
I'll try to fix it.

**Comment by benbender** [comment]
@wesselvdv any news on publishing your try on the integration? Sorry to be pushy, but I would love to have a look! :)

**Comment by wesselvdv** [comment]
@benbender I ultimately dropped the approach, I was having major performance issues with the hybrid approach. I never really managed to find out where the issue was coming from, but my guess is that I was not able to release objects correctly after a request. I suggest you use their builtin route handler for fastify. It has much better performance.

**Comment by ja-bravo** [comment]
I'm going to give this a try if no one else is working on this, will share some details once I have something running

**Comment by ja-bravo** [comment]
I've been doing some research and found this repository: https://github.com/autotelic/mercurius-postgraphile
It looks like it works alright with some warnings about enums being used inconsistently across subschemas.
I haven't been found a way to fix the warnings as the generated GQL looks okay to me but they could be turned off by adding ```typeMergingOptions ``` to the ```stitchSchemas``` call inside the repository.

I could not get it to work with Federation either, or at least not correctly. I don't have a lot of experience with federation so it's possible that it's an issue on my side and not the plugin itself.  
I've created a small repo with my tests in case anyone wants to take a look: https://github.com/ja-bravo/mercurius-postgraphile-federation-test

**Comment by mcollina** [comment]
I think we could just list that project here: https://github.com/mercurius-js/mercurius/blob/master/docs/plugins.md. Could you send a PR?

**Comment by ja-bravo** [comment]
Done, https://github.com/mercurius-js/mercurius/pull/668
