### ISSUE TITLE
Custom directives and federationMetadata

### ISSUE THREAD

**Issue by aldis-ameriks** [mercurius-js/mercurius#300]
I'm looking into using custom directives within a graphql services that's part of a federation.
This is how I'm initializing mercurius

```
  app.register(mercurius, {
    schema,
    resolvers,
    federationMetadata: true,
  })
```

To add custom directives, I could use the `makeExecutableSchema` and pass the directive configuration there.
```
  app.register(mercurius, {
    schema: makeExecutableSchema({ typeDefs: schema, resolvers, ... }),
    federationMetadata: true
  })
```

But the `federationMetadata` is included only when `schema` is a string, which it is not when using `makeExecutableSchema`.

Is there a way to use custom directives with mercurius and also preserve the federationMetadata?

**Comment by mcollina** [comment]
I'm certain this is doable, but I do not have time to research it. It would be good to have a PR so it's added using objects, not strings.

**Comment by aldis-ameriks** [comment]
Support added in #322. Closing issue.

**Comment by YuriFontella** [comment]
Did this have any implementation to use the federations @key directive using makeExecutableSchema?

As shown in the second code of the first comment.
