### ISSUE TITLE
Drop playground and update graphiql

### ISSUE THREAD

**Issue by PacoDu** [mercurius-js/mercurius#306]
I think we should drop `graphql-playground` support because the repo will be archived and integrated as a preset for graphiql (see https://github.com/graphql/graphql-playground/issues/1143), and there is already other great package like: [altair-fastify-plugin ](https://github.com/imolorhe/altair/tree/staging/packages/altair-fastify-plugin) if some user want a different interface from the default graphiql.

And also update our graphiql implementation.

**Comment by mcollina** [comment]
I agree!
