### ISSUE TITLE
investigate graphql-jit fork of hoangvvo

### ISSUE THREAD

**Issue by wesselvdv** [mercurius-js/mercurius#315]
I just stumbled upon a what I think is an interesting fork of [graphql-jit by hoangvvo.](https://github.com/hoangvvo/graphql-jit)

What mainly triggered my interest is the addition of supporting jit subscriptions. Might it be interesting to see how mercurius could benefit from this? If so, in what form?

**Comment by mcollina** [comment]
Is development of graphql-jit stopped? Why was it forked?

**Comment by wesselvdv** [comment]
I believe he forked it for his own minimal graphql server implementation [Benzene](https://github.com/hoangvvo/benzene), but this is purely a deduction on my part. He did open up several PRs ([[For discussion, do not merge] Remove fast-json-stringify and allows customJSONSerializer to be a function](https://github.com/zalando-incubator/graphql-jit/pull/88), [Add Subscription support](https://github.com/zalando-incubator/graphql-jit/pull/89), [Make fast-json-stringify optional](https://github.com/zalando-incubator/graphql-jit/pull/84)). Which were not merged due to various reasons. (not complete, discussion pending or requires major other rework). Looks like he just went with a personal fork for his own project to circumvent aforementioned challenges.

On another note, I do see that graphql-jit is not that actively developed. That was mainly the reason I opened up this issue.

**Comment by mcollina** [comment]
I would not switch to a fork at this point. If we have to, we'll do ours. I don't think there is any blockers right now on our end for which we'll need a fork.

**Comment by hoangvvo** [comment]
Please don't switch to my fork - it is for experimentation only. I just made a PR to add subscription here: https://github.com/zalando-incubator/graphql-jit/pull/94
