### ISSUE TITLE
Create list of open source GraphQL implementations using mercurius

### ISSUE THREAD

**Issue by simoneb** [mercurius-js/mercurius#345]
It would be cool to have a list of OS APIs built on top of mercurius!

**Comment by muco-rolle** [comment]
Any updates on this issue @simoneb

**Comment by simoneb** [comment]
No really, I guess GitHub [is already telling us that](https://github.com/mercurius-js/mercurius/network/dependents?package_id=UGFja2FnZS0xMzY4NDI5OQ%3D%3D).
