### ISSUE TITLE
Graphiql not loading

### ISSUE THREAD

**Issue by bRRRITSCOLD** [mercurius-js/mercurius#358]
***UPDATE***:
Here is the [repo/personal template](https://github.com/bRRRITSCOLD/ts-typegraphql-fastify-graphql) ([entry file](https://github.com/bRRRITSCOLD/ts-typegraphql-fastify-graphql/blob/master/src/index.local.ts)) I am using. README should get it going locally with minimal effort. Let me know if it does not and I will help out.

I also started to look into if it is a local browser setting.

***ORIGINAL***:
receiving the below errors when using:

    fastifyApp.register(require('mercurius'), {
      schema,
      graphiql: 'graphiql',
      context: (request: unknown, response: unknown) => {
        // Return an object that will be available in your GraphQL resolvers
        return {
          request,
          response,
        };
      },
    });

OR

    fastifyApp.register(require('mercurius'), {
      schema,
      graphiql: true,
      context: (request: unknown, response: unknown) => {
        // Return an object that will be available in your GraphQL resolvers
        return {
          request,
          response,
        };
      },
    });

main.js:11 Refused to load the script 'https://unpkg.com/react@15.6.2/dist/react.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:11
url @ main.js:5
urls @ main.js:15
(anonymous) @ main.js:52
Promise.then (async)
(anonymous) @ main.js:44
main.js:11 Refused to load the script 'https://unpkg.com/react-dom@15.6.2/dist/react-dom.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:11
url @ main.js:5
urls @ main.js:15
(anonymous) @ main.js:52
Promise.then (async)
(anonymous) @ main.js:44
main.js:11 Refused to load the script 'https://unpkg.com/graphiql@0.12.0/graphiql.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:11
url @ main.js:5
urls @ main.js:15
(anonymous) @ main.js:52
Promise.then (async)
(anonymous) @ main.js:44
graphiql:1 Uncaught (in promise) Event {isTrusted: true, type: "error", target: script, currentTarget: null, eventPhase: 0, …}
Promise.then (async)
(anonymous) @ main.js:57

**Comment by PabloSzx** [comment]
can you make an example reproducing the error (github repo or codesandox)? it seems to be a csp security policy configuration issue in your fastify instance rather than a mercurius error

**Comment by bRRRITSCOLD** [comment]
@PabloSzx 100% my fault for not doing that from the beginning.

Here is the [repo/personal template](https://github.com/bRRRITSCOLD/ts-typegraphql-fastify-graphql) I am using. README should get it going locally with minimal effort. Let me know if it does not and I will help out.

**Comment by PabloSzx** [comment]
![image](https://user-images.githubusercontent.com/8672915/101358869-3ddd2200-387a-11eb-9b85-2e8915be0a9d.png)

![image](https://user-images.githubusercontent.com/8672915/101358801-21d98080-387a-11eb-8b6a-d1a4090006ca.png)


It is a [fastify-helmet](https://github.com/fastify/fastify-helmet) configuration issue, by default it uses strict contentSecurityPolicy, [check here](https://helmetjs.github.io/)

**Comment by bRRRITSCOLD** [comment]
@PabloSzx You are amazing. I had a hunch it was something configuration wise, I was having trouble finding anything in the stack trace to lead me in the right direction though :( Cheers!!!

**Comment by capaj** [comment]
Weird. I am getting this problem again. My config is:

```ts
app.register(fastifyCors)
  const trustedDomains = ['https://unpkg.com']

  app.register(fastifyHelmet, {
    // TODO figure this out
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"].concat(
          trustedDomains
        ),

        scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"].concat(
          trustedDomains
        ),
        styleSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"].concat(
          trustedDomains
        )
      }
    }
  })
```

and with the newest chrome firefox I started getting:

```
main.js:11          GET https://unpkg.com/subscriptions-transport-ws@0.9.19/browser/client.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
(anonymous) @ main.js:11
url @ main.js:5
urls @ main.js:15
importDependencies @ main.js:50
Promise.then (async)
(anonymous) @ main.js:62
main.js:48          GET https://unpkg.com/graphiql@1.4.2/graphiql.css net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
importDependencies @ main.js:48
Promise.then (async)
(anonymous) @ main.js:62
main.js:11          GET https://unpkg.com/graphiql@1.4.2/graphiql.min.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```

But it worked a few chrome versions back for sure.
