### ISSUE TITLE
ErrorWithProps is not exported from the TypeScript types

### ISSUE THREAD

**Issue by HosseinAgha** [mercurius-js/mercurius#359]
We have an example for using `ErrorWithProps` in the documentation but it looks like it is not exported from the TypeScript types.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by PabloSzx** [comment]
`ErrorWithProps` is being exported, it's just inside the default namespace ([check here](https://github.com/mercurius-js/mercurius/blob/master/index.d.ts#L365)), which is how the library is actually exporting the class.

```ts
import mercurius from "mercurius";

const error = new mercurius.ErrorWithProps();
```
