### ISSUE TITLE
Question: Validating headers 

### ISSUE THREAD

**Issue by aleccool213** [mercurius-js/mercurius#366]
Hi there! 

I would like to validate some headers on the request. I see in [Fastify](https://www.fastify.io/docs/latest/Validation-and-Serialization/#validation) you can do this using the `schema`config but that is already being used for the GraphQL schema. What is the best way to go about doing this? 

Right now, we throw errors when constructing the `context` object but those are not getting bubbled up to the response appropriately.

**Comment by aleccool213** [comment]
After doing some more research, I'm wondering if this should be even handled at a gateway or context creation level. Does this make more sense to always have at a `query` or `mutation` level? Then have decorators around those functions in your resolvers.

**Comment by mcollina** [comment]
Can you make a use case of validating the headers?

**Comment by aleccool213** [comment]
I thought I had a valid one but I think just defining it on the query/mutation level is better on all accounts. I can't think of a scenario that we have currently where I would need to validate a header on every request for every single query/mutation. I was thinking `Accept-Language` or some to do with authentication but its still not a catch-all, only certain operations support these.
