### ISSUE TITLE
How to use subscriptions with fastify-websocket?

### ISSUE THREAD

**Issue by acro5piano** [mercurius-js/mercurius#369]
First of all, thank you for the great library.

I'm trying to work both mercurius + fastify-websocket using `subscription: true`, but stacking.

My code is like this:

```ts
const Fastify = require('fastify')
const fastifyWebsocket = require('fastify-websocket')
const mercurius = require('mercurius')

const { schema, resolvers } = require('./schema') // The same one from official docs

const app = new Fastify({
  logger: true,
})

// If we register `fastifyWebsocket` on our own, it raises:
//    Error: server.handleUpgrade() was called more than once with the same socket,
//    possibly due to a misconfiguration
// app.register(fastifyWebsocket)

app.register(mercurius, {
  schema,
  resolvers,
  subscription: true,
})

app.get('/ws', { websocket: true }, (conn) => {
  console.log(conn)
})

app.listen(6767)
```

Then connect to ws://127.0.0.1:6767/ws and I'm seeing the following output:

```
$ wscat -c ws://127.0.0.1:6767/ws

Connected (press CTRL+C to quit)
< {"error":"unknown route"}
Disconnected (code: 1005, reason: "")
```

I've created reproductive repo.

https://github.com/acro5piano/mercurius-with-fastify-websocket

Do you have any hints on it? 

Possible solutions are:

- Allow to pass my `wss` and pass it to `fastify-websocket`.
- Allow use multiple WebSocket server and use `server.on('upgrade')`.

Best regards,

**Comment by acro5piano** [comment]
Oh I've found a way to do it.

If I edit this line and 


https://github.com/acro5piano/mercurius/blob/c835596557e867d990a009a95ef3e7ff5f7c7c54/lib/subscription.js#L8

https://github.com/acro5piano/mercurius/blob/master/lib/subscription.js#L8

**Comment by acro5piano** [comment]
I've saw the whole code and my assumption is the following. (I'm not so familiar with Fastify plugins)

- fastify-websocket adds WebSocket route using `onRoute` hook
- Fasity does not fire `onRoute` hook from plugins. However, if we wrap the plugin with `fp`, it fires.
- Currently plugins are multi-layers.
    - 1. mercurius (index.js)
    - 2. routes.js
    - 3. subscriptions.js
    - 4. fasitfy-websocket
- `route.js` isn't wrapped with `fp`, so `onRoute` hook which written at `fastify-gql` does not invoke

Is this correct? If so, are there anything I can do?

Simple solution is wrap every file with `fp`.

**Comment by acro5piano** [comment]
Sorry to post too much comments. I've confirmed adding `fp` to every plugins solved my issue. I'll create a PR soon.

**Comment by mcollina** [comment]
I don't think this use case was originally supported. Unfortunately you can't use fastify-websocket more than once on a given instance. We should be able to detect if it has been loaded already and not load it twice. Would you like to implement this?

**Comment by acro5piano** [comment]
@mcollina 
Thank you for the hint. I'll try to implement it.
