### ISSUE TITLE
gateway subscriptions is trying to get subscription from his own resolvers

### ISSUE THREAD

**Issue by 0x77dev** [mercurius-js/mercurius#370]
gateway is seeing subscription schema from another service, but i think it is trying to resolve subscription from it's own resolvers.

### Gateway Screenshot
![Gateway Screnshot](https://user-images.githubusercontent.com/46429701/103154672-93359080-47a1-11eb-8d93-045859fbba0d.png)

### Service Screenshot
![Service Screenshot](https://user-images.githubusercontent.com/46429701/103154691-c1b36b80-47a1-11eb-82d8-1f6f10584f0f.png)

#### Notes
Gateway is having `wsUrl` of service in configuration.

#### Versions
- Mercurius `6.5.0`
- Node.js `v14.15.1`
- uname `Linux ff9c650fec30 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux`

**Comment by mcollina** [comment]
Could you please add a full example to reproduce?

**Comment by 0x77dev** [comment]
@mcollina https://gist.github.com/0x77dev/af60ef51e5405393c311f652ddd14289

**Comment by nigelhanlon** [comment]
I managed to get the sample code working with some small changes. I have put it together in this [Gist](https://gist.github.com/nigelhanlon/defbf4f34e6993bbcad623df6ca5be98). 

It seems that if you try and return a scalar type directly in the subscription it causes a format error, but if you return a type with the scalar inside it, the error disappears. Not sure why it’s the case but that’s a possible workaround.

**Comment by 0x77dev** [comment]
@nigelhanlon
> I managed to get the sample code working with some small changes. I have put it together in this [Gist](https://gist.github.com/nigelhanlon/defbf4f34e6993bbcad623df6ca5be98).
> 
> It seems that if you try and return a scalar type directly in the subscription it causes a format error, but if you return a type with the scalar inside it, the error disappears. Not sure why it’s the case but that’s a possible workaround.

Yup, works for me!

**Comment by Santinell** [comment]
@mcollina  @0x77dev, what I could do if I need return scalar type? `JSONObject` in my case (from `graphql-scalars`)

```
extend type Subscription {
  onUpdate(project: ObjectID): JSONObject
  onCreate(project: ObjectID): JSONObject
  onRemove(project: ObjectID): JSONObject
}
```

**Comment by simoneb** [comment]
@Santinell if that doesn't work it may be the same reason as what's originally reported in this issue. The current workaround would be to wrap that into a type. Apparently there hasn't been progress in figuring out the root cause of the issue.

**Comment by Santinell** [comment]
@simoneb Thanks for your comment, now I understand. I wrapped it in another type and now it works.
I did it this way:

```
type Event {
  data: JSONObject
}

extend type Subscription {
  onUpdate(project: ObjectID, types: [String]): Event
  onCreate(project: ObjectID, types: [String]): Event
  onRemove(project: ObjectID, types: [String]): Event
}
```

**Comment by simoneb** [comment]
No problem, glad it helped. That's a workaround, I would be happy if somebody could look more closely why it doesn't work with plain scalars.

**Comment by simoneb** [comment]
Fix proposed in https://github.com/mercurius-js/mercurius/pull/508
