### ISSUE TITLE
Usage with typegraphql

### ISSUE THREAD

**Issue by ramiel** [mercurius-js/mercurius#384]
Is it possible to use the schema generated by [typegraphql](https://typegraphql.com/)? The type exported by typegrahql is `GraphQLSchema`, the same expected by mercurius, but it doesn't work and there's no error message.

**Comment by mcollina** [comment]
I'm not personally a user of Typegraphql... so I would leave it to the community. Maybe you can send a PR to fix this and/or add an example.

**Comment by ramiel** [comment]
Indeed. I was hoping in some previous experience by any of the users here :)

**Comment by ramiel** [comment]
Ok, I found out there's actually no problem to use mercurius with type-graphql which produces a consumable schema. The only problem is that graphql versions mismatch and the produced schema cannot be used because of this. A solution would be to have `graphql` as a peer dependency instead of being a normal dep. I propose a PR if this makes sense to you.

**Comment by mcollina** [comment]
I don't see graphql as a dependency in https://www.npmjs.com/package/type-graphql

**Comment by voxpelli** [comment]
@mcollina It's a `peerDependency`: https://github.com/MichalLytek/type-graphql/blob/d50861399d8ea6b32328d667e38ff1562e270366/package.json#L22-L25

**Comment by voxpelli** [comment]
> Ok, I found out there's actually no problem to use mercurius with type-graphql which produces a consumable schema. The only problem is that graphql versions mismatch and the produced schema cannot be used because of this. A solution would be to have `graphql` as a peer dependency instead of being a normal dep. I propose a PR if this makes sense to you.

I've generally also found this to be true for complex types like this, having them as direct dependencies can easily cause errors as multiple versions of the module then easily can exist side by side and the tiniest of differences between types in the them are enough to make types rejected.

**Comment by mcollina** [comment]
> @mcollina It's a `peerDependency`: https://github.com/MichalLytek/type-graphql/blob/d50861399d8ea6b32328d667e38ff1562e270366/package.json#L22-L25

I don't understand this, as the two ranges of mercurius and type-graphql overlaps, so only one dependency should be installed.

**Comment by ramiel** [comment]
> I don't understand this, as the two ranges of mercurius and type-graphql overlaps, so only one dependency should be installed.

I agree with you, this shouldn't be a problem, nonetheless it was during my test. I'll check later if I did any other mistake, maybe some other deps included graphql or, most probably, in development type-graphql still install graphql and the version mismatch happens. Note that graphql is a dev dependency for type-graphql: https://github.com/MichalLytek/type-graphql/blob/d50861399d8ea6b32328d667e38ff1562e270366/package.json#L56

I'll also try to provide a small reproduction repo, but later today or in the next days.

**Comment by mcollina** [comment]
Thanks, a reproduction repo would be good!

(I also recommend to remove lockfiles and node_modules and reinstall everything from scratch)

**Comment by voxpelli** [comment]
> > @mcollina It's a `peerDependency`: https://github.com/MichalLytek/type-graphql/blob/d50861399d8ea6b32328d667e38ff1562e270366/package.json#L22-L25
> 
> I don't understand this, as the two ranges of mercurius and type-graphql overlaps, so only one dependency should be installed.

Does the current npm ensure that?

I know that at least Yarn `1.x` doesn't when one has a lockfile in place – installing a new module or a new version of a module only installs the latest dependencies for that module, it doesn't change the version used by other modules, so one can easily end up with multiple versions of the same module.

Of course one can fix this by running a `yarn upgrade`, as then all dependencies and sub dependencies are moved to the latest version, but that also requires more testing as than can result in quite a huge amount of changes.

**Comment by mcollina** [comment]
I think this is about good maintainance of the the lockfiles. We can't really support a combination of every version with every other version of our dependency that fit our ranges. The most common approach is to only support the last.

**Comment by voxpelli** [comment]
Sure, eg. running `yarn add graphql mercurius typegraphql` (if one has all three added at the top) should solve it.

Though I wouldn’t go as far as saying that duplicated modules are necessarily a sign of bad lockfile maintenance.

But maybe npm is solving it better than yarn 1?

**Comment by mcollina** [comment]
I don't know.

Anyway, this is not a bug.

**Comment by ramiel** [comment]
It looks like installing dependencies all in one shot fixes the problem, so

```
yarn add mercurius graphql type-graphql
```

Anyway this issue has never been opened as a bug report, but just as a way to investigate how to use mercurius with type-graphql. This may be helpful to other people using tools in the graphql ecosystem.
