### ISSUE TITLE
Allow setting graphql-jit's customJSONSerializer / fast-json-stringify

### ISSUE THREAD

**Issue by stephenh** [mercurius-js/mercurius#390]
I'd like to use graphql-jit's `customJSONSerializer` option, to use `fast-json-stringify` instead of `JSON.stringify`, but it looks like that isn't possible:

https://github.com/mercurius-js/mercurius/blob/361e9534f8c5e0dd693e16c7943b74b0d4c20e1e/index.js#L483

Could this be supported by mercurius's API?

I'm also a little curious if `customJSONSerializer` should just always be passed true, i.e. if its faster, just have that be the default. I had actually assumed it was, and was surprised that neither graphql-jit nor mercurius default it to on.

I guess `fast-json-stringify` does have the disclaimer that its slower on large output (...or at least "not as dramatically faster"), so maybe that is why. 

Kind of random/tangential, I also noticed the `fast-json-stringify` disclaimer about it dove-tailing really well with `flatstr`, but I don't see `flatstr` used in either mercurius or graphql-jit; is that a missed opportunity for a performance win?

**Comment by mcollina** [comment]
`flatstr` is done automatically by fastify.

Historically graphql-jit had fast-json-stringify backed in. However they removed it in one of the latest versions.
Would you like to send a PR to add it back to mercurius?

**Comment by sameer-coder** [comment]
I will take a look at this today if no one else is working on this

**Comment by sameer-coder** [comment]
@mcollina Should we just expose the full `compilerOptions` from graph-jit in mercurius?
Here's what it looks like:

```md
compilerOptions {Object} - Configurable options for the compiler  

disableLeafSerialization {boolean, default: false} - disables leaf node serializers. The serializers validate the content of the field at runtime so this option should only be set to true if there are strong assurances that the values are valid.
customSerializers {Object as Map, default: {}} - Replace serializer functions for specific types. Can be used as a safer alternative for overly expensive serializers
customJSONSerializer {boolean, default: false} - Whether to produce also a JSON serializer function using fast-json-stringify. The default stringifier function is JSON.stringify
```

User can then simply enable the `customJSONSerializer` from mercurius when needed.

**Comment by mcollina** [comment]
I think that would be a good idea.

**Comment by mattkindy** [comment]
I think perhaps the `MercuriusCommonOptions` weren't updated with this change
