### ISSUE TITLE
Closing out subscription does not execute return() on async iterator from subscription resolver

### ISSUE THREAD

**Issue by moonkev** [mercurius-js/mercurius#392]
Hi

I am working on a new application and looking to use mercurius to serve up graphql subscriptions.  During development, I noticed that if I close the the subscription client either abruptly or gracefully by sending a `GQL_STOP` the underlying async iterator from the subscription resolver will keep running.  In my working program (unable to share this particular code as it is  private code from my work) - I am delegating to another remote graphql subscription running in a different service.  So in this case these delegated subscriptions are staying active within my mercurius application to the remote server even though the client has disconnected.  As I am unable to show that code, I have put together a small project which demonstrates this

https://github.com/moonkev/mercurius-sub-repro

If you run src/mercurius.js it will startup a server on port 4500.  
query - http://localhost:4500
subs - ws://localhost:4500

You can make a subscription using this very simple example (using any client, i.e. Altair, graphql-playground, etc).
```
subscription {
  messages { id }
}
```

If from your client you disconnect or try to unsubscribe gracefully, you will notice from the logging that the iterator continues to run.  I have included a counter-example using express-graphql.  You can start this by running src/express.js.  It will start on the same URLs as the mercurius example.  If you close the client connection here, you will see that the async iterators return method is called and the iterator will stop producing data.

The iterator itself is defined in src/schema.js.  Apologies if there is just something that I have misconfigured that can make this work.  I didn't see anything in the documentation about it.  Please let me know if any further information is needed, Thanks!

**Comment by mcollina** [comment]
I haven't run the example, but the problem seems that in https://github.com/mercurius-js/mercurius/blob/master/lib/subscription-connection.js the iterator loop is never exited when the connection errors.

Would you like to send a PR?

**Comment by moonkev** [comment]
@mcollina I would be happy to open a PR, I will tuck the iterator into the map with the subscription context and will call return on the iterator when the context is also closed.  I will try to get a PR out tonight or tomorrow.

**Comment by valdestron** [comment]
This is related to: https://github.com/apollographql/graphql-subscriptions/issues/99#issuecomment-508520944

Mercurius is based on custom Subscription implementation not subscriptions-transport-ws. Those who try to migrate from apollo/gateway to mercurius gateway often faces a memory leak in subscription because pubsub does not fire asyncIterable.return(). Instead mercurius subscriptions is based on opinionated mqemitter where only queue.close() is used.
