### ISSUE TITLE
Tests intermittently failing

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#394]
Hi! As mentioned in this conversation https://github.com/mercurius-js/mercurius/pull/385#issuecomment-770115379, I've taken a closer look at the intermittently failing tests and identified a few potential fixes for the intermittent errors that I've come across:

 - For test [`subscription server works with fastify-websocket`](https://github.com/mercurius-js/mercurius/blob/master/test/subscription.js#L1719), there is a race condition where the test is ended before remaining checks can complete. Removing the `t.end()` should resolve this!
 - The test [`Polling schemas (subscriptions should be handled)`](https://github.com/mercurius-js/mercurius/blob/master/test/gateway/pollingInterval.js#L699) is not fully cleaned up in `t.tearDown`- should be fixed by adding this cleanup at the end of the test
 - For test [`gateway wsConnectionParams function is passed to SubscriptionClient`](https://github.com/mercurius-js/mercurius/blob/master/test/gateway/subscription.js#L337), the user service is closed before the gateway is closed. Switching this order in the `t.tearDown` should fix the intermittent errors in this case (and any other cases I can find in this test file)

With these proposed changes, running the following command `while npm run unit; do :; done` for ~15mins locally results in no errors!

I've already prepared the code for this so very happy to submit a PR for this if you are happy with the above approaches :)

**Comment by jonnydgreen** [comment]
I have also noticed just now that the test [`https://github.com/mercurius-js/mercurius/blob/master/test/gateway/pollingInterval.js#L534`] also occasionally fails in the CI only with the following error:

```txt
# Subtest: Polling schemas (cache should be cleared)
        ok 1 - should be equivalent
        not ok 2 - should be equivalent
          ---
          diff: >
            --- expected
          
            +++ actual
          
            @@ -1,12 +1,14 @@
             Object {
            -  "data": null,
          
            +  "data": Object {
          
            +    "me": null,
          
            +  },
               "errors": Array [
                 Object {
                   "message": "Cannot query field \"me\" on type \"Query\". Did you mean \"me2\"?",
                   "locations": Array [
                     Object {
            -          "line": 3,
          
            -          "column": 11,
          
            +          "line": 2,
          
            +          "column": 3,
                     },
                   ],
                 },
```

Happy to take a look at this one as well :)

**Comment by mcollina** [comment]
Amazing, could you send PRs?

**Comment by jonnydgreen** [comment]
For sure, will send the first one now with the 3 fixes I mentioned in the original description! I'll follow up with a PR for the other failing test as well :)
