### ISSUE TITLE
[types] reply object is missing in context

### ISSUE THREAD

**Issue by SkeLLLa** [mercurius-js/mercurius#404]
Hi.

In types `context` (`MercuriusContext`) doesn't contain `reply` object. Likely in js it's done here: https://github.com/mercurius-js/mercurius/blob/master/index.js#L242

Also in test `request` and `reply` are just declared in this interface https://github.com/mercurius-js/mercurius/blob/master/test/types/index.ts#L53, so they should be present in it?

So is missing `reply` a bug or it's done for a reason?

**Comment by mcollina** [comment]
It's likely a bug! PR?
