### ISSUE TITLE
Add subscription hooks to Mercurius

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#406]
Hi! As discussed in the original [hooks PR](https://github.com/mercurius-js/mercurius/pull/385#issuecomment-771872613), we could add GraphQL subscription hooks to Mercurius so we can process data at different points in the subscription lifecycle.

## Proposed solution

The subscription hooks to add will be:

- `preSubscriptionParsing`: before subscriptions are extracted from the input websocket data. It will contain the following data:
        - `schema`
        - `source`
        - `context`
- `preSubscriptionExecution`: before subscriptions are executed on the server. It will contain the following data:
        - `schema`
        - `document`
        - `context`
- `preGatewaySubscriptionExecution`: before subscriptions are created with federated services in the gateway. It will contain the following data:
        - `schema`
        - `document`
        - `context`
- `onSubscriptionResolution`: every time subscription data is received in the connection. It will contain the following data:
	- `execution`
	- `context`

## Example lifecycle

```
Incoming GraphQL Websocket subscription data
  │
  └─▶ Routing
           │
  errors ◀─┴─▶ preSubscriptionParsing Hook
                  │
         errors ◀─┴─▶ Subscription Parsing
                        │
               errors ◀─┴─▶ preSubscriptionExecution Hook
                              │
                     errors ◀─┴─▶ Subscription Execution
                                    │
                                    │
                                    └─▶ preGatewaySubscriptionExecution Hook(s)
                                            │
                                   errors ◀─┴─▶ Gateway Subscription Execution(s)
                                                  │
                                      wait for subscription data
                                                  │
                   subscription closed on error ◀─┴─▶ Subscription Resolution (when subscription data is received)
                                                        │
                                                        └─▶ onSubscriptionResolution Hook
```

All new code with be 100% covered by tests, documentation will be provided and the new hooks will be correctly typed. I have started work on an implementation of this and can submit a PR for this once everyone is agreed on the solution! :)

**Comment by mcollina** [comment]
Go for it!
