### ISSUE TITLE
Add schema directives support

### ISSUE THREAD

**Issue by rajagopalx** [mercurius-js/mercurius#408]
I think schema directives are currently not supported.
 
https://www.apollographql.com/docs/apollo-server/schema/directives/

or Is there any alternative?

**Comment by mcollina** [comment]
Why do you think they are not supported? I think they are: https://github.com/mercurius-js/mercurius/blob/2cb57b0da3903e8f54e3327558d4fcea10ee63ac/test/directives.js

Maybe we are missing docs.

**Comment by rajagopalx** [comment]
Thank you. Is there any example using `SchemaDirectiveVisitor`?

https://www.graphql-tools.com/docs/legacy-schema-directives/#implementing-schema-directives
https://www.apollographql.com/docs/apollo-server/schema/directives/#using-custom-schema-directives

Thank you.

**Comment by mcollina** [comment]
I don't think so, the tests are probably the most reliable source.

**Comment by rajagopalx** [comment]
Okay. Thank you.
