### ISSUE TITLE
Mark 'schema' optional in 'MercuriusSchemaOptions'

### ISSUE THREAD

**Issue by mrazauskas** [mercurius-js/mercurius#409]
At the moment `fastify.register(mercurius, { path: '/' })` trows `Property 'schema' is missing in type '{ path: string; }' but required in type 'MercuriusSchemaOptions'`.

Here is how I am using Mercurius (based on a sample from [docs](https://mercurius.dev/#/docs/api/options?id=appgraphqlextendschemaschema-appgraphqldefineresolversresolvers-and-appgraphqldefineloadersloaders)):

```
app.register(mercurius, { path: '/' })

app.register(async function (app) {
  app.graphql.extendSchema(schema)
})
```

The code works as expected.

Seems like 'schema' could be marked optional: `schema?: GraphQLSchema | string | string[];`.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
