### ISSUE TITLE
Add service metadata to `preGatewayExecution` hook

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#415]
Hi! I have a use case that requires me to infer the called federated service from within the `preGatewayExecution` hook. At the moment, I don't think this is possible as there is insufficient information in the `context` as far as I'm aware. In the code, this hook is called in two places:

- [`make-resolver`](https://github.com/mercurius-js/mercurius/blob/master/lib/gateway/make-resolver.js#L454)
- [`gateway.js`](https://github.com/mercurius-js/mercurius/blob/master/lib/gateway.js#L282)

I'm thinking we could add service metadata (starting with just `name`) to the hook as it is available in both of these situations. I think we have two options when presenting the service metadata to the user in the hooks API:

On the context:

```js
app.graphql.addHook('preGatewayExecution', async (schema, document, context) => {
  console.log(context.service.name)
})
```

Or as a separate parameter:

```js
app.graphql.addHook('preGatewayExecution', async (schema, document, context, service) => {
  console.log(service.name)
})
```

Which of these options do you prefer?

We could also do the same for the `preGatewaySubscriptionExecution` hook [here](https://github.com/mercurius-js/mercurius/blob/master/lib/gateway/make-resolver.js#L445), should you think this is worthwhile to do at the same time as well!

If you agree with this proposed implementation, I'm very happy to get a PR out for this today! :)

**Comment by mcollina** [comment]
I think it's better to use a 4th parameter.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jonnydgreen** [comment]
For sure, I'll start work on a PR now including unit tests, typings, typings tests and docs!
