### ISSUE TITLE
safeBuildSchema swallowing errors

### ISSUE THREAD

**Issue by jkirkpatrick24** [mercurius-js/mercurius#422]
Hello!

I think the introduction of the [safeBuildSchema method](https://github.com/mercurius-js/mercurius/pull/385/files#diff-061d3468d2bcef7c7e9e1a06bbe3e8d14fa2edabd3f090c099ac8718c8ec5a3aR107-R114
) has lead to the swallowing of errors that should be surfaced to users. Previously, if trying to build an invalid schema, a useful error message would be returned pointing them to the issue.

Given the invalid schema: 
```graphql
extend type Query { pizza: Pepperoni }
``` 

attempting to build the schema would throw an error with the message:  `"Unknown type "Pepperoni"`. With the current implementation that error is swallowed up. The resulting return value of  `safeBuildSchema` will be set as `undefined` [here](https://github.com/mercurius-js/mercurius/pull/385/files#diff-061d3468d2bcef7c7e9e1a06bbe3e8d14fa2edabd3f090c099ac8718c8ec5a3aR160). When we attempt to parse this undefined value later, a different more opaque error is thrown `"Syntax Error: Unexpected <EOF>"`.

I'm more than happy to contribute a PR to fix this, but just wanted to double check the approach. Is it reasonable for `safeBuildSchema` throw an error if both `buildSchema` and `buildFederationSchema` fail? that would allow us to send the more descriptive error message to the user. 

Cheers!

**Comment by mcollina** [comment]
Could you upload a runnable script to reproduce your issue? Otherwise it would be hard to understand what's going on.

As a general rule I would consider it ok to throw and error if both fails if this results in runtime errors / inability to access the graph.

**Comment by jkirkpatrick24** [comment]
Ah this is actually nothing to do with safeBuildSchema. It's to do with how the gateways handle remote services (specifically when those remote services have invalid schemas) so this isn't actually a bug.

I do think some improved error messaging would help here so I've spun up a quick PR to address that. 

https://github.com/mercurius-js/mercurius/pull/425
