### ISSUE TITLE
Query aliases are not handled correctly in the gateway

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#428]
Hi! I've encountered an issue when using aliases in queries to the gateway. This occurs within nested types where aliases are not handled correctly on fields. I'm able to reproduce it with a test and I think I have identified a potential solution for the fix as well.

To reproduce, we take the following gateway setup:

### User service schema

```graphql
type Query @extends {
  me: User
}

type User @key(fields: "id") {
  id: ID!
  name: String!
  message(input: String!): String!
}
```

### Post service schema

```graphql
type Post @key(fields: "pid") {
  pid: ID!
}

type User @key(fields: "id") @extends {
  id: ID! @external
  topPosts(count: Int!): [Post]
}
```

If we make the following query with valid aliases:

```graphql
query {
  user: me {
    id
    newName: name
    otherName: name
    foo: message(input: "foo")
    bar: message(input: "bar")
    somePosts: topPosts(count: 1) {
      pid
    }
    morePosts: topPosts(count: 2) {
      pid
    }
  }
}
```

We get the following error:

```json
{
  "data": { "user": null },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field User.name.",
      "locations": [{ "line": 5, "column": 9 }],
      "path": ["user", "newName"]
    }
  ]
}
```

Where I was instead expecting:

```json
{
  "data": {
    "user": {
      "id": "u1",
      "newName": "John",
      "otherName": "John",
      "foo": "foo",
      "bar": "bar",
      "somePosts": [{ "pid": "p1" }],
      "morePosts": [{ "pid": "p1" }, { "pid": "p3" }]
    }
  }
}
```

Looking at the codebase, it seems that the issue is to do with the way the gateway schema is resolved for fields within a service type as resolvers are currently only defined for types that trigger a request to a federated service.

From what I've been able to diagnose, the response coming back from the federated services is aliased correctly but when it is returned from the gateway field resolver, the alias types are not mapped to their original types. Here's an example in the codebase: https://github.com/mercurius-js/mercurius/blob/master/lib/gateway.js#L104

For example, from the user service we correctly get back:

```json
{
  "me": {
    "id": "u1",
    "newName": "John",
    "otherName": "John",
    "foo": "foo",
    "bar": "bar",
    "__typename": "User"
  }
}
```

But the gateway resolver is expecting:

```json
{
  "me": {
    "id": "u1",
    "name": "John",
    "message": "...",
    "__typename": "User"
  }
}
```

This has two issues:
 - Because it doesn't know about the aliases at this point, it is unable to map either of `newName` or `otherName` to the `name` field and thus returns undefined.
 - When alias fields return different values, it won't be able to differentiate between them.

## Proposed solution

I think there is a solution to this by adding a field resolver for every unhandled field in the gateway schema. This will allow us to use the raw data coming back from the federated services and correctly map to aliases on the gateway. In my testing, by adding the following as a fallback for unhandled types, I was able to resolve the aliases correctly:

```js
field.resolve = (parent, args, context, info) => parent && parent[info.path.key]
```

I think there are two places in the `gateway.js` file where we would need to put this line:
 - unhandled scalars
 - unhandled non-scalars

I do have a concern about this approach however, in that since we would be applying it on every unhandled type in the gateway schema, I don't know how this would scale for large schemas and what the impact would be (if any) from a performance and memory footprint point of view. It is a very basic function to be fair. Is there a nice way to benchmark this before and after perhaps?

Let me know what you think! As always, I'm very happy to help out with fixing this! :)

**Comment by PabloSzx** [comment]
I think it's very import for this issue to be fixed, thanks for reporting it

> Is there a nice way to benchmark this before and after perhaps?

I just created a repo for benchmarking mercurius very easily with autocannon https://github.com/PabloSzx/mercurius-benchmark, made it with a gateway with 2 services of only hello worlds, but it's a nice start, with some logic to make it very easy to use, there you can also modify mercurius as you need and the changes will be instant, since it's pnpm workspaces

**Comment by jonnydgreen** [comment]
No problem, I'll get started on a PR asap if that works for you!

> I just created a repo for benchmarking mercurius very easily with autocannon PabloSzx/mercurius-benchmark, made it with a gateway with 2 services of only hello worlds, but it's a nice start, with some logic to make it very easy to use, there you can also modify mercurius as you need and the changes will be instant, since it's using pnpm workspaces

Awesome, I'll give that a go - thanks very much for the tip! :)
