### ISSUE TITLE
Access context in rewriteHeaders

### ISSUE THREAD

**Issue by theGlenn** [mercurius-js/mercurius#431]
Hi, first of all, kudos for this awesome repo.

I was implementing the gateway but realised we cannot access context information in `rewriteHeaders`, it's quite a broad use case to pass  headers from context info to underlying services, Apollo allows it  in `RemoteGraphQLDataSource` by providing context in `willSendRequest`.

**Comment by mcollina** [comment]
Good spot! 
Would you like to send a Pull Request to add this feature? Remember to add unit tests.

**Comment by theGlenn** [comment]
Yes I could not sure where to start tho.
Could it the context parameter be passed to `service.sendRequest` ?

**Comment by mcollina** [comment]
Maybe, unfortunately I do not have time right now to dig into a design. It's definitely available in the resolver, it's just a matter of the few steps it must passed through to get it to `rewriteHeaders`.

**Comment by Santinell** [comment]
I have the same problem, I tried to make a workaround - just generate context in method `rewriteHeaders`,
but unfortunately method `rewriteHeaders` can't be async method because it's doesn't awaiting in `request` method.
It works only with synchronous methods. 😞
