### ISSUE TITLE
Query directives do not handle operation variables in the gateway

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#432]
Hi! I recently came across an issue in the gateway when passing variables through to `skip` directives in the query. When variables defined in the operation are used by directives, they are not included in the constructed query sent to federated services and an error is returned in the gql response. Note, this issue seems to be applicable when passing variables to any query directive supported by the gateway as it also occurs for the `include` directive (from my testing). I've managed to replicate this with a test for the following gateway setup:

### User service schema

```graphql
type Query @extends {
  me: User
}

type User @key(fields: "id") {
  id: ID!
  name: String!
}
```

### Post service schema

```graphql
type Post @key(fields: "pid") {
  pid: ID!
}

type User @key(fields: "id") @extends {
  id: ID! @external
  topPosts(count: Int!): [Post]
}
```

If we run the following query with valid skip directives using input variables:

```graphql
query GetMe($shouldSkip: Boolean!) {
  me {
    id
    name @skip(if: $shouldSkip)
    topPosts(count: 1) @skip(if: $shouldSkip) {
      pid
    }
  }
}
```

We get the following error:

```json
{
  "data": { "me": null },
  "errors": [
    {
      "message": "Variable \"$shouldInclude\" is not defined by operation \"Query_me\".",
      "locations": [{ "line": 5, "column": 42 }, { "line": 1, "column": 1 }]
    }
  ]
}
```

Where I was instead expecting it to return the data for `shouldSkip = false` :

```json
{
  "data": {
    "user": {
      "id": "u1",
      "name": "John",
      "topPosts": [{ "pid": "p1" }]
    }
  }
}
```

Looking at the codebase, it seems that the issue is to do with the way arguments with variable names are collected in [`make-resolver.js`](https://github.com/mercurius-js/mercurius/blob/master/lib/gateway/make-resolver.js#L273). At the moment, directives are not handled when looping over the query document selections to collect these names.

### Proposed solution

Collecting for selection directives should fix this issue. For example, the following code will ensure directive arguments are also included:

```js
if (selection.directives.length > 0) {
  for (const directive of selection.directives) {
    argumentNames.push(...collectArgumentNames(directive))
  }
}
```

In my testing of this issue, I have created a branch for this fix on my fork which resolves the issue: https://github.com/jonnydgreen/mercurius/tree/bugfix/gateway-directives-with-variables. If you are happy with the above solution and analysis, I am very happy to submit a PR for this fix! :)

**Comment by mcollina** [comment]
Excellent write up! Go ahead and send the PR!

**Comment by jonnydgreen** [comment]
Thanks! :) Will do that now!
