### ISSUE TITLE
custom directive support

### ISSUE THREAD

**Issue by sharmapukar217** [mercurius-js/mercurius#463]
Is there any other way to implement custom directives other than stuffs done on their test file?

**Comment by mcollina** [comment]
Did you read https://github.com/mercurius-js/mercurius/blob/master/test/directives.js?

**Comment by sharmapukar217** [comment]
@mcollina yes i've already read that but its too much there.. i'm searching for easy way. Currently I'm using `makeExecutableSchema` but there's a problem using this and working with unions. `mercurius-codegen` creates `resolveType` for resolving unions but `makeExecutableSchema` throw error and __resolveType works but then typescript get angry 😠 .

**Comment by sharmapukar217** [comment]
@mcollina btw is it good to use `makeExecutableSchema` with `mercurius` 🤔 ?

**Comment by mcollina** [comment]
Yes it's possible and tested. I have no clue about the typescript problems. I would recommend starting with a minimal repro and maybe open an issue on mercurius-codegen.

**Comment by sharmapukar217** [comment]
@mcollina it good to use makeExecutableSchema with mercurius ?

**Comment by mcollina** [comment]
Sure, it's just graphql.
