### ISSUE TITLE
Context type when creating sub-resolver

### ISSUE THREAD

**Issue by akoenig** [mercurius-js/mercurius#465]
Thanks for building `mercurius` 🤗 It's a pleasure to work with it – so lightweight 🪶 I have a question though 🙂 

It is related to working with TypeScript and the context type binding via `declare module "mercurius"`. What I want to achieve is modularizing the resolver map a little bit. Let's say I have the following `Project` type:

```graphql
type Project {
  members: [ProjectMember!]!
}
```

I want to define a "sub-resolver" for just the `members` field. I use the respective `ProjectResolvers` type which has been generated by `mercurius-codegen`.

```typescript
import { ProjectResolvers } from "./graphql/generated";

type Resolver = ProjectResolvers["members"];

export const members: Resolver = async (root, args, context) => {
  return [
    {
      firstName: "André",
    },
  ];
};
```

Unfortunately, the `context` is typed as `any` although I did `declare module "mercurius"` and defined the actual context type there. Not sure if this is an anticipated behavior or if this is an actual bug in the generated type definition or it is not meant to be used in such a way as I figured that the actual generated project resolver type is defined as:

```typescript
export type ProjectResolvers<
  ContextType = any,
  ParentType extends ResolversParentTypes["Project"] = ResolversParentTypes["Project"]
> = {
  // ...
}
``` 

The default of `ContextType` is `any` instead of the declared context type through the module declaration. Any help on the question of how to modularize the resolver map without loosing the types is highly appreciated.

**Comment by mcollina** [comment]
Thanks for reporting! Unfortunately I'm not an expert on TS and I can't help you directly. I hope some other member of the community could!

**Comment by PabloSzx** [comment]
Can you create a small repo reproducing this issue? Thank you

**Comment by akoenig** [comment]
@PabloSzx Sure 🙂 Here it is: https://github.com/akoenig/tmp-mercurius-context-type – The example represents basically the example from the readme and uses the `QueryResolvers` type directly for separating the resolver in an [own function](https://github.com/akoenig/tmp-mercurius-context-type/blob/e2419026d695b90efe1a88bcbd7d0b04f83543b7/src/resolvers/hello.ts#L9). In this case, the `context` is typed as `any` due to the default type [here](https://github.com/akoenig/tmp-mercurius-context-type/blob/e2419026d695b90efe1a88bcbd7d0b04f83543b7/src/graphql/generated.ts#L163).

**Comment by PabloSzx** [comment]
> @PabloSzx Sure 🙂 Here it is: https://github.com/akoenig/tmp-mercurius-context-type – The repo basically represents the example from the [mercurius docs](https://mercurius.dev/#/docs/typescript) and uses the `QueryResolvers` type directly for separating the resolver in an [own function](https://github.com/akoenig/tmp-mercurius-context-type/blob/e2419026d695b90efe1a88bcbd7d0b04f83543b7/src/resolvers/hello.ts#L9). In this case, the `context` is typed as `any` due to the default type [here](https://github.com/akoenig/tmp-mercurius-context-type/blob/e2419026d695b90efe1a88bcbd7d0b04f83543b7/src/graphql/generated.ts#L163).

To solve this issue you have 2 options:


```ts
import { MercuriusContext } from "mercurius";
import { QueryResolvers } from "../graphql/generated";

type Resolver = QueryResolvers<MercuriusContext>["hello"];

// `context` is of `any` type instead of the one defined in the "context builder" (see `src/index.ts`)
//
// This is because of the `any` default type in `src/graphql/generated.ts` -> `QueryResolvers`.
//
export const hello: Resolver = async (root, args, context) => {
  return "World";
};
```

or

```ts
import { IResolvers } from "mercurius";

type Resolver = NonNullable<IResolvers["Query"]>["hello"];

// `context` is of `any` type instead of the one defined in the "context builder" (see `src/index.ts`)
//
// This is because of the `any` default type in `src/graphql/generated.ts` -> `QueryResolvers`.
//
export const hello: Resolver = async (root, args, context) => {
  return "World";
};
```

**Comment by akoenig** [comment]
Ahhhh, thanks @PabloSzx for the heads-up. You're completely right. I thought it would catch up the type due to the `declare module` declaration, but passing the context explicitly helps. 👍🏽  Awesome! 🙂
