### ISSUE TITLE
Support for extensions similar to express-graphql

### ISSUE THREAD

**Issue by Sven65** [mercurius-js/mercurius#466]
In the [express-graphql](https://github.com/graphql/express-graphql/) package, I'm able to define an extension method that adds extra data to the output data as such;

```js
graphqlHTTP(async (req, res, graphQLParams) => ({
	schema,
	graphiql: true,
	context: { req, res, startTime: Date.now() },
	extensions: ({ context }) => {
		const {
			queryCost,
			queryRemaining,
			expires,
			pointsUsed,
		} = context.req

		return {
			runTime: Date.now() - context.startTime,
			queryCost,
			queryRemaining,
			expires,
			pointsUsed,
			maxQueryCost: 1000,
		}
	},
})
```

I'm unsure if this is possible to do with Mercurius, if it is, I'd like to know how, and if not, I'd like to see it added.

**Comment by mcollina** [comment]
In mercurius we have hooks: https://mercurius.dev/#/docs/hooks?id=onresolution. You can also use fastify onSend to alter the final payload: https://www.fastify.io/docs/latest/Hooks/#onsend.

Would you like to send a PR to add an example?

**Comment by Sven65** [comment]
Thanks!
I'll give the hooks a go and send a PR once I get my desired result!

**Comment by Sven65** [comment]
After some tinkering, the only way I was able to add any extensions is through fastifys own `onSend` hook, even though mercurius has an `exec.extensions` property in its `onResolution` hook.

I believe this is a bug, and created a new report at #467

**Comment by mcollina** [comment]
Using `onSend` would have been my first choice anyway.

**Comment by Sven65** [comment]
As I have more endpoints than just graphql, fastifys `onSend` hook would affect those too. I could check the URL and methods, but I prefer to register it directly on the plugin methods.

I appreciate the help, and I'll close this issue now.

**Comment by Sven65** [comment]
Sorry, would you mind giving me an example on how you'd use `onSend` to add the extensions (with data from mercurius)?

**Comment by mcollina** [comment]
I currently have no time :(.

**Comment by Sven65** [comment]
No worries!

I figured out the issue behind this and #467 and I created a PR (#468) for you to look at when you do 😄
