### ISSUE TITLE
How to get FastifyRequest in resolvers?

### ISSUE THREAD

**Issue by fookit** [mercurius-js/mercurius#478]
Say I have this resolver:

```ts
// resolvers.ts
import type { IResolvers } from 'mercurius'

const resolvers: IResolvers = {
  Query: {
    add: async (_, { x, y }) => {
      // I need request.ip here
      // console.log(`\n request.ip:`, request.ip, `\n`)
      return x + y
    }
  }
}
```

Is there any way I can get request: FastifyRequest?

---

Versions: typescript (v4.2.4), node (v14.16.1), fastify (v3.15.0), mercurius (v7.6.0)

**Comment by mcollina** [comment]
Take a look at https://github.com/mercurius-js/mercurius/blob/master/docs/context.md.

I'm not sure how to make that available to TypeScript.

**Comment by PabloSzx** [comment]
"MercuriusContext" already has "reply", which is a "FastifyReply", that contains the request inside 
![image](https://user-images.githubusercontent.com/8672915/117327237-63d61500-ae60-11eb-9abb-7f7189f1f76e.png)

**Comment by fookit** [comment]
Thank you @mcollina and @PabloSzx
