### ISSUE TITLE
Idea: context returns valid graphql error

### ISSUE THREAD

**Issue by Floffah** [mercurius-js/mercurius#489]
Currently, if you throw an error in the context or subscription.context option function it will just make the server return status 500 and a json object of the format `{"data":null,"errors":[{}]}`

i feel like it would be a good idea to respond to the client with errors thrown in these context functions.

if this is already a thing it doesnt work with async/promise context functions

this is quite annoying to me because i interact with my database (which uses promises) in the context and throwing errors that aren't reflected is not descriptive to the client

**Comment by mcollina** [comment]
I'm all in for providing better error messages. I think this really needs an example with a failing test.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Floffah** [comment]
if i have time i might

**Comment by rbonillajr** [comment]
Hello, the problem is when you set the response (!) As required and return an error.
This happened to me recently and what I did to solve it was to remove it from being required.

**Comment by Floffah** [comment]
> Hello, the problem is when you set the response (!) As required and return an error.
> This happened to me recently and what I did to solve it was to remove it from being required.

ah yeah didnt think about that i thought just throwing an error would have the same behaviour as throwing an error in a resolver
