### ISSUE TITLE
How to access plugins in resolvers

### ISSUE THREAD

**Issue by muco-rolle** [mercurius-js/mercurius#490]
```js
const Fastify = require("fastify");
const mercurius = require('mercurius')
const fastifyCookie = require("fastify-cookie")


const app = Fastify();


app.register(fastifyCookie);

app.get("/", async () => {
    return {msg: "Fastify GraphQL API"}
})


const schema = `
    type Query {
      hello: String
    }
`

const resolvers = {
      Query: {
           hello: (parent, args, ctx) => {
    
               ctx.reply.setCookie("qid", "test", {
                   path: "/",
                   httpOnly: true,
                   secure: false,
                   sameSite: "none"
              })

              return "Hello, world!!!"
          }
     }
}

app.register(mercurius, {
    schema,
    resolvers,
    graphiql: "playground"
})

```

In the code above I would like to set the cookie from resolvers but it's not working and I tried other fastify plugins like `fastify-jwt` not working too, how can I set them up?

**Comment by mcollina** [comment]
what do you mean with "it's not working"? Which error are you getting?

**Comment by muco-rolle** [comment]
I don't get any error but I'm unable to set cookies, like the example about I can't see a cookie with the name `qid` in the browser

**Comment by simoneb** [comment]
I copied your example as-is, just adding `.listen(3000)` and I get the cookie just fine in the response:

```bash
$ curl 'http://localhost:3000/graphql' -H 'content-type: application/json' --data-raw '{"operationName":null,"variables":{},"query":"{\n  hello\n}\n"}'  -c -

{"data":{"hello":"Hello, world!!!"}}# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost     FALSE   /       FALSE   0       qid     test
```

The last line of the curl output shows the cookie received in the response.

**Comment by muco-rolle** [comment]
It was my misunderstanding of how cookies work in the browser. I was looking in the Devtools - Application/Cookies tab, I couldn't see the cookie, checking the response headers I could see it, actually, the browser was blocking it because of the `sameSite` field that was set to `None` and the `secure` field to false. I changed it from "none" to "strict" it is now working.

Thanks, guys for your time.
