### ISSUE TITLE
the playground can break using makeExecutableSchema?

### ISSUE THREAD

**Issue by YuriFontella** [mercurius-js/mercurius#497]
Hello,

I was testing the functionality all in one file, and everything was working perfectly.
[https://gist.github.com/YuriFontella/72d84cf91fc421f0be0c6abcea240405](https://gist.github.com/YuriFontella/72d84cf91fc421f0be0c6abcea240405)

I decided to create a structure with fastify-autoload and some other plugins. I ended up using some tools from graphql-tools.
[https://github.com/YuriFontella/mercurius-graphql](https://github.com/YuriFontella/mercurius-graphql)

So the playground didn't open anymore, the project starts without errors.
![image](https://user-images.githubusercontent.com/4920619/119767894-20cef680-be8e-11eb-9a48-a6560592ab84.png)

What could be locking the playground?

**Comment by mcollina** [comment]
You have a problem in the default CSP added by Helmet

**Comment by YuriFontella** [comment]
It was exactly that, I went deeper into the doc of the fastify-helmet and solved the problem.
