### ISSUE TITLE
Value Types

### ISSUE THREAD

**Issue by steinroe** [mercurius-js/mercurius#499]
[According to the Apollo Federation Docs](https://www.apollographql.com/docs/federation/value-types/), it is possible to share types, so-called value types, among subgraphs. This is e.g. useful when using a relay-based graph, where all connections share a `PageInfo` type. These value types don't "originate" in a particular subgraph. Instead, all of the subgraphs that define a value type share ownership.

An example
```
// Subgraph 1
extend type Query {
  posts: PostConnection!
}

type PostConnection {
  pageInfo: PageInfo!
  edges: [PostEdge!]!
}

type PageInfo {
  hasNextPage: Boolean
}

type PostEdge {
  node: Post!
}

type Post @key(fields: "id") {
  id: ID!
}
```

```
// Subgraph 2
extend type Query {
  users: UserConnection!
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge!]!
}

type PageInfo {
  hasNextPage: Boolean
}

type UserEdge {
  node: User!
}

type User @key(fields: "id") {
  id: ID!
}
```

When querying a gateway for `users`, in which the user service is listed before the post service, it throws `Missing @key directive in PageInfo type`. I debugged this issue and it seems like that the `PageInfo` type is assigned to the post service and it is not checked whether a type is a value type.

I am happy to provide a PR to "search for" value types and remove the assignment to a service.

**Comment by steinroe** [comment]
Should we keep this open to implement the todo I mentioned? Otherwise feel free to close. :)

**Comment by mcollina** [comment]
> Should we keep this open to implement the todo I mentioned? Otherwise feel free to close. :)

Can you please document them here?

**Comment by steinroe** [comment]
Sure!

As of now, we search for duplicates based on the type names and decide whether it is a value type by filtering out all entities (determined by the key directive) and types that are neither object, input nor interface.

[According to the Apollo Federation docs on Value Types](https://www.apollographql.com/docs/federation/value-types/) however, for types with field definitions, all fields and their types must be identical (including nullability). Further, for enums and unions, all possible values must match. Otherwise, the schema composition should fail.

Hence, summarised:
- Include enums and unions in the search for value types
- Compare the value type candidates to ensure that they are the same and if not, schema composition should fail
  - if object, interface or inputs, all fields and their types must be identical 
  - if enum or union, all possible values must match
