### ISSUE TITLE
Help with subscription

### ISSUE THREAD

**Issue by mpiorowski** [mercurius-js/mercurius#503]
Hey Guys, i would really need Your help with subscription. I cannot get it to wrok properly. I am not sure how should i name my request. This is what i got:
```
Mutation: {
    createChat: async (_: unknown, data: Chat, context) => {
      const response = await addChat(data, context);
      await context.pubsub.publish({
        topic: "CHAT_ACTIVE",
        payload: {
          activeChat: response,
        },
      });
      return response;
    },
  },
  Subscription: {
    activeChat: {
      subscribe: async (_root, _args, { pubsub }) => await pubsub.subscribe("CHAT_ACTIVE"),
    },
  }
```

and then on the client side i am trying to send data as :

```
client.send(`subscription { activeChat { id } }`);
```

But i got nothing when i hit mutation createChat. I am listening on ws://localhost:4000/graphql

Would be really greatful for help

**Comment by mcollina** [comment]
Can you provide a full example? The subscription protocol is a bit more complex than just sending something over a WebSocket connection. You can see a few examples in https://github.com/mercurius-js/mercurius/blob/master/test/subscription-client.js

**Comment by mpiorowski** [comment]
Ok, i though its that easy :) i went with appolo subscription client and its works :) Thank for help.
