### ISSUE TITLE
Propose gateway use in cluster mode

### ISSUE THREAD

**Issue by StarpTech** [mercurius-js/mercurius#504]
Hi, Node.js has a very solid https://nodejs.org/api/cluster.html module. Is there any reason not to recommend it? This would make it possible to utilize all cores. This is especially useful for an infrastructure component like the GraphQL Gateway.

**Comment by mcollina** [comment]
The load balancing algorithms are quite poor. Haproxy or analog perform a much better job at it.

I generally recommend to scale up using infrastructure instead, e.g. Kubernetes or AWS.

**Comment by StarpTech** [comment]
> The load balancing algorithms are quite poor.

Are there any results available?

> I generally recommend to scale up using infrastructure instead, e.g. Kubernetes or AWS.

Definitely, but running a gateway in cluster mode is less complex than running it by orchestration software.

**Comment by mcollina** [comment]
> > The load balancing algorithms are quite poor.
> 
> 
> 
> I have never used the cluster module. What's the point of this module if it can't match today's expectations? 😄 Legacy?
> 

Yes exactly!


> > I generally recommend to scale up using infrastructure instead, e.g. Kubernetes or AWS.
> 
> 
> 
> Definitely, but running a gateway in cluster mode is less complex than running it by orchestration software. Maybe a solid approach behind a reverse proxy for many users.

I think we should be looking into an option to run the graphql-processing logic (and possibly the whole gateway logic) within worker threads. I think we'd have better results.

**Comment by StarpTech** [comment]
Thanks, this answers my question.

**Comment by StarpTech** [comment]
> I think we should be looking into an option to run the graphql-processing logic (and possibly the whole gateway logic) within worker threads. I think we'd have better results.

Do you think of https://github.com/piscinajs/piscina? Then I'd rather prefer to scale up Node.js processes but it would be fun to experiment.

**Comment by mcollina** [comment]
My experience in all of this is that almost nothing beats infra for efficiency and flexibility and one process is enough for the dev experience.

**Comment by StarpTech** [comment]
I agree but it still requires infra. Other languages can scale up vertically with no code change.
