### ISSUE TITLE
Set-Cookie header accepted by browser but not saved!

### ISSUE THREAD

**Issue by alaarihan** [mercurius-js/mercurius#506]
Hi,

I have an issue using fastify-cookie with a Mercurius GraphQL resolver, the cookie is sent by the response but the browser didn't save it, I tried everything, I tried with and without cors and tried with localhost, https, http, secure httpOnly but it doesn't work, while when I use the same code with a normal fastify route the cookie is saved in the browser with no issues!
you can check my code from here:
https://codesandbox.io/s/vigorous-sea-cn7qt?file=/src/index.js
![image](https://user-images.githubusercontent.com/10984287/120893547-85235000-c61c-11eb-8a4b-f0fcc0596444.png)

**Comment by abevince** [comment]
Did you change the Playground `request.credentials` settings to `include`?
`"request.credentials": "include"`

**Comment by alaarihan** [comment]
No actually :(
It didn't occurred to me because I tried another GraphQL endpoint with the same playground instance and it sets the cookies without problems but I just tried it with "request.credentials": "include" and it just worked! thank you very much @abevince  for your help
