### ISSUE TITLE
Validation in Mercurius with directives

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#509]
Defining validation constraints through directives is a really nice pattern in GraphQL - I think it would be awesome to discuss a solution to help people implement this in Mercurius!

Consider the following schema definition:

```graphql
directive @constraint(
  format: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION`

type User @key(fields: "id") {
  id: ID!
  name: String!
}

type Query {
  userById(id: ID! @constraint(format: "uuid")): User
}
```

When the `userById` query operation is called, the validation implementation could recognise that the `id` input field is protected and run the specified validation (make sure it's a `uuid`) against this.

In the same way as `mercurius-auth`, this could be defined as a separate plugin. In the implementation, we would provide the user with sufficient options to make this entirely configurable:

  - Validation directive to look for
  - Validation to run when a protected input field is used

Upon startup, the plugin would:

  - Identify protected fields and input fields
  - Override or add the validation resolver to the relevant fields in the schema

Then at runtime, all the fields and input fields would be protected by these constraints! I think a plugin approach is really scalable for this and alongside existing plugins, could even be the start of a suite of plugins for Mercurius!

What do you think? If you agree with the general approach, would there be anything you'd want to change/add? For example, could we provide some default validation rather than leave it entirely up to the user?

**Comment by jonnydgreen** [comment]
I'll get started on this towards the end of next week if that works! :) @mcollina would you be okay if I created a repo for this in the `mercurius-js` org when I start the work?

**Comment by jonnydgreen** [comment]
Hi! Have started to draft a basic version (that doesn't use default validation and leaves it up to the user) in this repo: https://github.com/jonnydgreen/mercurius-validation/tree/feature/basic-validation. I'm very happy to donate this to the `mercurius-js` organisation if you would like! :)

Quick update so far:

 - From my exploration ^^, I found an initial approach creates new graphql scalars. From my testing,  this works well until GraphQL Operation variables are used. Unfortunately, because this overrides protected scalars with new scalar types, I found that this could break existing queries to the same schema if you use scalar types on an argument.
 - Currently looking at parsing the arguments directly and constructing resolvers on the fields - have got a basic working version for this - I need to do a lot of tidying and optimising

**Comment by mcollina** [comment]
I agree that the scalar approach does not work very well (I tried it in a previous project). If you'd like to donate to the org we can definitely work on this together... I was just in a call today with @simone-sanfratello talking about writing one.

**Comment by jonnydgreen** [comment]
Sounds great and good timing! :) I'll get this in the org this evening and open up a PR to show what I've already done so we can start from there if that works for you!

**Comment by jonnydgreen** [comment]
For those following, `mercurius-validation` is now released! https://github.com/mercurius-js/validation/releases/tag/v1.0.0
