### ISSUE TITLE
Custom GQL Context as class instance loses context (class `this`) during merge with default Mercurius context props

### ISSUE THREAD

**Issue by DanTsk** [mercurius-js/mercurius#514]
Looks like provided `context` must be `Object.assign` target (first argument) but not the source (second argument).

https://github.com/mercurius-js/mercurius/blob/58fe4c631285737f826be2436f5169017300bc8c/index.js#L427-L428

Are there any drawbacks, limitations, reasons why `context` is passed as a second argument? 
I can create a simple PR to fix this behavior.

**Comment by mcollina** [comment]
I don't understand the problem, could you make an example?

**Comment by DanTsk** [comment]
> I don't understand the problem, could you make an example?

For example:
```javascript
class CustomContext {

   constructor(someProp) {
      this.someProp= someProp;
   }  

   someMethod() {
       console.log(this.someProp);
   }
}

const contextInstance = Object.assign({}, new CustomContext("Foo"));
contextInstance.someMethod() // Uncaught TypeError: contextInstance.someMethod is not a function
```

`Object.assign(target, ...sources)` actually copy `sources` properties to `target`, so `sourses` lose their prototypes.

**Comment by mcollina** [comment]
Ah, yes. Would you like to send a PR?

**Comment by DanTsk** [comment]
> Ah, yes. Would you like to send a PR?

Sure, will submit it shortly.
