### ISSUE TITLE
How to handle downstream/network errors on gateway initialization?

### ISSUE THREAD

**Issue by actraiser** [mercurius-js/mercurius#520]
I have encountered the scenario that federated services may not be up yet when the gateway has initialized. In this case, the gateway will not retry polling those services in question. It's a different behavior as opposed to when everything (all services, the gateway) is up and running and, say, one of the federated services goes down. In this case, the gateway will retry polling that service according to the set 'polling'-interval. This is what I  would also expect on errors with non-ready federated services on gateway startup.

Is this a scenario overlooked in the polling mechanism or is it my task to handle this error? If the latter, how would I ask the gateway to retry connection/polling to the service in question in the errorHandler? The example in the docs only shows simple error logging but how could I actually address the problem?

The workaround right now is to restart the gateway when all federated services are up and running. This is fine for development but I would rather make sure the gateway always retries reaching out to the configured services on gateway startup errors.

Greets
-act

**Comment by mcollina** [comment]
I think this scenario was overlooked in the polling mechanism. A PR would be highly welcomed.
