### ISSUE TITLE
How to disable GraphQL introspection in production like Apollo Server?

### ISSUE THREAD

**Issue by raymclee** [mercurius-js/mercurius#521]
below message from apollo server production backend

message: "GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production"

**Comment by mcollina** [comment]
I don't think this is possible right now but it should be easy to add.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by actraiser** [comment]
I have not deployed my app into production yet, but I added validationRules like this and was under the assumption that this would work. Maybe you could try this.

```Javascript
import { NoSchemaIntrospectionCustomRule } from 'graphql';

app.register(mercurius, {
  context: buildContext,
  gateway: {
    services: [....],
    pollingInterval: 30000,
  },
  validationRules: process.env.NODE_ENV === 'production' && [
    NoSchemaIntrospectionCustomRule,
  ],
});

```
Greets
-act

**Comment by mcollina** [comment]
I think that would do.. I didn't know about it!

**Comment by lucasbittencurt** [comment]
I believe the @actraiser solution really works, I found another possibility with a library called "graphql-disable-introspection", that library do a similar approach and can be used in this way:

```js
...
import NoIntrospection from 'graphql-disable-introspection'

app.register(mercurius, {
  context: buildContext,
  gateway: {
    services: [....],
    pollingInterval: 30000,
  },
  validationRules: [NoIntrospection]
});
...
```

I don't have access but @mcollina I recommend that issue can be closed.

**Comment by mcollina** [comment]
@lucasbittencurt would you like to send a PR with a unit test to validate this and then add it to the docs?

**Comment by simoneb** [comment]
Closed via https://github.com/mercurius-js/mercurius/pull/531
