### ISSUE TITLE
Status error 500 with TypeGraphQL

### ISSUE THREAD

**Issue by angelvega93** [mercurius-js/mercurius#529]
When using TypeGraphQL and throwing an error, the server responds with a 500 status code.
This seems to happen only with TypeGraphQL.

![Screenshot_432](https://user-images.githubusercontent.com/9835055/124679504-c314cd80-de81-11eb-9c07-764aca3c2c56.png)

Example:
https://github.com/angelvega93/mercurius-typegraphql

The problem seems to be that typegraphql returns data: null, instead of data: { resolver: null }

**Comment by phantomk** [comment]
set `nullable` will return 200
```
@Query({ nullable: true})
```
