### ISSUE TITLE
How to accept queries and mutations over websocket? (client-server)

### ISSUE THREAD

**Issue by xxSkyy** [mercurius-js/mercurius#532]
I've got problem with accepting queries and mutations over websocket in mercurius and I can't find solution how to handle them. I'm implementing chat and social functions to my project and don't want every message sent over http, its overkill.
I did add to split if query/mutation has websocket property it will be sent over it than http but despite subscriptions goes well queries don't want to and I dont know way to handle it.

I've got exact same error as #195 
```
/* SENT */ {"type":"connection_init","payload":{}}
/* RECV */ {"type":"connection_ack"}
/* SENT */ {"id":"1","type":"start","payload":{"variables":{"message":"TEST!"},"extensions":{},"operationName":"InsertNotificationOverWS","query":"mutation InsertNotificationOverWS($message: String!) {\n  insertNotification(message: $message)\n}\n"}}
/* RECV */ {"type":"error","id":"1","payload":"Subscription field must return Async Iterable. Received: undefined"}
/* SENT */ {"id":"1","type":"stop"}
```

[Here](https://github.com/mercurius-js/mercurius/blob/0f101149239c2544f0dd3b912a74ef41a46e7787/docs/protocol-extension.md) is written only about server to server case when in reference are about client-server also.

How can I achieve mercurius to read queries over websocket?

**Comment by mcollina** [comment]
That's not currently supported..
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by xxSkyy** [comment]
> That's not currently supported..
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I figured it out for my project [in this fork](https://github.com/xxSkyy/mercurius) if someone wants to use it or implement fell free, I don't have enough time right now to make full PR

**Comment by indatawetrust** [comment]
do you have a pull request plan for this topic?
