### ISSUE TITLE
bug / graphiql not opening

### ISSUE THREAD

**Issue by dougg0k** [mercurius-js/mercurius#537]
Hi, I just upgraded Mercurius to 8.0 and set `graphiql` to true and it's just a empty screen with the errors below.

![Screenshot from 2021-07-20 17-00-21](https://user-images.githubusercontent.com/10801221/126387877-902572bb-d5b4-4e7d-b3ad-74b4a38e30ab.png)

**Comment by mcollina** [comment]
Can you try clearing out the cache?

**Comment by dougg0k** [comment]
Same thing and same thing in Private Window. I just end up adding Altair which seems better than GraphiQL.

**Comment by mcollina** [comment]
Can you provide some code to reproduce? I can't, everything works smoothly here.

**Comment by dougg0k** [comment]
Altair was enough here, but thanks for the help.

**Comment by NickMandylas** [comment]
@mcollina Found the issue. Was experiencing the same problem, with only a blank screen appearing and the same error. 
It appears that when you try to access GraphiQL from a domain other than localhost (like a local IP address, 192.168..).
