### ISSUE TITLE
Errors lose class instance in errorFormatter

### ISSUE THREAD

**Issue by puchm** [mercurius-js/mercurius#550]
It seems like errors lose their class when passed into the `errorFormatter`.

Here is an example repo: https://github.com/puchm/mercurius-issue-demo

Just run `npm start` and run the `testQuery` via GraphiQL.
It will demonstrate that the error is an instance of the custom `AuthenticationError` class I made if you check from inside the resolver, but it is not if you check from the custom `errorFormatter`. Just look at the console log for that.

At some point between resolving the query and running the error formatter all errors are "converted" to a GraphQLError. There is a `toGraphQLError` function inside `lib/errors.js`, however I don't think this is being run when using a custom error formatter so it must be somewhere else. Wherever this is, I think this could be the place where this information is lost.

**Comment by mcollina** [comment]
would you like to send a PR?

**Comment by puchm** [comment]
I don't know what the issue is. I was just speculating.

**Comment by puchm** [comment]
I did a lot of debugging and I found out that it is the graphql package which formats the errors before they reach mercurius. After I found out, I found a similar issue with Apollo: https://github.com/apollographql/apollo-server/issues/2898

It turns out that you can access the original error at `error.originalError` and you can also use that to check which class the error is an instance of.

I tried it with mercurius and it is also working so I am closing this.

**Comment by asciidisco** [comment]
Might be a worthy addition to the docs though :)
