### ISSUE TITLE
Opentelemetry & GraphQLInstrumentation don't work

### ISSUE THREAD

**Issue by SkeLLLa** [mercurius-js/mercurius#562]
Hi. I've setup opentelemetry like in example with some modifications that were required by opentelemetry version updates and package name changes. Provider code looks like this

```ts
import { HttpTraceContextPropagator } from '@opentelemetry/core';
import { JaegerExporter } from '@opentelemetry/exporter-jaeger';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { GraphQLInstrumentation } from '@opentelemetry/instrumentation-graphql';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { IORedisInstrumentation } from '@opentelemetry/instrumentation-ioredis';
import KnexInstrumentation from '@opentelemetry/instrumentation-knex';
import { Resource } from '@opentelemetry/resources';
import { BatchSpanProcessor } from '@opentelemetry/sdk-trace-base';
import { NodeTracerProvider } from '@opentelemetry/sdk-trace-node';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { config } from '../../../config';
import { name, version } from '../../../package.json';

export function getTraceProvider(): NodeTracerProvider {
  const exporter = new JaegerExporter({
    ...config.tracing.jaeger.options,
  });

  const provider = new NodeTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: name.split('/')[1],
      [SemanticResourceAttributes.SERVICE_NAMESPACE]: config.env,
      [SemanticResourceAttributes.SERVICE_VERSION]: version,
    }),
    forceFlushTimeoutMillis: 60_000,
  });

  registerInstrumentations({
    // tracerProvider: provider,
    instrumentations: [
      new GraphQLInstrumentation({ enabled: true }),
      new HttpInstrumentation({ enabled: true }),
      new KnexInstrumentation({ enabled: true }),
      new IORedisInstrumentation({ enabled: true }),
    ],
  });

  if (config.tracing.jaeger.enabled === true) {
    provider.addSpanProcessor(new BatchSpanProcessor(exporter));
  }

  // if (config.tracing.console.enabled) {
  //   provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));
  // }
  provider.register({
    // contextManager: new AsyncHooksContextManager().enable(),
    propagator: new HttpTraceContextPropagator(),
  });

  return provider;
}
```

Other instrumentations work fine, GraphQLInstrumentation registers it's hooks, but then they are never called.

Are there any thoughts or suggestions where the issue could be?
Thanks.

**Comment by mcollina** [comment]
Are you using node ESM? Don't expect any of this to work.

**Comment by steinroe** [comment]
I am having the same issues (without ESM). The trace works, but only on a route "/graphql" level and not for each individual resolver.

**Comment by SkeLLLa** [comment]
> Are you using node ESM? Don't expect any of this to work.

No, unfortunately that's just typescript.

**Comment by jonnydgreen** [comment]
Have you tried seeing if the OTEL diagnostic logger gives you any more info? https://github.com/open-telemetry/opentelemetry-js#setting-the-global-diagnostic-logger

**Comment by SkeLLLa** [comment]
Seems I've found the problem.

Instrumentation patches 3 function of 'graphql' library. So the main thing I've missed in example that `require` and registering instrumentation should happen before any other `require` happen (including requiring `mercurius` itself), since require will be cached and "patching" will happen on a function that already required by mercurius.

Maybe it worth mention this little thing in docs alongside with an example of using it in mercurius.

**Comment by jonnydgreen** [comment]
That makes sense, yeah!
