### ISSUE TITLE
GraphiQL fetcher uses HTTP for subscriptions

### ISSUE THREAD

**Issue by puchm** [mercurius-js/mercurius#568]
I have been experimenting with subscriptions and the way mercurius currently uses GraphiQL is slightly wrong. The [fetcher](https://github.com/mercurius-js/mercurius/blob/e0f672c4a3dc2054e9557d863183aa58e265f34b/static/main.js#L21-L30) always uses the fetch API which should not be used for subscriptions which use WebSockets.

Apparently, there is a package (`@graphiql/create-fetcher`) which comes with a function that allows for an easy way to create a fetcher, there is some good documentation on this here: https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md

Do you agree with me that the current way of doing it is wrong? All subscriptions just return `null` when requested via GraphiQL or even throw an error if the response is non-nullable.

I can maybe look into making a PR about this next week if we agree on using `@graphiql/create-fetcher`.

**Comment by mcollina** [comment]
Would you like to send a PR? Using that package would be spectacular, I did not know it existed.

**Comment by puchm** [comment]
I have created a PR that tries to address this but I am stuck with the WebSocket closing with code 1002. Read the PR for further info. It's a draft for now - any ideas on how to fix that?
