### ISSUE TITLE
Ambiguous error message 400

### ISSUE THREAD

**Issue by lewispham** [mercurius-js/mercurius#572]
After upgrading to version 8.2.1, I'm receiving this error for all syntax errors and also the query depth error.

```json
{
    "statusCode": 400,
    "code": "MER_ERR_GQL_VALIDATION",
    "error": "Bad Request",
    "message": "Graphql validation error"
}
```
This error is obviously not enough for debugging.

After double-checking the issue then it's because of my custom error formatter.
```ts
            errorFormatter: (result: ExecutionResult) => {
                let statusCode = 500;
                if (result.errors) {
                    const firstError = result.errors[0];
                    if (firstError.extensions) {
                        statusCode = firstError.extensions.statusCode;
                    }
                }
                return {
                    statusCode,
                    response: result
                };
            }
```
I still can not figure out the issue of that error formatter function. It's only for changing the http status code. But removing it solves this issue.

**Comment by mcollina** [comment]
Which was the last released that worked fine for you?

I think you might want to add some logging to your errorFormatter.

**Comment by lewispham** [comment]
@mcollina It's v7.4.0 . Which sort of logs do you need? I tried to log `result.errors` and the error is the correct one.

**Comment by mcollina** [comment]
What is the correct error?

Could you please upload an example to reproduce?

There is nothing that strikes me as changing this between v7.4.0 and v7.5.0.

**Comment by lewispham** [comment]
@mcollina I've just created this repo for reprducing the issue.
https://github.com/lewispham/mercurius-572
You can follow the readme to reproduce it.

**Comment by linkthai** [comment]
It works for me, but the current version requires an extra context arguments. This issue should be solved but I think we need to document this in the errorFormatter section.

```ts
import mercurius from 'mercurius';
const { defaultErrorFormatter } = mercurius;

fastify.register(mercurius, {
    schema,
    errorFormatter: (result, ctx) => {
      const def = defaultErrorFormatter(result, ctx);

      return {
        statusCode: def.statusCode || 500,
        response: def.response,
      };
    },
});
```

**Comment by mcollina** [comment]
@linkthai would you mind to send a PR to update the docs?

**Comment by linkthai** [comment]
@mcollina alright, I made a pull request here #1034
