### ISSUE TITLE
Subscription Protocols: graphql-transport-ws

### ISSUE THREAD

**Issue by steinroe** [mercurius-js/mercurius#574]
Hi,

we are currently moving away from Apollo client and using urql now (highly recommend!). Urqls recommended subscription client is graphql-ws, [which is using](https://github.com/enisdenjo/graphql-ws/discussions/237#discussioncomment-1337652) the `graphql-transport-ws` protocol and not the `graphql-ws` protocol that is used by the [deprecated subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/231c1b0d25b20090033140b83c8a39871d4ed88c/src/protocol.ts#L1). (Took me some time to get over the protocol and library names...)

It seems like mercurius is supporting the  `graphql-ws` protocol / `subscriptions-transport-ws` library only 
https://github.com/mercurius-js/mercurius/blob/037cc1f35c3e4901d3dc219a9ef88b43ac017b0e/lib/subscription.js#L12-L17

Are there plans to move to the new protocol? Or maybe enable both? I am too inexperienced with subscription protocols to tackle this issue on my own, but with some help I am happy to create a PR.

**Comment by mcollina** [comment]
This might be explaining why https://github.com/mercurius-js/mercurius/pull/570 is failing cc @punchm.

I think we should support both.

**Comment by puchm** [comment]
Yes this is probably the same reason why I was failing there, I found a workaround though.
I think it would be good to support the new protocol since the one we are using right now is deprecated.
