### ISSUE TITLE
Export MercuriusPlugin type

### ISSUE THREAD

**Issue by trey-m** [mercurius-js/mercurius#578]
I'm looking to decorate my fastify instance with the `MercuriusPlugin` type but it's not exported for use.

Line: https://github.com/mercurius-js/mercurius/blob/037cc1f35c3e4901d3dc219a9ef88b43ac017b0e/index.d.ts#L232

ie. 
```js
declare module 'fastify' {
  interface FastifyInstance {
    graphql: MercuriusPlugin
  }
}
```

So we can properly call the following without type errors:
 ```js
fastify.graphql.addHook('preValidation', async (schema, document, context) => {
  await asyncMethod()
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
