### ISSUE TITLE
Loaders: cache disabled by default?

### ISSUE THREAD

**Issue by darrenfurr** [mercurius-js/mercurius#598]
Is caching disabled by default on loaders?

It looks that way...(which I am ok with)...
https://github.com/mercurius-js/mercurius/blob/b671de31178395ea53f2ea39c19cc3f8d80be8eb/index.js#L389

But the docs make it seem that it is enabled by default.
https://mercurius.dev/#/docs/loaders

**Comment by mcollina** [comment]
The cache must be disabled for subscriptions, otherwise long running connections would cache data indefinitely, leaking memory in the process. It's also not functionally correct, as if you are using subscriptions you want fresh data, not possibly stale ones.

**Comment by mcollina** [comment]
For Query resolvers?

**Comment by darrenfurr** [comment]
> For Query resolvers?

Yes...A loader is an utility to avoid the 1 + N query problem of GraphQL. Each defined loader will register a resolver that coalesces each of the request and combines them into a single, bulk query.

**Comment by mcollina** [comment]
By default the loaders specified for the resolved caches the value for the duration of that query.
