### ISSUE TITLE
Behaviour of Mercurius errors and their associated HTTP status codes

### ISSUE THREAD

**Issue by jonnydgreen** [mercurius-js/mercurius#599]
I have been looking into the following reported issue: https://github.com/mercurius-js/auth/issues/32#issuecomment-937886976

And have replicated with the following test:

```js
test('errors - should use statusCode from error if present', async (t) => {
  const schema = `
    type Query {
      error: String!
    }
  `

  const resolvers = {
    Query: {
      error () {
        throw new ErrorWithProps('Error', undefined, 200)
      }
    }
  }

  const app = Fastify()

  app.register(GQL, {
    schema,
    resolvers
  })

  await app.ready()

  const res = await app.inject({
    method: 'GET',
    url: '/graphql?query={error}'
  })

  t.equal(res.statusCode, 200)
})
```

However, it got me thinking about how we should be handling HTTP status codes in general.

As it stands, we have the following behaviour for valid GraphQL queries in Mercurius:

- If GraphQL execution response `data === null` => statusCode: `500`
- If GraphQL execution response `data !== null` => statusCode: `200`

If we are to add support for the HTTP status code being controlled by `ErrorWithProps` in the returned error list, we probably need to define the behaviour for the following edge cases:

 - Multiple errors in the error list that have multiple status codes - which one do we pick?
 - Multiple errors in the error list where some contain status codes and some don't - which one do we pick?

Based on the above, does it make sense to control the HTTP status codes through the `ErrorWithProps` errors? Or should we be pragmatic and just take the first statusCode we can find?

What do you reckon?

**Comment by mcollina** [comment]
It's important to note that this behavior can be fully customized by changing the `errorFormatter`.
This issue refers to the _default_ behavior.

In general I think we should change this as:

1. if there is one error and no data, use the statusCode property. If it's not set, use 500.
2. if there are both errors and data, use 200.

The alternative is to always return 200 even if there are errors, like apollo does.

I don't think this is standardized anyhow, but maybe a quick survey of the market might be necessary.

**Comment by jonnydgreen** [comment]
Here's a quick update from the survey I did:

| Real APIs      | Results                                                                                                                                                |
| -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Hasura.io      | 200 OK on everything (previously had 4xx and 5xx status codes)                                                                                         |
| GitHub API     | 200 OK on everything                                                                                                                                   |
| Contentful API | 400 on validations/complexity errors. [5xx supported, but not from within the response](https://www.contentful.com/developers/docs/references/errors/) |
| Shopify        | [5xx supported, but they are not GraphQL responses as far as I could tell](https://shopify.dev/api/admin-graphql#status_and_error_codes)                                      |

| GraphQL Server  | Results                                        |
| --------------- | ---------------------------------------------- |
| Apollo Server   | 4xx on input errors, 200 OK on everything else |
| express-graphql | 4xx on input errors, 200 OK on everything else |
| graphql-yoga    | 4xx on input errors, 200 OK on everything else |

From the survey, there are definitely several different opinions on how to set HTTP Status codes. Notably, none of them set a non-2xx code as a result of an execution response (at least, I never observed this behaviour).

I also found this really interesting draft spec for serving GraphQL over HTTP (if/when this is finalised, it would be good to write some tests for this to ensure compliance!): https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes Although we can't take it as a spec (yet), it does suggest that what you suggested earlier is the right direction going forward!

I found the following statement particularly insightful:

> In case of errors that completely prevent the successful execution of the request, the server SHOULD respond with the appropriate status code depending on the concrete error condition.

I do agree with this statement and I think it is especially relevant for your original suggestion (when data is `null`):

> In general I think we should change this as:
>  - if there is one error and no data, use the statusCode property. If it's not set, use 500.
>  - if there are both errors and data, use 200.

An addition I would suggest would be to account for multiple errors and no data? I'm thinking in this case, we use 500 as selecting the first error statusCode could be misleading (note, this approach is the current default behaviour)?

The only concern I would have is that this is differing slightly from the market consensus (note, it doesn't have complete consensus). However, after thinking about it a bit, I think it's actually okay because as long as the default is spec compliant, we are all good :)

What do you think? Do you agree/disagree?

**Comment by mcollina** [comment]
I think we should use 400 in case there are multiple errors and no data. It likely means the request was accepted but there were some controlled errors.

I think we should also document clearly all the above... and how to implement the 200-for-everything behavior.

This would be a good contribution!

**Comment by simoneb** [comment]
Shall we close this issue since the PR which addresses it is merged? Or are we waiting for the next release in which it will be included?
