### ISSUE TITLE
unable to get __resolveReference to execute

### ISSUE THREAD

**Issue by mikaelkaron** [mercurius-js/mercurius#603]
I've copied the [Federation with __resolveReference caching](https://mercurius.dev/#/docs/federation?id=federation-with-__resolvereference-caching) example and made a _small_ modification:

```
const resolvers = {
  Query: {
    me: () => {
      console.log('Resolver:Query')
      return users['1']
    }
  },
  User: {
    __resolveReference: async (source, args, context, info) => {
      console.log('Resolver:User')
      return users[source.id]
    }
  }
}

const loaders = {
  User: {
    __resolveReference: async (queries, context) => {
      console.log('Loaders:User')
      // This should be a bulk query to the database
      return queries.map(({ obj }) => users[obj.id])
    }
  }
}
```

However when I try to query the only thing I see on the console is `Resolver:Query` - so to me it looks like the `__resolveReference` is never called (neither on the `resolvers` _or_ `loaders`)

I've also tried to have `__resolveReference` exclusively in `resolvers` or `loaders` but there's no difference.

**Comment by PacoDu** [comment]
> Hm. From the code examples on the [federation page](https://mercurius.dev/#/docs/federation) I understood it that `__resolveReference` would be called normally. So if I understand it correctly `__resolveReference` will _only_ be called `gateway` is configured?

`__resolveReference` is the resolver used for the `_entities` Query which is sent by the gateway when it needs to resolve a reference between services (like https://github.com/mercurius-js/mercurius/blob/master/examples/gateway.js#L107)

**Comment by mikaelkaron** [comment]
> __resolveReference is the resolver used for the _entities Query which is sent by the gateway when it needs to resolve a reference between services (like https://github.com/mercurius-js/mercurius/blob/master/examples/gateway.js#L107)

That makes a lot more sense. Maybe just mentioning it in the fereration page could help others like me.
