### ISSUE TITLE
errors path missing

### ISSUE THREAD

**Issue by sooxt98** [mercurius-js/mercurius#610]
both errors should include `path` as below, how could i obtain the path info
``` json
"path" : ["mutation", "add"]
```
Path missing from the example
![image](https://user-images.githubusercontent.com/13378059/138130982-4d8b8c45-8c45-4c13-82a4-5e303c464752.png)

### What we expected
https://github.com/rmosolgo/graphql-ruby/issues/1967
![image](https://user-images.githubusercontent.com/13378059/138553883-778e5e6c-2553-45ba-a871-b594bb02c322.png)

**Comment by sameer-coder** [comment]
Not able to reproduce the problem. I tested with the example mentioned above(basic.js) and I am able to get back `path` in the errors array

**Comment by sooxt98** [comment]
@sameer-coder @mcollina did you guys really tested out? path is still missing
![image](https://user-images.githubusercontent.com/13378059/141078261-74fb66f2-d1d9-41ed-b13d-d9bf2c8845bc.png)

**Comment by mcollina** [comment]
I don't think this is fixable without a change inside graphql-js, which is not going to happen unless the spec changes.

**Comment by sooxt98** [comment]
@mcollina In addition, is it possible to know which input field causing type error? since the path is missing, 
``` json
"path" : ["mutation", "userRegister", "password"] // Field name here
```
![image](https://user-images.githubusercontent.com/13378059/142160993-70300946-470b-425c-8255-15c9c3b023f9.png)
