### ISSUE TITLE
`errorHandler` question

### ISSUE THREAD

**Issue by wiktor-obrebski** [mercurius-js/mercurius#616]
Currently `errorHandler` [plugin option](https://mercurius.dev/#/docs/api/options?id=plugin-options) function sometimes is triggered, but sometimes is ignored. 

In `index.js` file `errorFormatter` is used to format some errors, without calling `errorHandler`.
https://github.com/mercurius-js/mercurius/blob/6c523d96f57eb08a33a3a2b7b2e1d48c4e12e869/index.js#L558-L563

But in routes, `errorHandler` handle the error and possibly call `errorFormatter`.
https://github.com/mercurius-js/mercurius/blob/6c523d96f57eb08a33a3a2b7b2e1d48c4e12e869/lib/routes.js#L132-L140

It gives strange situation when some errors are handled in custom way I want them too, but some not. I can not use `errorFormatter` for everything, because it do not get `request` instance, so I have no contextual information e.g. to log things correctly.

To be more specific, the `errorHandler` is not used when the error happen in one of my schema executors I using (in request context).

My question: is this expected situation? I found it quite confusing. Should we try to use `errorHandler` in both error flows in some way?

**Comment by wiktor-obrebski** [comment]
@mcollina any chance you can take a look? I would like to confirm if this is a real issue, or I do not understand something correctly. If I'll get confirmation I will try to provide a pull request to fix this.

**Comment by mcollina** [comment]
It's ok the flow is split. If a resolver rejects/throw, that error is going to end inside errorFormatter: these errors will be part of the "usual" GraphQL response. 
The Fastify `errorHandler` is being called if there is an error _outside_ of the GraphQL flow. These are outside of the GraphQL responses.

Can you make an example that makes this confusing?

This might be better documented, would you like to send a PR?

**Comment by wiktor-obrebski** [comment]
>  If a resolver rejects/throw, that error is going to end inside errorFormatter: these errors will be part of the "usual" GraphQL response. (...) Can you make an example that makes this confusing?

I need to add logic to hande resolvers errors by myself. I need to log information about this (contextually, with request info etc.) to stdout. Additionally, I want to report it to Sentry. On both cases, I want add few contextual information (like e.g. `reqId` added automatically by fastify).
But `errorFormatter` has been designed to format errors, not handle them. So there is not access to current `req` object in the function. So I can not get the contextual information I need. I guess there can be more reasons to handle the errors in custom way.

Generally I found it very confusing that some errors go thru `errorHandler` and some not. 

> This might be better documented, would you like to send a PR?
I will after we will explain things here.

**Comment by mcollina** [comment]
> But errorFormatter has been designed to format errors, not handle them.

resolver errors __must__ be sent to the user. The `errorFormatter` is the option we use to do so. You cannot handle the errors there as they still need to sent to the end user.

>  So there is not access to current req object in the function. So I can not get the contextual information I need. I guess there can be more reasons to handle the errors in custom way.

I see no problem in adding the informations that are missing to the errorFormatter. I think the graphql context would suffice. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by wiktor-obrebski** [comment]
ok, I will try to provide a PR this week.

**Comment by eduhenke** [comment]
I have the same use-case as @wiktor-obrebski, and I too found it confusing and only figured why it wasn't working because of this issue
