### ISSUE TITLE
Best place to log errors

### ISSUE THREAD

**Issue by ramiel** [mercurius-js/mercurius#619]
I looked into documentation and among issues but I couldn't find anything relevant. My goal is to simply log any error before it get sent as response. I don't need to do anything on the error but logging it. Where should I hook to do that?

**Comment by mcollina** [comment]
What kind of errors would you like to catch? You want to log all resolver errors?

**Comment by ramiel** [comment]
Yes, I just want to log all resolver errors. I don't know if this should be done at fastify level, but probably through mercurius would be better.

**Comment by ramiel** [comment]
Ok, this way I'm able to log the same error that is sent to the requester. I'm trying to find a way to log the proper error, with stack trace.

**Comment by mcollina** [comment]
what's your current code?

**Comment by ramiel** [comment]
This is the relevant part

```ts
app.register(mercurius, {
      schema: schema as any,
      graphiql: false,
      context: contextProviderFn,
      persistedQueryProvider:
        mercurius.persistedQueryDefaults.automatic(),
      errorFormatter: (error, ...args) => {
        logger.error(error);
        return mercurius.defaultErrorFormatter(error, ...args);
      }
});
```

**Comment by mcollina** [comment]
In your example, `error` should be the "proper" error. Could you make an example of why it is not the "proper" one?

**Comment by ramiel** [comment]
Indeed. The problem is with my usage of pino: `logger.error(error)` cannot show the right stacktrace. This is working instead

```ts
if (error.errors) {
  error.errors.forEach((e) => logger.error(e))
} else {
  logger.error(error);
}
```


The right version shows

```
[1636023734368] ERROR (35970 on hostname): Cannot read property 'songsList' of undefined
    TypeError: Cannot read property 'songsList' of undefined
        at SongResolver.songsList (/.../graphql/resolvers/SongResolver.ts:112:42)
        [... stacktrace]
```

while using `logger.error(error)` just shows

```
[1636023934398] ERROR (36371 on hostname):
    errors: [
      {
        "message": "Cannot read property 'songsList' of undefined",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "songsList"
        ]
      }
    ]
    data: null
```
