### ISSUE TITLE
Error response doesn't trigger Fastify `onResponse` hook?

### ISSUE THREAD

**Issue by markrzen** [mercurius-js/mercurius#626]
I wanted to check if this was expected. I know that Mercurius doesn't have `onResponse` as a lifecycle hook, but I would expect that any response at all from Mercurius would trigger the `onResponse` hook in Fastify.

Expected or a bug to be fixed?

**Comment by markrzen** [comment]
And example would be submitting an invalid query. No `onResponse` hook is called.

Though when a normal route schema validation issue occurs, we certainly do have `onResponse` hook called.

**Comment by mcollina** [comment]
Could you please prepare an example to reproduce this problem? Something that uses fastify.inject() would be fine.

**Comment by markrzen** [comment]
I have this on my list, sorry for the delay. Busy busy as usual.

**Comment by markrzen** [comment]
I am going to close this until I have time to review.
