### ISSUE TITLE
Pass the resolvers info parameter to loaders

### ISSUE THREAD

**Issue by paolochiodi** [mercurius-js/mercurius#627]
The documentation states that

> Each loader function has the signature loader(queries, context). queries is an array of objects defined as { obj, params } where obj is the current object and params are the GraphQL params (those are the first two parameters of a normal resolver).

This is implemented in https://github.com/mercurius-js/mercurius/blob/b671de31178395ea53f2ea39c19cc3f8d80be8eb/index.js#L371-L376

I'm suggesting to also pass the "info" param (it's the fourth one) from a normal resolver.

**Comment by mcollina** [comment]
Will it all be the same? Why do you need it?

**Comment by paolochiodi** [comment]
To be honest, I'm not sure. I think in most cases it will be the same but this will need to support the case when it's not.

We mainly use it to derive which fields have been requested for an object and optimise database queries to only load necessary data (this is likely a minor optimisation in most cases, but for some bigger objects it may make a difference).

Loaders make this more complicated because you need to define the comment set of fields from the multiple - so whether this is worth it should be evaluated on a case by case. 
But would be good to have the option to do that.

I also assume there may be other use cases for the info object.

**Comment by mcollina** [comment]
How would you implement it? As part of the array?

I think that's useful only if it's  going to be the same for all.

**Comment by sameer-coder** [comment]
I am working on this issue. Will create a PR soon.

**Comment by paolochiodi** [comment]
@sameer-coder that was quick, thanks for the fix!
@mcollina any plan for a release?

**Comment by paolochiodi** [comment]
@mcollina never mind, just noticed a new release has been published a few minutes ago
