### ISSUE TITLE
Doesn't work with graphql v16+

### ISSUE THREAD

**Issue by Manubi** [mercurius-js/mercurius#628]
Hi,
just wanted to update the graphql package to version 16 but fastify/mercurius doesn't seem to like it. 

![CleanShot 2021-11-08 at 14 38 09](https://user-images.githubusercontent.com/20935138/140751737-964b551d-9499-4d23-a480-dbcc1c04285a.png)

`No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<MercuriusOptions, Server>, opts?: FastifyRegisterOptions<MercuriusOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type 'NexusGraphQLSchema' is not assignable to type 'string | GraphQLSchema | string[] | undefined'.
      Property 'isPossibleType' is missing in type 'NexusGraphQLSchema' but required in type 'GraphQLSchema'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<MercuriusOptions, Server>, opts?: FastifyRegisterOptions<MercuriusOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof mercurius' is not assignable to parameter of type 'FastifyPluginAsync<MercuriusOptions, Server>'.
      Type 'void' is not assignable to type 'Promise<void>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<MercuriusOptions, Server> | FastifyPluginAsync<MercuriusOptions, Server> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type 'NexusGraphQLSchema' is not assignable to type 'string | GraphQLSchema | string[] | undefined'.ts(2769)
schema.d.ts(83, 3): 'isPossibleType' is declared here.`

Thanks for your help!

**Comment by mcollina** [comment]
Seems about right, we have not updated to GraphQL v16 yet.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by Manubi** [comment]
Guess that doesn't make sense right now. 
graphql-shield doesn't have updated to v16. either.
[PR](https://github.com/maticzav/graphql-middleware/pull/477)

Also why this PR for an update of graphql in mercurius failed.  [PR](https://github.com/mercurius-js/mercurius/pull/620)

**Comment by giacomorebonato** [comment]
Hi @Manubi , the PR seems to be failing because of this:

```bash
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from graphql-middleware@6.1.12
npm ERR! node_modules/graphql-middleware
```

graphql-middleware (Mercurius dev dependency) has peer dependency on graphql < 16, so it needs to be upgraded too.

**Comment by mcollina** [comment]
We can actually remove that dependency and add the relative example: https://github.com/mercurius-js/mercurius/blob/b671de31178395ea53f2ea39c19cc3f8d80be8eb/examples/graphql-shield-authorization.js.
That dependency is not needed to run, build or test Mercurius.

**Comment by giacomorebonato** [comment]
Thanks @mcollina , I'll look into that.

**Comment by DanTsk** [comment]
Any updates on this?

**Comment by mcollina** [comment]
> Any updates on this?

Would you like to work on it?

**Comment by DanTsk** [comment]
> > Any updates on this?
> 
> Would you like to work on it?

Yes, on the next week I will have some capacity to fix this, but don’t want to interrupt someone’s existing work.

**Comment by mcollina** [comment]
Go for it!

**Comment by giacomorebonato** [comment]
Sorry, I can't help with this at the moment
