### ISSUE TITLE
Add graphql playground 

### ISSUE THREAD

**Issue by victororlyk** [mercurius-js/mercurius#632]
Hi, It would be cool if the package would have playground instead/along with regular grpahiql ide. 
I believe there was a pr merged before but now we do not have playground in the package. or it is strongly hidden
https://github.com/mercurius-js/mercurius/issues/52
Thanks

**Comment by smolinari** [comment]
@victororlyk - you can plugin in Altair. It blows away Playground and Graphiql. 

https://mercurius.dev/#/docs/plugins?id=altair-fastify-plugin

Or use the Altair Chrome Extension: https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja?hl=en

Scott

**Comment by mcollina** [comment]
We supported Playground in the past. however As https://github.com/mercurius-js/mercurius/issues/306 states, Playground is deprecated / unmaintained - so we removed it.

If features are missing, they can be added to https://github.com/mercurius-js/mercurius/blob/master/static/main.js. It should be a preset or some other missing configuraiton.
