### ISSUE TITLE
Authentication and Authorization Example

### ISSUE THREAD

**Issue by mthota15** [mercurius-js/mercurius#65]
Any Example on how to leverage fastify-jwt plugin with fastify-gql for authentication and Authorization example?

**Comment by thiagokroger** [comment]
Here's an example using fastify-jwt and fastify-auth

`
const fastify = require("fastify")();

const users = [
  { id: 1, name: "matteo", email: "matteo@email.com", password: "12345" },
  { id: 2, name: "thiago", email: "thiago@email.com", password: "123456" }
];

const getToken = (email, password) => {
  const user = users.find(u => u.email === email && u.password === password);
  return user ? fastify.jwt.sign({ id: user.id }) : null;
};

const getUserName = id => {
  const user = users.find(u => u.id === id);
  return user ? user.name : null;
};

const verifyJWT = async (request, reply) => {
  try {
    await request.jwtVerify();
  } catch (err) {
    reply.send(err);
  }
};

const registerRoutes = () => {
  fastify
    .post("/login", async (request, reply) => {
      const { email, password } = request.body;
      try {
        return reply.graphql(
          `{ token(email: "${email}", password: "${password}") }`
        );
      } catch (error) {
        return reply.error(error);
      }
    })
    .route({
      method: "GET",
      url: "/user-name",
      preHandler: fastify.auth([fastify.verifyJWT]),
      handler: (request, reply) => {
        const userId = request.user.id;
        try {
          return reply.graphql(`{ userName(id: ${userId}) }`);
        } catch (error) {
          return reply.send;
        }
      }
    });
};

fastify
  .register(require("fastify-auth"))
  .register(require("fastify-jwt"), { secret: "supersecret" })
  .register(require("fastify-gql"), {
    schema: `
      type Query {
        token(email: String, password: String): String,
        userName(id: Int): String
      }
    `,
    resolvers: {
      Query: {
        token: async (_, { email, password }) => getToken(email, password),
        userName: async (_, { id }) => {
          return getUserName(id);
        }
      }
    }
  })
  .decorate("verifyJWT", verifyJWT)
  .after(registerRoutes)
  .listen(9000, (err, address) => {
    if (err) {
      console.log(err);
      process.exit(1);
    }
    console.log("Server running at: " + address);
  });
`

Full code here: [fastify-graphql-jwt-example](https://github.com/thiagokroger/fastify-graphql-jwt-example)

**Comment by Eomm** [comment]
I have started a basic example that fit your needs for authentication in the example repo.

It would be great if you would like to work together to complete that example 👍

**Comment by StevenVerbiest** [comment]
The example of @Eomm authenticates  a url endpoint in fastify. Is there a way to authenticate a resolver? Like in [type-graphql](https://github.com/MichalLytek/type-graphql/blob/master/docs/middlewares.md#how-to-use).

**Comment by mcollina** [comment]
Not at this point, but it would be great to support something.

**Comment by dougg0k** [comment]
@StevenVerbiest Maybe you are looking for something like this? https://github.com/kkemple/graphql-auth

Another way to authenticate is through schema fields, you can do so by using Schema Directives.

**Comment by dougg0k** [comment]
Nevermind, `graphql-auth` doesn't seem to be compatible with `fastify-gql` at the moment.

**Comment by dougg0k** [comment]
I actually built one myself, with the same idea.

```
export const withAuth = (rolesAllowed: Array<string>, next: any) => (
	root: any,
	args: any,
	context: any,
	info: any,
) => {
	if (!context.isAuthenticated) {
		throw new Error("Unauthorized");
	}
	if (!rolesAllowed.includes(context.authorizedAs)) {
		throw new Error("Forbidden");
	}
	return next(root, args, context, info);
};
```
```
context: async (request: FastifyRequest) => {
	...
	return {
		isAuthenticated: isAuth,
		authorizedAs: role,
	};
}
```
```
Mutation: {
	createUser: withAuth(
		[ROLES.ADMIN],
		async (_parent: any, args: any) => {
			return await createUser(args);
		},
	),
},
```

**Comment by stolinski** [comment]
Along these same lines, I'm trying to integrate with https://github.com/fastify/fastify-cookie and not having any luck settings cookies via the reply passed into context.

**Comment by mcollina** [comment]
This probably needs some docs and a well built example. I have mercurius in production with both authentication and authorization.

**Comment by jmfury** [comment]
Figured I would drop a note here that [`graphql-shield`](https://github.com/maticzav/graphql-shield) works as expected with `mercurius`.

It's one path for authorization, as a `graphql-middleware`, which may work for some use cases.

I could contribute an example if that'd be of interest.

**Comment by mcollina** [comment]
An example would be amazing!

**Comment by muco-rolle** [comment]
@stolinski were you able to set cookies with https://github.com/fastify/fastify-cookie ?

**Comment by mcollina** [comment]
I think there is a solid example in https://github.com/mercurius-js/auth.

**Comment by muco-rolle** [comment]
> I think there is a solid example in https://github.com/mercurius-js/auth.

@mcollina this is so good, the problem I have, is Fastify plugins are not working, like `fastify-cookie` and `fastify-jwt` 

I'm using this example project https://github.com/mercurius-js/mercurius-typescript/tree/master/examples/codegen-gql-files 

and I installed `fastify-cookie`  with the field credentials field set to include in playground `"request.credentials": "include",` but cookies are not being setted

**Comment by mcollina** [comment]
I don't see fastify-cookie in there.

**Comment by frndvrgs** [comment]
I spend some time trying to figure out why my fastify-cookie is not sending my cookies to the client from my graphql resolvers.

The first problem I found was on the client side, axios just not parsing/setting the cookie correctly, and the second one is because the authentication query are coming through my gateway service. The cookies headers are sent back with the response to the gateway but they do not follow the way back to the client who made the request.

I fixed this only sending the auth request query outside the gateway, directly to my authentication service host but I think its not ideal. The gateway are running on a entire separate host, using mercurius gateway mode.

Is there some way to send these cookie headers through the gateway mode back to the client?

**Comment by mcollina** [comment]
I don't think we are forwarding the cookies back in gateway mode.

**Comment by frndvrgs** [comment]
Thank you for clarifying, so I will keep my authentication out of the gateway and work the authorization with some ideas I found here.

As soon as it is ready I will share another example of project with both auth processes, including federation and microservices

**Comment by frndvrgs** [comment]
For those who still need an example for authorization / authentication using fastify-cookies + mercurius, these solutions worked very well for me:

graphql resolver authorization:
[https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/services/graphql/resolvers.ts](https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/services/graphql/resolvers.ts)

session handler, verifying JWT and creating/removing cookies:
[https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/handlers/session.ts](https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/handlers/session.ts)

http router for authentication:
[https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/services/http/routes.ts](https://github.com/frndvrgs/electronic-publishing/blob/main/server/account/src/infrastructure/services/http/routes.ts)

To read the cookies inside the resolvers / loaders you need to check the **context.reply.request** object.

**Comment by louwers** [comment]
@frndvrgs Anndd it's donw.

**Comment by smolinari** [comment]
I'd consider authentication and authorization much too faceted in terms of ways to get them accomplished to be able to give good examples. They will most definitely only fit certain use cases and no way could the examples cover all possible use cases. Thus, I think this issue can be closed.

Scott

**Comment by marco-ippolito** [comment]
@frndvrgs now it is possibile to forward headers from the services to the gateway, this means cookies too. read documentation here: https://github.com/mercurius-js/mercurius-gateway#collectors
