### ISSUE TITLE
Remove secure-json-parse from Gateway

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#650]
I think we could safely consider the target services as trusted and remove the secure-json-parse call in https://github.com/mercurius-js/mercurius/blob/25500ddf95f3cfafaab23d03248ac6c52740142c/lib/gateway/request.js#L92.

Even better, we could put it behind an option.

**Comment by radomird** [comment]
I'll create a PR for this.

**Comment by radomird** [comment]
@mcollina is there a name for the option that you prefer?
