### ISSUE TITLE
Couldn't use typegraphql with mercurius

### ISSUE THREAD

**Issue by ghyath5** [mercurius-js/mercurius#665]
I am trying to use typegraphql prisma generator, when I pass the built schema to mercurius plugin it shows this error

`No overload matches this call. Overload 1 of 3, '(plugin: FastifyPluginCallback<MercuriusOptions, Server>, opts?: FastifyRegisterOptions | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error. Type 'GraphQLSchema' is not assignable to type 'string | string[] | GraphQLSchema | undefined'. Type 'GraphQLSchema' is missing the following properties from type 'GraphQLSchema': description, getImplementations, isSubType Overload 2 of 3, '(plugin: FastifyPluginAsync<MercuriusOptions, Server>, opts?: FastifyRegisterOptions | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error. Argument of type 'typeof mercurius' is not assignable to parameter of type 'FastifyPluginAsync<MercuriusOptions, Server>'. Type 'void' is not assignable to type 'Promise'. Overload 3 of 3, '(plugin: FastifyPluginCallback<MercuriusOptions, Server> | FastifyPluginAsync<MercuriusOptions, Server> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error. Type 'GraphQLSchema' is not assignable to type 'string | string[] | GraphQLSchema | undefined'.`

![q1](https://user-images.githubusercontent.com/49321826/143040690-0b9bcb68-c67c-4868-87b0-da0a475250bc.PNG)
![q2](https://user-images.githubusercontent.com/49321826/143040698-c06aceb7-9eb7-4f28-9d76-b308c5224d3d.PNG)

**Comment by mcollina** [comment]
I don't have a clue, I'm sorry I can't help.

**Comment by ghyath5** [comment]
@mcollina 
I just delete `graphql` from my dependinses it works perfectly, because mercurius doesn't support graphql 16 yet

**Comment by essarn** [comment]
Facing the same problem using the latest versions of all packages, how can this be fixed?

**Comment by jonnydgreen** [comment]
> Facing the same problem using the latest versions of all packages, how can this be fixed?

Could you output the following or even better provide a reproducible example please?

```sh
npm why graphql
npm why fastify
npm why mercurius
npm why type-graphql
```

**Comment by essarn** [comment]
Actually the problem seems to be that `type-graphql` doesn't support `v16` yet (see https://github.com/MichalLytek/type-graphql/issues/1100). Everything is working when using older versions so I guess that's the blocker.

**Comment by bmccorm2** [comment]
Sorry for being dense is there a resolution for this?  I am getting the same errors as above and have downgraded my graphql package to 15.3.0.

![image](https://user-images.githubusercontent.com/11781610/154388973-2b6738d3-60a2-42ad-97bd-9920332b8d58.png)

```
  "dependencies": {
    "class-validator": "^0.13.2",
    "fastify": "^3.27.1",
    "mercurius": "^9.3.2",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^1.1.1",
    "graphql": "^15.3.0",
    "typeorm": "^0.2.42"
  },
```

```
venv) ➜  test ts-node src/index.ts
/home/bryan/.config/yarn/global/node_modules/ts-node/src/index.ts:828
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:11:5 - error TS2322: Type 'GraphQLSchema' is not assignable to type 'string | string[] | GraphQLSchema | undefined'.
  Type 'GraphQLSchema' is missing the following properties from type 'GraphQLSchema': __validationErrors, _queryType, _mutationType, _subscriptionType, and 6 more.

11     schema: await buildSchema({
       ~~~~~~
src/index.ts:17:3 - error TS2769: No overload matches this call.
```

**Comment by smolinari** [comment]
@bmccorm2 - The issue is with TypeGraphQL. Not Mercurius. 

If you are looking for the TypeGraphQL experience, where it also works with v16 of GraphQL (and also gives you a modules/DI system which you have to add with TypeGraphQL), you could try NestJS' code-first approach. Nest now supports Mercurius out of the box. 

Scott

**Comment by bmccorm2** [comment]
Thanks @smolinari.  So if i understand correctly, the stack of fastify/mercurius/typegraphql is not compatible at this time correct?  I tried to get it to work on Nest to no avail and i also tried the vanilla example from the site below.  Same error as above - all with graphql 15.3.0.  

https://mercurius.dev/#/docs/integrations/type-graphql?id=integrating-typegraphql-with-mercurius

**Comment by smolinari** [comment]
@bmccorm2 - Mercurius and TypeGraphQL should work together with v15 of GraphQL. And, when you say "tried to get it to work with Nest" are you speaking of TypeGraphQL? If yes, you don't need it. Nest has it's own TypeGraphQL-like module. In fact, Nest used to use TypeGraphQL in the past, but went away from it, for reasons I don't know. But, their new GraphQL module is just as good as TypeGraphQL. 

Scott

**Comment by mcollina** [comment]
You will have to use v8 of Mercurius because that's the one that supports GraphQL v15. 

I'm not sure what is blocking the upgrade of TypeGraphql but it seems there is some activity there, so hopefully it will be resolved soon.

**Comment by bmccorm2** [comment]
@smolinari  - sorry i didn't know that nest had its own graphql module similar to typeGraphQL.  I'll give that a try.

@smolinari / @mcollina  - I copied the two files from the recipe below.  They won't run because of typing errors. V8 of mercurius and v15 of graphql.  Are you saying you are able to get those to run?
https://mercurius.dev/#/docs/integrations/type-graphql?id=integrating-typegraphql-with-mercurius
```
{
  "dependencies": {
    "apollo-server-core": "^3.6.3",
    "apollo-server-fastify": "^3.6.3",
    "fastify": "^3.27.2",
    "graphql": "15.3.0",
    "mercurius": "8.12.0",
    "reflect-metadata": "^0.1.13",
    "type-graphql": "^1.1.1",
    "typeorm": "^0.2.43"
  },
  "devDependencies": {
    "@types/node": "^17.0.18",
    "nodemon": "^2.0.15",
    "sqlite3": "^5.0.2",
    "typescript": "^4.5.5"
  },
  "scripts": {
    "dev": "nodemon --exec ts-node src/mercurius.ts"
  }
}
```
```
venv) ➜  test ts-node src/index.ts
/home/bryan/.config/yarn/global/node_modules/ts-node/src/index.ts:828
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:11:5 - error TS2322: Type 'GraphQLSchema' is not assignable to type 'string | string[] | GraphQLSchema | undefined'.
  Type 'GraphQLSchema' is missing the following properties from type 'GraphQLSchema': __validationErrors, _queryType, _mutationType, _subscriptionType, and 6 more.

11     schema: await buildSchema({
       ~~~~~~
src/index.ts:17:3 - error TS2769: No overload matches this call.
```
