### ISSUE TITLE
Question: logging the operation name

### ISSUE THREAD

**Issue by higgins** [mercurius-js/mercurius#694]
Hello, I'm hoping to log the parsed graphql operation name of every request our fastify server receives.
Using
```
  const app = fastify({
    logger: {
      serializers: {
        req (request) {
          ...
        }
      }
    },
  });
```
I see I have access to the `fastify` [Request object](https://www.fastify.io/docs/latest/Reference/Request/) but it doesn't look like that stores the parsed graphql operation name.

**Question:** Will mercurius decorate the fastify Request object with the graphql operation name and if so, where is it stored?

Thank you!

**Comment by mcollina** [comment]
We don't store the operation name. Adding it is going to break https://mercurius.dev/#/docs/batched-queries where there are mulitple queries in the same HTTP request.

Why would you need to log the operation name?

**Comment by higgins** [comment]
> We don't store the operation name. Adding it is going to break https://mercurius.dev/#/docs/batched-queries where there are mulitple queries in the same HTTP request.

I see, no worries! We'll decorate our resolvers with a debug logger



> Why would you need to log the operation name?

We aren't batching (yet) and for the time being it's helpful to have the operation name logged with the http request logger we setup on fastify init. We should get the same effect with the resolver decorator though. 

thank you!
