### ISSUE TITLE
ErrorWithProps custom status code always return 200

### ISSUE THREAD

**Issue by sooxt98** [mercurius-js/mercurius#696]
the last sentence got mention this issue, but how to not return null? even if everything is empty the data stills return null
https://github.com/mercurius-js/mercurius/blob/master/docs/api/options.md

```js
// This doesnt work, Property 'data' does not exist on type 'ErrorWithProps'.ts(2339)
const error = new mercurius.ErrorWithProps('Invalid User ID', {moreErrorInfo}, 500)
error.data = {foo: 'bar'} 
throw error
```

and there's no way to get ErrorWithProps statusCode in mercurius errorFormatter

![image](https://user-images.githubusercontent.com/13378059/147898999-d81aee55-f0a7-4ca9-8a18-b78a60f6d3a2.png)

index.js
```js
'use strict'

const Fastify = require('fastify')
const mercurius = require('mercurius')
const { JSONObjectResolver, JSONObject } = require('graphql-scalars');

const app = Fastify()

const schema = `
  scalar JSONObject
  type Query {
    show(input: JsonInput): JSONObject
  }
  input JsonInput {
      json: JSONObject
  }
`

const resolvers = {
    JSONObject: JSONObjectResolver,
    Query: {
        show: async (_, { input }) => {
            throw new mercurius.ErrorWithProps('Invalid User ID', {}, 500)
            return input.json
        }
    }
}

app.register(mercurius, {
    schema,
    resolvers
})

app.get('/', async function (req, reply) {
    const query = '{ show(json: {test: true}) }'
    return reply.graphql(query)
})

app.listen(5000)
```

package.json
```
{
  "name": "mercurius-json-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fastify": "^3.25.0",
    "graphql": "^15.8.0",
    "graphql-scalars": "^1.14.1",
    "mercurius": "^8.12.0"
  }
}

```

**Comment by sameer-coder** [comment]
> the last sentence got mention this issue, but how to not return null? even if everything is empty the data stills return null

I think this is as per the graphql spec (https://spec.graphql.org/June2018/#sec-Data)
`If an error was encountered during the execution that prevented a valid response, the data entry in the response should be null.`

Also, as mentioned in the mercurius docs, if you specify a `data` property on the error then the `statusCode` will always be 200

However, if you still want to get rid of the `data` property or change the status code before sending the response you can use a custom errorFormatter and do something like
```js
errorFormatter: (result, context) => {
      delete result.data
      return { statusCode: 500, response: result }
    }
```

**Comment by gilach** [comment]
You can access the statusCode from the exception via `originalError` property:
```javascript
app.register(mercurius, {
    schema,
    resolvers,
    errorFormatter: (result) => ({ statusCode: result.errors[0].originalError.statusCode, response: result })
})
```
