### ISSUE TITLE
MercuriusGatewayService keepAlive property not available

### ISSUE THREAD

**Issue by grillmeistertodafleisch** [mercurius-js/mercurius#698]
According to the documentation the gateway services should expose a `service.keepAlive` property. However the `MercuriusGatewayService` interface does not provide this property.

Is there any way to enable keepalive messages from the gateway to the services?

Thanks in advance for your help.

**Comment by mcollina** [comment]
I think we forgot to add it to the types. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by grillmeistertodafleisch** [comment]
Sure, I can try to fix that

**Comment by grillmeistertodafleisch** [comment]
@mcollina sorry, for the delay, just opened the PR
