### ISSUE TITLE
Apollo Subgraph Compatibility Verification 

### ISSUE THREAD

**Issue by destumme** [mercurius-js/mercurius#718]
Has anyone looked at getting mercurius added to Apollo's list of verified libraries for creating federation compatible subgraphs? 

https://github.com/apollographql/apollo-federation-subgraph-compatibility
https://www.apollographql.com/docs/federation/other-servers/

I'd be happy to take a swing at it, as well as open the corresponding issue in their testing repo, but if there is work that has already been done here, or there are already some known limitations that are a blocker on having mercurius added to that list (or maybe some other reasons it hasn't been done).

**Comment by mcollina** [comment]
Go for it! I don't think any work has been done.

**Comment by destumme** [comment]
For visibility: https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/69

The only thing that failed out of the box, was apollo's federated trace header (https://www.apollographql.com/docs/federation/metrics/#how-tracing-data-is-exposed-from-a-subgraph). I started looking at it, but didn't get very far. I assume that is functionality that should be in it's own lib though, and not directly in mercurius.

**Comment by destumme** [comment]
They merged the PR for this, mercurius now shows in the readme of the testing repo, listing the features that are supported. This can probably be closed.
