### ISSUE TITLE
@requires directive not found in gateway list of directives

### ISSUE THREAD

**Issue by aleccool213** [mercurius-js/mercurius#729]
Hi! 

My team writes the gateway schema to disk for a number of reasons. We like seeing what our federated graph schema compiles to and its nice for communicating what the schema looks like to other teams (we dont use a schema registry).

We recently started to use the `@requires` directive in a service and the gateway doesn't list it in the directives available. Because of this, `@requires` does not get defined at the top of the schema file even though its being used in the schema. This breaks our linting and also doesn't follow the GraphQL schema spec closely.

Functionally `@requires` works as expected for the federated services.

## Steps to reproduce

1. Create a new node project on your computer.

1. [Copy and paste the example gateway code](https://github.com/mercurius-js/mercurius/blob/master/examples/gateway.js) from the repo into a index.js file.

1. Run the gateway and the two services (does this by default) by running `node index.js`.

1. Query the gateway for directives

1. See that no requires directive will exist

1. Query service 2 for directives

1. See that the `@requires` directive exists

Here is the query you can run to get directives.
```graphql
query IntrospectionQuery {
  __schema {
    directives {
      name
      description
      locations
    }
  }
}
```

**Comment by mcollina** [comment]
Good spot! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by aleccool213** [comment]
The reason this happens is that the gateway-specific directives are filtered out of the final list of directives here: https://github.com/mercurius-js/mercurius/blob/ea2e50df36284bab5cae1894e103a851f303234e/lib/federation.js#L240

This is because they aren't used in the final gateway schema, except the `requires` is used in both locations. I propose we do not filter out the `requires` directive when building the gateway schema.
