### ISSUE TITLE
Gateway query fails if a type is redefined

### ISSUE THREAD

**Issue by codeflyer** [mercurius-js/mercurius#731]
Hi,
I'm facing this issue using the gateway feature: 

I've 2 nodes that declare the same type, it's a wrapper to normalise the return list:

```graphql
    type PageInfo {
      edges: [User]
    }
```

The first node declare and resolve the `User` type

```graphql
  extend type Query {
      me: User
    }

    type PageInfo {
      edges: [User]
    }

    type User @key(fields: "id") {
      id: ID!
      name: String
      username: String
    }
```

The second one has a query that return the list of the users:

```graphql
    extend type Query {
      meWrap: PageInfo
      meWrapDifferentName: PageInfoRenamed
    }

    type PageInfoRenamed {
      edges: [User]
    }
    
    type PageInfo {
      edges: [User]
    }
    
    type User @key(fields: "id") @extends {
      id: ID! @external
    }
```

The query that uses the type with a diffrent name, works properly as expected:

```graphql
   {
        meWrapDifferentName { edges { name }  }
   }
```

Instead the query that used the type that's declared in the other node as well fails:

```graphql
   {
        meWrap { edges { name }  }
   }
```

with the error:
```
Cannot query field \"edges\" on type \"Query\".
```

A test file that replicate the issue is available here:

https://github.com/mercurius-js/mercurius/pull/730

**Comment by mcollina** [comment]
Can you please make a reproducible example? 

I don't understand why you are redefining the type.

**Comment by mcollina** [comment]
Why are you not using the @external directive on `edges`?

**Comment by codeflyer** [comment]
I-ve created a test in the PR in the comment, this the direct link to the file: 
https://github.com/mercurius-js/mercurius/blob/c03f25657400323a93f0744ad13617db51f30300/test/gateway/type-redefined.js
