### ISSUE TITLE
Add logs for queries and mutations

### ISSUE THREAD

**Issue by paolochiodi** [mercurius-js/mercurius#732]
When a fastify + mercurius application receives a request with a query or a mutation, only the original fastify http request is logged. 
Unfortunately this is not very useful as everything will be logged as a `POST /graphql`.

It would be great if mercurius could instead:
- log the name of the mutation or query
- extend the logger passed to the resolvers to include informations about the query or mutation
- (optional) suppress default fastify logs

I guess what I'm saying is that it would be great to have some mercurius logging that works the way fastify logging works.

I understand this is feature request that will need some thinking / designing. Let me know if I can help.

**Comment by mcollina** [comment]
I think this should be implemented logging the query source right before https://github.com/mercurius-js/mercurius/blob/5760b066339241c51b6da80c9098032673fc08d7/index.js#L511 as a new logging value at a debug level.

**Comment by paolochiodi** [comment]
But what should be logged? I.e. I send multiple named queries like

```
query Query1 {
  currentUser {
    id
  }
}

query Query2 {
  categories {
    id
    name
  }
}
```

Will both queries be logged separately? Will it log the query name or the actual query?

**Comment by mcollina** [comment]
If you check in the actual code, it's just the source that is sent by the user before parsing it.

**Comment by Eomm** [comment]
I have created a plugin for this issue:
https://github.com/Eomm/mercurius-logging

**Comment by mcollina** [comment]
Could you add a link in the docs?
