### ISSUE TITLE
Schema and resolver errors

### ISSUE THREAD

**Issue by subhero24** [mercurius-js/mercurius#737]
When loading Mercurius with a schema option as a string, and the schema contains syntax errors or there are resolvers that do not match the schema, the server just quits without any error message whatsoever. This makes debugging really hard. Is it possible to throw relevant errors when schema and/or resolvers contain errors?

**Comment by mcollina** [comment]
Can you include an example? It does error so maybe you are not handling/logging them?

**Comment by subhero24** [comment]
I used the first example from the docs:

```javascript
'use strict'

const Fastify = require('fastify')
const mercurius = require('mercurius')

const app = Fastify()

const schema = `
  type Query {
    add(x: Int, y: Int): Int
  }
`

const resolvers = {
  Query: {
    add: async (_, { x, y }) => x + y
  }
}

app.register(mercurius, {
  schema,
  resolvers
})

app.get('/', async function (req, reply) {
  const query = '{ add(x: 2, y: 2) }'
  return reply.graphql(query)
})

app.listen(3000)

```

**Comment by mcollina** [comment]
Where is the error?

**Comment by subhero24** [comment]
This example from the docs runs fine. When I change anything about the resolvers or schema that should result in an error, the program just quits.

If for example the schema has an additional method that is not there in the resolvers. 

```javascript
'use strict'

const Fastify = require('fastify')
const mercurius = require('mercurius')

const app = Fastify()

const schema = `
  type Query {
    add(x: Int, y: Int): Int
    subtract(x: Int, y: Int): Int
  }
`

const resolvers = {
  Query: {
    add: async (_, { x, y }) => x + y
  }
}

app.register(mercurius, {
  schema,
  resolvers
})

app.get('/', async function (req, reply) {
  const query = '{ add(x: 2, y: 2) }'
  return reply.graphql(query)
})

app.listen(3000)
```

**Comment by subhero24** [comment]
I understand that it is allowed in graphQl, but the fastify server just shuts down immediately.

**Comment by mcollina** [comment]
the above example you pasted works fine here.

**Comment by subhero24** [comment]
I upgraded my node version, and now it works fine 🤔 . Thanks for looking into it.
