### ISSUE TITLE
Latest NPM version points to v8.12.2 instead of 9.3.6

### ISSUE THREAD

**Issue by wodCZ** [mercurius-js/mercurius#760]
During a regular package update (`yarn upgrade-interactive --latest`), mercurius was offered to "upgrade" from 9.3.5 to 8.12.2.

![CleanShot 2022-03-25 at 16 33 16](https://user-images.githubusercontent.com/1174421/160152103-635d1126-2cf0-4ada-8374-4360fc545c95.png)

The 9.3.6 version seems to be [available at NPM](https://www.npmjs.com/package/mercurius), but the `latest` version points to the 8.12.2.
![CleanShot 2022-03-25 at 16 30 50](https://user-images.githubusercontent.com/1174421/160151873-65350a77-d38b-47ec-921a-f87a720c4fc9.png)

**Comment by mcollina** [comment]
Good spot, I'll fix it asap.

**Comment by mcollina** [comment]
This is fixed.
