### ISSUE TITLE
Node __resolveType is not acceptable by typescript types

### ISSUE THREAD

**Issue by ZiiMakc** [mercurius-js/mercurius#761]
While working on ["Global Object Identification"](https://graphql.org/learn/global-object-identification/) I stumbled on issue where `__resolveType` on `Node` is not accepted by typescript types but works fine:
```
  Node: {
    __resolveType: () => "User",
  }
```

while `resolveType` without `__` is accepted by ts but doesn't work:
```
  Node: {
   resolveType: () =>  "User",
  }
```
Without `__resolveType` you will get an error:
>"Abstract type \"Node\" must resolve to an Object type at runtime for field \"Query.node\". Either the \"Node\" type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",

Reproduction example:
```
import Fastify from "fastify";
import mercurius from "mercurius";
import mercuriusCodegen, { gql } from "mercurius-codegen";
import { makeExecutableSchema } from "@graphql-tools/schema";
import { Resolvers } from "./generated";

const app = Fastify();

app.setErrorHandler(async (err, req, res) => {
  console.error(err);

  await res.status(500).send({ msg: "Server error" });
});

const types = gql`
  type Query {
    user: User!
    node(id: ID!): Node!
  }

  type User implements Node {
    id: ID!
    name: String!
  }

  interface Node {
    id: ID!
  }
`;

const user = { id: "1", name: "x" };

const resolvers: Resolvers = {
  // Works, but typescript is not happy
  Node: {
    __resolveType: () => {
      return "User";
    },
  } as any,
  // Doesnt' work, but ts is happy
  // Node: {
  //  resolveType: () => {
  //     return "User";
  //   },
  // } as any,
  Query: {
    user: () => user,
    node: () => user,
  },
};

const schema = makeExecutableSchema({ typeDefs: types, resolvers });

app.register(mercurius, {
  schema,
  graphiql: true,
});

app.listen(3000);

mercuriusCodegen(app, {
  targetPath: "./generated.ts",
}).catch(console.error);

```

**Comment by mcollina** [comment]
Can you try without mercurius-codegen? I have a feeling it must be the problem.

**Comment by ZiiMakc** [comment]
@mcollina Seems that setting `internalResolversPrefix: true` in [configuration](https://www.graphql-code-generator.com/plugins/typescript-resolvers) resolves an issue. 

> type: string default: '__'
Defines the prefix value used for __resolveType and __isTypeOf resolvers. If you are using mercurius-js, please set this field to empty string for better compatibility.

**Comment by ZiiMakc** [comment]
Without `__` and `mercurius-codegen` I get error 
> "message": "Node.resolveType defined in resolvers, but not in schema",

**Comment by ZiiMakc** [comment]
It also works with and without `__` if I pass resolvers directly to plugin:
```
 await app.register(mercurius, {
    schema,
    resolvers,
  });
```

instead of `makeExecutableSchema`:
```
 const schema = makeExecutableSchema({ resolvers,... })
 await app.register(mercurius, {
    schema,
  });
```

**Comment by mcollina** [comment]
There is likely something odd in meecurius that is preventing this.  
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ZiiMakc** [comment]
I think issue is that `makeExecutableSchema` doesn't allow `resolveType` without underscores and throws an error, related issue: https://github.com/mercurius-js/mercurius-typescript/issues/14

I'm not very familiar with graphql and not sure what is the proper solution (overriding `internalResolversPrefix` works for me):
1) Not override `internalResolversPrefix` in `[mercurius-typescript](https://github.com/mercurius-js/mercurius-typescript)` and use `__resolveType` for compatibility with `makeExecutableSchema` . 
2) Add note to the docs that you should not pass resolvers to `makeExecutableSchema` and should pass them to plugin.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ZiiMakc** [comment]
Sorry for delay, no, I'm not sure what is a proper solution, anyway solutions for `makeExecutableSchema` usage is added above for anyone who will stumble on this issue.
