### ISSUE TITLE
Forward custom context to GraphQL service when using Federation 

### ISSUE THREAD

**Issue by all2pie** [mercurius-js/mercurius#762]
I am using Mercurius Federation with Nestjs as a Gateway and I want to set user session in the context that should be accessible form the GraphQL service. 

I have tried custom context but it dose not work with federation.

**Comment by mcollina** [comment]
The context cannot be forwarded as-is, it's part of the gateway system. However you can do forward headers with the `rewriteHeaders` option of the gateway. Note that this is mostly a problem of Nest.js in sending this information down, not the reverse.

**Comment by all2pie** [comment]
@mcollina 
Thanks for the suggestion I tried the rewriteHeaders before but it doesn't accept Json so I will stringify it.

And can you please share the details details regarding the Nestjs information sending so I can open an issue there

**Comment by mcollina** [comment]
I have absolutely no clue. I'm not a Nest.js so you might just ask them. I think they use mercurius under the hood so there some kind of short-circuit here.

**Comment by all2pie** [comment]
Okay thanks
