### ISSUE TITLE
onResolution hooks not called on bad request

### ISSUE THREAD

**Issue by tuan231195** [mercurius-js/mercurius#764]
I am trying to use type-graphql and type-di with Mercurius. Currently, I am creating a new typeDI container inside the context function:

```
context: ({ request, reply }) => {
	const requestId = uuidv4();
	const traceId =
		(traceIdHeader
			? request?.headers?.[traceIdHeader]
			: undefined) ?? uuidv4();

	return {
		container: createContainer(logger, requestId, traceId),
		req: request,
		res: reply,
		requestId,
		traceId,
		__cache: {
			dataLoaders: new Map(),
		},
		...contextOptions,
	};
},
```

I have added an onResolution hook to handle clean-up of the container instance. However, it will never be called if the Graphql request fails validation.
```
app.graphql.addHook('onResolution', async (execution, context: any) => {
		Container.reset(context.requestId);
		// eslint-disable-next-line no-param-reassign
		context.__cache = {};

		if (execution.errors) {
			const requestLogger = context.container.get('logger');
			requestLogger.error(
				`Graphql execution failed with errors: \n ${formatError(
					execution.errors as any
				)}`
			);
		}
	});

```
It results in memory leaks. Also, I will not be able to log the validation errors.

Is it possible to call onResolution for the graphql validation errors too? It should behave similarly to didEncounterErrors in apollo-server

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by sameer-coder** [comment]
Maybe you could try using the `errorFormatted` callback to clean up the container instance. Something like:

```js
  app.register(mercurius, {
    schema,
    resolvers,
    context: ({ request, reply }) => {
      return {
        container: createContainer(logger, requestId, traceId),
      }
    },
    errorFormatter: (result) => {
      // cleanup container instance
      return { statusCode: result.errors[0].originalError.statusCode || 200, response: result }
    }
  })
```

@tuan231195 Let me know if that doesn't work for you.

@jonnydgreen do you think we should have a separate hook to allow handling validation errors?

**Comment by mcollina** [comment]
What `didEncounterErrors` add vs what we already have?

**Comment by sameer-coder** [comment]
As per my understanding, I think `didEncounterErrors` hook captures errors occurred while parsing or validating a GraphQL operation. In mercurius, we those errors are captured in the `errorFormatter` instead of a separate hook.

**Comment by mcollina** [comment]
I don't understand how that would be different from what we have, apart from naming.

**Comment by sameer-coder** [comment]
Yes, I agree. It would only be a naming change and we already have the functionality. I guess the OP can just use the `errorFormatter`
