### ISSUE TITLE
Add Async support in rewriteHeaders

### ISSUE THREAD

**Issue by all2pie** [mercurius-js/mercurius#767]
Please add async (promise) support in `rewriteHeaders`

Use Case: 

It is related to this [issue](https://github.com/mercurius-js/mercurius/issues/762) 

I want to get session in `rewriteHeaders`  function which is Asynchronous, Because the context setting is not possible as per [this](https://github.com/nestjs/graphql/issues/2114)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by all2pie** [comment]
https://github.com/mercurius-js/mercurius/pull/773
