### ISSUE TITLE
`graphql` is both a dependency and a peerDependency

### ISSUE THREAD

**Issue by markrzen** [mercurius-js/mercurius#768]
It looks like someone moved GraphQL to a peerDependency, then someone else re-added GraphQL as a dependency without changing it's peerDependency configuration:

https://github.com/mercurius-js/mercurius/commit/675769acf79a926f0bfdf6cc8e0abd7621798fb7

https://github.com/mercurius-js/mercurius/blob/master/package.json#L62

**Comment by mcollina** [comment]
Unfortunately that's the only way to handle the pletora of different implementations of package managers :(.

**Comment by markrzen** [comment]
@mcollina Any chance you have some docs surrounding that? Or just a bit of tribal knowledge?

**Comment by mcollina** [comment]
npm v6 does not install peerDependencies by default.
npm v8 does install peerDependencies.

Yarn handles it even differently. We target npm v6 environment still.
