### ISSUE TITLE
Subscription Support in Federation

### ISSUE THREAD

**Issue by all2pie** [mercurius-js/mercurius#776]
Please add subscription support for Federation

**Comment by mcollina** [comment]
This is supported already.

**Comment by all2pie** [comment]
Please add it in docs as well.

And I set the `subscription: true` in both gateway and service but not able to test in Apollo Studio or any other client, which url should I use for subscription? 

The subscription works correctly when checking from service directly through grapihiql but it dose not with Federation Gateway  using Apollo Studio 

 
![image](https://user-images.githubusercontent.com/34629684/165061366-1eb7bd43-4ebd-41ac-8cfb-de57b97d15dd.png)
