### ISSUE TITLE
Throwing ErrorWithProps with required resolver result type.

### ISSUE THREAD

**Issue by didiermicoud** [mercurius-js/mercurius#779]
Ciao Matteo
I have resolvers that are throwing ErrorWithProps on failures.
Looking closer, I see some unexpected behavior.
When more than one resolver are throwing an error, the expectations would be to return all the errors in the response. But it does not seem to be the case.

I have this:

```
'use strict'

const Fastify = require('fastify')
const mercurius = require('mercurius')
const { ErrorWithProps } = require('mercurius');

const app = Fastify()

const throwErrorWithProps = (code) => {
  throw new ErrorWithProps(
    'resolver error',
    {
      foo: 'bar',
      code
    },
    code
  );
}

const schema = `
  type Query {
    resolverReturnOptional(code: Int!): String
    resolverReturnRequired(code: Int!): String!
  }
`

const resolvers = {
  Query: {
    resolverReturnOptional: (_, { code }) => throwErrorWithProps(code),
    resolverReturnRequired: (_, { code }) => throwErrorWithProps(code)
  }
}

app.register(mercurius, {
  schema,
  resolvers
})

app.listen(3000)
```

-> A resolver that returns an optional result, throwing an error
-> A resolver that returns a required result, throwing an error

When querying:
```
query {
  ok: resolverReturnOptional(code: 200)
  err1: resolverReturnOptional(code: 418)
  err2: resolverReturnOptional(code: 500)
}
```
The response is a 200 with ok data and 2 errors, each with the expected extensions. As expected

When querying:
```
query {
  ok: resolverReturnRequired(code: 200)
  err1: resolverReturnRequired(code: 418)
  err2: resolverReturnRequired(code: 500)
}
```
The response has the status code of the first resolver failure. I would have expected a 200 with both errors - and also the successfull resolver execution data. It seems like the response validation fails the request maybe too early.

**Comment by didiermicoud** [comment]
Note that - with type resolvers, the behavior is as expected:
With something like: 
```
const schema = `
  type Entity {
    optionalFieldThrows(code: Int!): String
    requiredFieldThrows(code: Int!): String!
  }

  type Query {
    entity: Entity
    resolverReturnOptional(code: Int!): String
    resolverReturnRequired(code: Int!): String!
  }
`

const resolvers = {
  Query: {
    entity: () => { return { foo: 'bar' } },
    resolverReturnOptional: (_, { code }) => throwErrorWithProps(code),
    resolverReturnRequired: (_, { code }) => throwErrorWithProps(code)
  },
  Entity: {
    optionalFieldThrows: (_, { code }) => throwErrorWithProps(code),
    requiredFieldThrows: (_, { code }) => throwErrorWithProps(code)
  }
}
```

The response for :
```
query {
	entity {
		optionalFieldThrows(code: 418)
		requiredFieldThrows(code: 500)
	}
}
```
Does return a 200 with 2 errors.

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

---

It would be a while before I can tackle this bug. Would you like to send a PR?

**Comment by didiermicoud** [comment]
Ecco ci qua - 
I put this quickly together - 
https://github.com/didiermicoud/mercurius-stash

I will look a little deeper to understand how errors are handled when a request contains more than one root query.

**Comment by mcollina** [comment]
What would be the fix to this issue? Would you like to send a PR?

**Comment by didiermicoud** [comment]
I have not been able to look closer - also I am not 100% sure what is the spec for handling multiple queries in a single request / with one failing - 
Let's close this for now - while I look more into it -
