### ISSUE TITLE
errorHandler method is not called

### ISSUE THREAD

**Issue by lucasGras** [mercurius-js/mercurius#786]
## Global issue description

I'm trying to create a custom error handler and formater for mercurius to match my custom error types. For this I would need
to overwrite errorFormatter and errorHandler implementation. 

I have no problem with errorFormatter, it works well and it's being called on every raised errors. But the errorHandler method does not seem to be called.

## Expected Behavior

What I expect is the errorHandler to be called, so I can handle custom error coming from my resolvers.

## Current Behavior

Here is my code sample:

```typescript
  const schema = `
  type Query {
      badRequestTest: String!
  }
  `;
  
  const resolvers = {
      Query: {
          badRequestTest: () => {
              throw BadRequest({
                  status: 400,
                  issue: 'This is the issue',
              });
              return "won't be called anyway"
          }
      }
  };

  await app.register(mercurius, {
      schema,
      resolvers,
      // Only required to use .batchQueries()
      allowBatchedQueries: true,
      errorHandler: (error, request, reply) => {
          console.log(error); // This log never appears
          reply.send({
              errors: [], // I still receive errors in errorFormatter
              data: {}
          });
      },
      errorFormatter: (execution) => {
          console.log(execution);
          return {
              statusCode: 200,
              response: execution,
          }
      },
  });
```

This code is wrapped in jest tests, the expected behaviour is to at least see the  errorHandler logs, and receive empty errors array in the errorFormatter method. But I see no logs, no trace of errorHandler execution, I can 't figure out why.

## Steps to Reproduce

Here are the steps to reproduce this, from the public repository I'm working on:
1. git clone https://github.com/flexper/unify-mercurius
2. pnpm install
3. pnpm test
4. We still receives errors, and errorHandler shows no logs

## Context (Environment)

- the ts.config is available in the repository: [https://github.com/flexper/unify-mercurius/blob/main/tsconfig.json](ts.config)
- node version v14.17.0
- mercurius v^9.3.6

**Comment by mcollina** [comment]
errorHandler is Fastify error handler, so it won't be called with `server.query()` as in your example.

**Comment by lucasGras** [comment]
I tried to use the fastify errorHandler as you mentioned @mcollina , see my example:
```
    app.setErrorHandler(
        //@ts-ignore
        (error, request, reply) => {
            console.log(error);
            reply.send({
                errors: [],
                data: {}
            });
        });
```

I think I still don't get any method overload, is there something I'm missing ?
How can I get fastify errorHandler to be called on mercurius errors ? (before being send to errorFormatter)

Thanks anyway !

**Comment by mcollina** [comment]
The Fastify error handler is called when a route handler rejects with an error. In your example you are not calling any Fastify route, but just doing `.query()`. Therefore, no error handler is triggered.

**Comment by qlaffont-flexper** [comment]
@mcollina as I see, @lucasGras wants to catch errors on query/resolver before they are converted to GraphQL Errors from Mercurius. We are trying to build an adapter for mercurius to Error Handling (https://github.com/flexper/unify-errors). How we can do that ?

**Comment by mcollina** [comment]
Please open a fresh issue
