### ISSUE TITLE
Mercurius 8 throws error about using `fastify-static` after upgrading to use `@fastify/static`

### ISSUE THREAD

**Issue by jessekrubin** [mercurius-js/mercurius#791]
I get the following warning:

```
(node:11324) [FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
```

I can send a PR for this fix if I have time soon.

**Comment by mcollina** [comment]
Go for it!

**Comment by jessekrubin** [comment]
Made the PR to the v8x branch

#792

**Comment by mmahkamov** [comment]
@jessekrubin @mcollina 

Using Mercurius 8.13.0 I'm seeing the following error message:
```
FastifyError [FST_ERR_PLUGIN_VERSION_MISMATCH]: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.3.0' is installed
```

I've verified that 8.13.0 is referencing @fastify/static in its package.json.

Verified that in node_modules @fastify/static 5.0.2 got installed. However, I see this in index.js of @fastify/static:
```
module.exports = fp(fastifyStatic, {
  fastify: '3.x',
  name: 'fastify-static'
})
```

Apparently, @fastify/static supports fastify 4.x starting from 6.0.0
