### ISSUE TITLE
Is there a way to receive query as AST?

### ISSUE THREAD

**Issue by joadr** [mercurius-js/mercurius#804]
Hello!

Before que used to have apollo-graphql-lambda which supports parsing Graphql AST directly. We've migrated to mercurius but some of our clients sends us graphql AST in the query payload. The thing is we had to create a fastify contentTypeParser to transform that AST back to string, but that is not something we want to keep because it doesn't make much sense as the string is converted back to AST by mercurius, so we are adding unnecessary overhead.

Is there a way of processing graphlq AST directly?

**Comment by simoneb** [comment]
Can you provide an example of what the query AST would look like?

**Comment by Ceres6** [comment]
Hi! I'm currently working on a way to provide this functionality

**Comment by smolinari** [comment]
A question that comes to my mind is, why would you want to do this at all? What would be the benefit? Disadvantages as I see them would larger request packets, going against one of the goals of GraphQL. Also troubleshooting AST instead of query text would be magnitudes harder. I'm not seeing what advantage this would offer that would beat those disadvantages. So, I'm wondering..... 

Scott

**Comment by simoneb** [comment]
Good point Scott, we can decide whether it makes sense to have this, I think @Ceres6 is only looking into the feasibility at the moment.

**Comment by Ceres6** [comment]
While doing the research I wasn't able to find an easy way to parse the string into an AST. Given the concerns raised about the feature probably not being wanted I think it won't be worth the effort implementing a solution for that

**Comment by simoneb** [comment]
Based on the outcome of the research done by @Ceres6, it looks like there isn't an easy way to support this. I'll close this issue then.

**Comment by simoneb** [comment]
Reopening, looks like @Ceres6 found a viable solution we'll propose and accept feedback about (thanks @matijagaspar!)
