### ISSUE TITLE
Disable GET requests

### ISSUE THREAD

**Issue by knpwrs** [mercurius-js/mercurius#810]
Is there a way to disable GET requests to `/graphql` or otherwise having some form of CSRF protection ([like Apollo](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#csrfprevention)) for GET requests?

**Comment by ZiiMakc** [comment]
You can use [fastify-helmet](https://github.com/fastify/fastify-helmet) I assume.

[Plugin options. Serves the Default: true. A graphql endpoint is exposed at /graphql.](https://mercurius.dev/#/docs/api/options?id=plugin-options)

**Comment by mcollina** [comment]
Check out https://github.com/fastify/csrf-protection

**Comment by acro5piano** [comment]
For someone who are looking for the exact solution:

```tsx
fastify.register(mercurius, {
  schema,
  context: async (req) => {
    if (req.method === 'GET') {
      throw new Error('You need to use POST to run GraphQL.')
    }
  },
})
```
