### ISSUE TITLE
Update mercurius-typescript

### ISSUE THREAD

**Issue by ZiiMakc** [mercurius-js/mercurius#811]
Can we update [mercurius-typescript](https://github.com/mercurius-js/mercurius-typescript/pull/285)?

**Comment by mcollina** [comment]
cc @PabloSzx

**Comment by PabloSzx** [comment]
working on it

**Comment by PabloSzx** [comment]
[mercurius-codegen@4.0.0](https://github.com/mercurius-js/mercurius-typescript/releases/tag/mercurius-codegen%404.0.0)
