### ISSUE TITLE
Fix @fastify/static version in v8.

### ISSUE THREAD

**Issue by mcollina** [mercurius-js/mercurius#832]
@jessekrubin @mcollina 

Using Mercurius 8.13.0 I'm seeing the following error message:
```
FastifyError [FST_ERR_PLUGIN_VERSION_MISMATCH]: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.3.0' is installed
```

I've verified that 8.13.0 is referencing @fastify/static in its package.json.

Verified that in node_modules @fastify/static 5.0.2 got installed. However, I see this in index.js of @fastify/static:
```
module.exports = fp(fastifyStatic, {
  fastify: '3.x',
  name: 'fastify-static'
})
```

Apparently, @fastify/static supports fastify 4.x starting from 6.0.0

__Originally posted by @mmahkamov in https://github.com/mercurius-js/mercurius/issues/791#issuecomment-1199825501__

**Comment by mcollina** [comment]
I'll fix it asap.

**Comment by jessekrubin** [comment]
@mcollina you will fix fastify static? or this pr fix?

**Comment by mcollina** [comment]
Unfortunately I can't reproduce it. @jessekrubin could you create a repository to reproduce the problem? All versions of modules used by mercurius are correct.

**Comment by jessekrubin** [comment]
@mcollina I made a repo but cannot repro; https://github.com/jessekrubin/fastify-mercurius-static-err-832

I think @mmahkamov has the problem tho so maybe they should repro it?

**Comment by jessekrubin** [comment]
mercurius `~8.13.0` working good for me and I too am using type-graphql with `"@fastify/static": "~5.0.0"`

**Comment by jessekrubin** [comment]
@mcollina gut says @mmahkamov is using wrong `@fastify/static`

**Comment by mmahkamov** [comment]
@mcollina I'll try to reproduce the issue on a new repo today

**Comment by mmahkamov** [comment]
@jessekrubin which version of fastify are you using?
I have @fastify/static 5.0.2 installed and it appears to support only fastify 3.x.

**Comment by mmahkamov** [comment]
@mcollina @jessekrubin Here's a sample repo to reproduce the issue:

https://github.com/mmahkamov/mercurius-issue-832

Please let me know if I can help with anything.

**Comment by mcollina** [comment]
You need to use Fastify v3 with Mercurius 8 or Fastify v4 with Mercurius 10.
