### ISSUE TITLE
Uniquely identify batched queries through all their lifecycle

### ISSUE THREAD

**Issue by drakhart** [mercurius-js/mercurius#842]
While trying to give support to https://github.com/nearform/mercurius-apollo-tracing/issues/125 we noticed that we were unable to uniquely identify each operation definition contained in batched queries through their whole lifecycle. This is needed in order to know which tracer to start or stop at any given time.

We tried two approaches and faced two different issues with them:

1. Using the `document` object contained in the hooks to extract the relevant operation information. This simply can't be done since the `onResolution` hook doesn't receive the `document` object, only the `execution` and `context` ones. See https://github.com/mercurius-js/mercurius/blob/master/docs/hooks.md#onresolution

Also, in the specific case of mercurius-apollo-tracing, it hooks into schema resolvers that don't provide all the `document` details (and they don't need to), just some `info` object. So it's best to go with the next approach...

2. Using the `context.__currentQuery` attribute. Turns out that this attribute is only updated during the `preParsing` stage and left untouched afterwards, so it's basically useless for batched queries during the rest of the lifecycle.

For reproducing this we can setup a basic Fastify + Mercurius server with `allowBatchedQueries: true` and a typical `add` query, and include these debugs on all hooks:
```
app.graphql.addHook('preParsing', async (_, __, context) => {
  app.log.info(`preParsing: ${context.__currentQuery}`)
})

app.graphql.addHook('preValidation', async (_, __, context) => {
  app.log.info(`preValidation: ${context.__currentQuery}`)
})

app.graphql.addHook('preExecution', async (_, __, context) => {
  app.log.info(`preExecution: ${context.__currentQuery}`)
})

app.graphql.addHook('onResolution', async (__, context) => {
  app.log.info(`onResolution: ${context.__currentQuery}`)
})
```

Then fire the following queries from a client that supports batched queries:
```
query { add(x: 1, y: 1) }
query { add(x: 2, y: 2) }
```

One would expect to have each hook print out the two queries, but as we can see only the `preParsing` hook does that while the rest of them print out the second query twice:
```
{"level":30,"time":1660745778776,"pid":74281,"hostname":"BBaidal-SPMAC21","reqId":"req-2","req":{"method":"POST","url":"/graphql","hostname":"localhost:3000","remoteAddress":"::1","remotePort":50784},"msg":"incoming request"}
{"level":30,"time":1660745778780,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preParsing: {\n  add(x: 1, y: 1)\n}"}
{"level":30,"time":1660745778781,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preParsing: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778781,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preValidation: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778782,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preValidation: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778786,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preExecution: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778787,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"preExecution: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778788,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"onResolution: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778788,"pid":74281,"hostname":"BBaidal-SPMAC21","msg":"onResolution: {\n  add(x: 2, y: 2)\n}"}
{"level":30,"time":1660745778789,"pid":74281,"hostname":"BBaidal-SPMAC21","reqId":"req-2","res":{"statusCode":200},"responseTime":12.858789920806885,"msg":"request completed"}
```

I'm sure that not only mercurius-apollo-tracing would benefit from having a way to uniquely identify batched queries through all their lifecycle, but also other potential plugins that could handle batched queries.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
