### ISSUE TITLE
Compatibility with `graphql-ws` `keepAlive`

### ISSUE THREAD

**Issue by andreialecu** [mercurius-js/mercurius#851]
I'm experimenting with switching from Apollo Express to Fastify and Mercurius.

I discovered something a bit weird. If I enable `keepAlive` in `graphql-ws`, it will send messages that look like `{"type": "ping"}` but it seems that something on the Mercurius side is not processing them correctly.

<img width="300" alt="Screenshot 2022-08-27 at 17 50 32" src="https://user-images.githubusercontent.com/697707/187035444-473f9634-fdc4-4376-b2cd-c332b751f4f8.png">

On the other hand, If I enable `keepAlive` in Mercurius, it sends messages like `{type: "ka"}`:
<img width="131" alt="Screenshot 2022-08-27 at 17 52 03" src="https://user-images.githubusercontent.com/697707/187035502-0d39e54a-0a4a-449d-aa03-666fcb7102f1.png">
 
`graphql-ws` completely crashes on these messages and breaks the subscription:
<img width="638" alt="Screenshot 2022-08-27 at 17 52 38" src="https://user-images.githubusercontent.com/697707/187035518-f65d114f-bb6c-48aa-9268-a038fa6dda93.png">
 
My understanding is that Mercurius uses `graphql-ws`, so what's the deal here? 🙂

**Comment by mcollina** [comment]
I think there is a bug somewhere in Mercurius that requires the payload in https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#ping to exist.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by andreialecu** [comment]
I'll take a look at submitting a PR for this. I believe this is also incorrect:

https://github.com/mercurius-js/mercurius/blob/f25d973208e6da61ab03cf6e99f35966f42b66f2/lib/subscription-protocol.js#L29

I don't think `graphql-ws` understands the `ka` message, based on the error in my original report.

**Comment by mcollina** [comment]
note that you should only change the `graphql-transport-ws` subprotocol.

**Comment by andreialecu** [comment]
Opened #852
