### ISSUE TITLE
GQL spec compliance for http status codes (200 everywhere)

### ISSUE THREAD

**Issue by andreialecu** [mercurius-js/mercurius#860]
I've been migrating from Apollo to Mercurius and noticed that queries that return GQL errors have status code 500. This trips up our client code, thinking it's a Network Error instead of an application error.

I took a look at the spec here:
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationjson

It seems to mention that:

> The server SHOULD NOT use a 4xx or 5xx status code.

> Note: For compatibility with legacy servers, this specification allows the use of 4xx or 5xx status codes for failed requests where the response uses the application/json media type, but it is strongly discouraged. To use 4xx and 5xx status codes, please use the application/graphql-response+json media type

This has already been discussed here: https://github.com/mercurius-js/mercurius/issues/599#issuecomment-940734753 

I implemented a custom errorFormatter to address this as mentioned in the documentation.

However, now that the spec recommends `200` everywhere, I think it might make sense to change it in the next Mercurius version accordingly.

**Comment by mcollina** [comment]
Sure thing. Would you like to send a PR?

**Comment by andreialecu** [comment]
> Sure thing. Would you like to send a PR?

Here you go: #861 🙂

**Comment by tamland** [comment]
mercurius still returns `400` for some errors e.g. attempting to query a field that doesn't exist or invalid query syntax. Not sure if this is intentional?

**Comment by mcollina** [comment]
@tamland could you send a PR to update it? No, it was not intentional.

**Comment by mcollina** [comment]
Then it's ok to return 400! Awesome.

**Comment by tamland** [comment]
I think 200 is correct for `application/json`. Clarified here: https://github.com/graphql/graphql-over-http/issues/203 Old issue but latest draft still say:
> The server SHOULD use the 200 status code, independent of any GraphQL request error or GraphQL field error raised.

**Comment by andreialecu** [comment]
Like I mentioned, I don't disagree. :)

I just explained what the reasoning was. If Matteo also agrees, you can send a PR to change it.

I left the 400 errors there because they're unlikely to occur during actual production usage. Invalid syntax and missing fields is usually a development time issue.
