### ISSUE TITLE
Federating with ruby-graphql

### ISSUE THREAD

**Issue by flovilmart** [mercurius-js/mercurius#862]
More a question than an issue. I am wondering what the DSL should be when integrating with an external server that isn't a mercurius federation / graphQL server, for example ruby-graphql.

I see that the server expects an [SDL](https://github.com/mercurius-js/mercurius/blob/master/lib/gateway/service-map.js#L76-L87) to be served, but how would I go about producing one?

Thanks!

**Comment by mcollina** [comment]
According to https://www.apollographql.com/docs/federation/supported-subgraphs/, graphql-ruby supports it.
