### ISSUE TITLE
Mercurius Federation throws error for Federation version 2 schema

### ISSUE THREAD

**Issue by sushilkjaiswar** [mercurius-js/mercurius#868]
Hi @mcollina ,

In brief I am using Mercurius + Fastify with @nestjs but this issue I found was more related to Mercurius library.  Can you validate my understanding and check it out if have fixed the issue appropriately or more needs to be to fix the issue.

Federation V2 schema is mentioned below 

users.graphql
```
extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0"
    import: ["@key", "@shareable"]
  )

type Query {
  getUser(id: ID!): User
}

type User @key(fields: "id") {
  id: ID!
  name: String! @shareable
}

```

posts.graphql

```
type Post {
  id: ID!
  title: String!
  body: String!
  user: User
}

type User @key(fields: "id") @extends {
  id: ID! @external
}

type Query {
  getPosts: [Post]
}

extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0"
    import: ["@key", "@external", "@provides", "@extends"]
  )
```

While testing federation app it threw following error 

```
/mercurius/lib/federation.js:99
    const typeName = definition.name.value
                                     ^
```

After investigating and my findings I found this error can be corrected by changing line 95 in mercurius/lib/federation.js

```
    if (definition.kind === 'SchemaDefinition' ) {
      continue
    } 
```

to 

```     
 if (definition.kind === 'SchemaDefinition' || definition.kind === 'SchemaExtension' ) {
      continue
    }
```

Can you comment on these observation and my fix and if there is an issue can we resolve in the main source?

**Comment by mcollina** [comment]
Mercurius does not support Federation 2.0.

**Comment by sushilkjaiswar** [comment]
Yes, I read the document and never found the mercurius is supporting federation version 2 and it is surprising that above schema worked after one change. Federation 1 never worked for me  with NestJs but without NestJS it worked without issues I have raised issue in the discord channel.  This is sample github code with instructions  https://github.com/sushilkjaiswar/Nestjs-Mercurius-Federation-Sample-Code. 

I will investigate more on Federation 1 with NestJs, By the way for your information below are the simple schema which is working,

users.graphql
```
 
type User @key(fields: "id") {
  id: ID!
  name: String!
}

extend type Query {
  getUser(id: ID!): User
}
```
posts.graphql
```
   type Post @key(fields: "id") {
  id: ID!
  title: String!
  body: String!
  user: User
}

extend type User @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}

extend type Query {
  getPosts: [Post]
}

``` 

Is there any plan to support federation version 2 in Mercurius with timeline proposed.

**Comment by mcollina** [comment]
According to https://www.bloomberg.com/press-releases/2021-11-03/apollo-graphql-introduces-federation-2-to-get-more-organizations-to-the-graph, Federation v2 is patent pending. I don't think we would implement it natively in Mercurius.

**Comment by sushilkjaiswar** [comment]
Okay. I think why it is working for in my Nestjs project is due to @apollo/subgraph dependency required in the nest project for federation even for Mercurius framework as well. This is my assumption because I don't think any other reason why it is working in my case.

Sad news Federation v2 won't make part of  Mercurius!

**Comment by smolinari** [comment]
This is the license stipulation that would kill the usage for me. 

> You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software.

This stipulation to me means Federation v2 is no longer open source. I understand a business has to make money, but what Apollo has done with their "work" has the stench of corporate greed all over it. 

Scott

**Comment by smolinari** [comment]
Hmmm... but reading further, it seems you can use Federation as part of a larger platform or service. Still, it is a bit vague in that respect. 

Scott

**Comment by sushilkjaiswar** [comment]
Since Apollo was in forefront driving the standards for Graphql Federation v1 and now federation v2(which is pending for patent). How you guys see the Mercurius and other similar libraries moving ahead in the direction of federation and what would be probable roadmap for federation feature for this library. Any thoughts?

**Comment by smolinari** [comment]
Although I'd highly doubt Mercurius' team/ makers would be taken to court over any breach of the Federation license or patent, it does pose big questions to those using Mercurius for services that offer federated GraphQL APIs. I'd say, the risk isn't with @mcollina, but then again, he might not want to be in the middle of anything, so probably why he said the comment above. https://github.com/mercurius-js/mercurius/issues/868#issuecomment-1251211831

Scott

**Comment by sushilkjaiswar** [comment]
I was more worried about the roadmap of Mercurius Federation given that Federation v2 will be patented. What next will be for federation in Mercurius or development will stop at version 1 features. This concern applies to all other graphql libraries as well with federation support.

**Comment by mcollina** [comment]
At this point, I have no answer for you.

Likely we'll spin out all Apollo Federation logic to a different module/plugin, and leave the development/support of Federation v2 to others.

I think it's inevitable that different kinds of composition logic will be developed given the anti-OSS stance of Apollo.

**Comment by sushilkjaiswar** [comment]
Thanks. Good to know the details. I was just evaluating @nestjs+mercurius federation for using in my new project and now I have to rethink about it. We can close this issue since I do not have any further queries in this regard.
