### ISSUE TITLE
GraphQL subscription does not work reliably unless listening on 0.0.0.0

### ISSUE THREAD

**Issue by andreialecu** [mercurius-js/mercurius#875]
I've been migrating a NestJS app from Apollo to Mercurius and found that the GraphQL WebSocket endpoint was not working. No connection could be established.

Upon some further inspection, I found that I needed to listen specifically on an explicit IP.

I was able to get things to work initially by specifying `127.0.0.1` as the bound IP address. However, once deployed via docker, this wouldn't work properly.

Instead, I need to specify `0.0.0.0` as mentioned in this comment: https://github.com/mercurius-js/mercurius/issues/838#issuecomment-1212655506

I wonder why this is necessary. Is it a bug? If not, I haven't seen it documented anywhere.

Related: 
https://github.com/mercurius-js/mercurius/issues/838
https://github.com/nestjs/nest/issues/9903#issuecomment-1229169259
https://github.com/nestjs/graphql/issues/2365

**Comment by mcollina** [comment]
It's documented here: https://www.fastify.io/docs/latest/Reference/Server/#listen.

Note that we do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

**Comment by andreialecu** [comment]
In particular, Chrome is not able to establish a connection when developing locally unless I either use `::` or `0.0.0.0` or `127.0.0.1`.

<img width="1103" alt="Screenshot 2022-09-27 at 13 32 16" src="https://user-images.githubusercontent.com/697707/192503185-2b8b0905-169a-45be-8ee7-cebfd980a322.png">

**Comment by mcollina** [comment]
Are you using the latest version of Fastify? This looks like te problem we fixed in https://github.com/fastify/fastify/pull/4190.

I'll be happy to look into this given a simple repro, ideally just with Fastify and Fastify-websockets

**Comment by mcollina** [comment]
This looks like some sort of DNS or networking issue on your machine. What does localhost resolves to?

**Comment by andreialecu** [comment]
```
➜ yarn why fastify             
├─ @nestjs/platform-fastify@npm:9.0.11
│  └─ fastify@npm:4.4.0 (via npm:4.4.0)
│
├─ @nestjs/platform-fastify@npm:9.0.11 [fc2e5]
│  └─ fastify@npm:4.4.0 (via npm:4.4.0)
│
└─ ...actual-project...
   └─ fastify@npm:4.5.3 (via npm:^4.5.3)
```

Oh, thank you. Indeed the version of `@nestjs/platform-fastify` I was using had a previous version of fastify pinned.

```
➜ yarn why fastify                
├─ @nestjs/platform-fastify@npm:9.1.2
│  └─ fastify@npm:4.6.0 (via npm:4.6.0)
│
├─ @nestjs/platform-fastify@npm:9.1.2 [fc2e5]
│  └─ fastify@npm:4.6.0 (via npm:4.6.0)
│
└─ ...actual-project...
   └─ fastify@npm:4.6.0 (via npm:^4.5.3)
```

After bumping everything, it's all good. Sorry for taking your time, and thanks for pointing me in the right direction!
