### ISSUE TITLE
No way to operate with variables in hooks

### ISSUE THREAD

**Issue by npdev453** [mercurius-js/mercurius#876]

**Comment by mcollina** [comment]
Can you make an example?

**Comment by npdev453** [comment]
Also Variables is very closes, and strange for me that it no passed inside hook:
https://github.com/mercurius-js/mercurius/blob/f6b6b858c24bc4bc919b25e9ac5cbf35df568d5d/index.js#L635

And slso no way to return it modified as Document do

(in apollo requestContext  (requestDidStart) its possible)

**Comment by matijagaspar** [comment]
So if I understand you correctly @npdev453, you are saying variables should be returned separately ie: `app.graphql.addHook('preExecution', (schema, document, context, variables) => {` 
and possibly be able to return them modified:

```
app.graphql.addHook('preExecution', (schema, document, context, variables) => {

  return {
    modifiedVariables:  doSomethingWithVariables(variables)
  }
}
```

is that correct @npdev453 ?

Since variables are already included in the context via `context.req` would having a correctly typed context be enough?

**Comment by npdev453** [comment]
> So if I understand you correctly @npdev453, you are saying variables should be returned separately ie: `app.graphql.addHook('preExecution', (schema, document, context, variables) => {` and possibly be able to return them modified:
> 
> ```
> app.graphql.addHook('preExecution', (schema, document, context, variables) => {
> 
>   return {
>     modifiedVariables:  doSomethingWithVariables(variables)
>   }
> }
> ```
> 
> is that correct @npdev453 ?
> 
> Since variables are already included in the context via `context.req` would having a correctly typed context be enough?

I think that it should  be chosen by library designer (an author @mcollina  or any active maintainer)

But in my option:
 1) using variables from context req is not stable solution and users code can be broken after some updates
 2) ability of accessing and modifying variables should be available because hook name is `preExecution` and `variables` is part of execution (also it can be safely logged in this place with Pino and redact function)
 3) context and context.req - should be typed as well, as you can absolutely know that it can be only passed from `fastify`

**Comment by mcollina** [comment]
I'm kind of lost in all of this. By the look of https://github.com/mercurius-js/mercurius/issues/876#issuecomment-1259506419, this seemed an issue about lack of types and or docs.

```js
        app.graphql.addHook('preExecution', (schema, document, context) => {
                 console.log('variables', context.req.body.variables)
                 console.log('ops', readOpsNames(document)) // filtering for OperationDefinition selectionSet names
        });
```

This is the proper way to access the request body. There does not seem to be a need for anything more than this.

**Comment by simoneb** [comment]
@npdev453 is this issue sorted for you? Can you close it?

**Comment by npdev453** [comment]
> @npdev453 is this issue sorted for you? Can you close it?

Yeah, thank! Strange that gitlab dont close it automatically
