### ISSUE TITLE
Incorrect overload types of hooks

### ISSUE THREAD

**Issue by npdev453** [mercurius-js/mercurius#877]
That code:
```ts
 app.graphql.addHook('preExecution', (schema, document, context) => {});
```
make that error:

```ts
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"preExecution"' is not assignable to parameter of type '"onGatewayReplaceSchema"'.ts(2769)
index.d.ts(362, 3): The last overload is declared here.
```

**Comment by npdev453** [comment]
There are shoud be something like:
```addHook(name: any, hook: any): void;```
 on the end

**Comment by npdev453** [comment]
Ah, its because I call it without `async` keyword.
but is it really nessesacy? 


` app.graphql.addHook('preExecution',  async (schema, document, context) => {});`

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

It's ok to update the types to `()=>Promise<T> | T`.

**Comment by raulsoledispa** [comment]
@mcollina, I'd like to send a PR to address this issue. Can you assign it to me?

**Comment by mcollina** [comment]
go for it!
