### ISSUE TITLE
Allow internal graphiql to add custom plugin

### ISSUE THREAD

**Issue by codeflyer** [mercurius-js/mercurius#892]
The internal version of `graphiql` provided with `mercurius` loads the code from unpkg.com.

Allow to add `graphiql` plugin through the configuration of mercurius.

Eg.

```
{
      graphiql: {
        enabled: true,
        plugins: [
          {
            name: 'yourPlugin',
            props: {foo: 'bar'},
            umdUrl: 'https://unpkg.com/your-plugin@1.1.1/umd/yourplugin.production.min.js'
            fetcherWrapper: 'interceptResultFromFetch'
          }
        ]
      },
      schema,
      resolvers
    }
```

**Comment by arkmech** [comment]
Will type definitions be added for this? currently accepts boolean, "graphiql", and undefined

**Comment by codeflyer** [comment]
@arkmech 

I've just opened an issue. I'll take care of it the few days.
https://github.com/mercurius-js/mercurius/issues/903
