### ISSUE TITLE
How to create a dynamic GraphQL schema

### ISSUE THREAD

**Issue by VojislavVlasic** [mercurius-js/mercurius#894]
Hello!
We're creating a new GraphQL API and we're researching how to improve the performance of our previous API.
We have a scenario where each user can have his own types, I was wondering if there is some way to create and load those types, based on the request headers?
Thank you!

**Comment by mcollina** [comment]
This would be an interesting use case to work on... but Mercurius has no specific utility for you :(. A dynamic schema for each user is outside of the scope of this project.
