### ISSUE TITLE
Duplicated _entities in federation

### ISSUE THREAD

**Issue by ramiel** [mercurius-js/mercurius#897]
As in issue #643 should it be similar for `_entities`?

**Comment by mcollina** [comment]
I'm sorry but I don't understand what you are talking about. Can you clarify and make an example?

**Comment by ramiel** [comment]
Sorry for the poor description. I want to ask another question actually, that includes an answer to this issue as well. In the [documentation](https://mercurius.dev/#/docs/federation?id=use-graphql-server-as-a-gateway-for-federated-schemas) is written:

`A GraphQL server can act as a Gateway that composes the schemas of the underlying services into one federated schema and executes queries across the services. Every underlying service must be a GraphQL server that [supports the federation](https://www.apollographql.com/docs/federation/supported-subgraphs/).`

From the link it looks like mercurius does not support some critical feature. Is it possible to use mercurius as underlying service, in a federation?

**Comment by mcollina** [comment]
According to [announcement](https://www.businesswire.com/news/home/20211103005214/en/Apollo-GraphQL-Introduces-Federation-2-to-Get-More-Organizations-to-the-Graph) of Federation v2, it is patent pending.

While it would be ok for users to make a judgment call for themselves, I do not feel I should include them in the main package. As soon as we have Federation support separated in https://github.com/mercurius-js/federation-support/pull/1, anybody could fork that project to add those in.

**Comment by ramiel** [comment]
Ok, good to know. Since mercurius can act as gateway I thought it could be used as service as well. My fault. To be honest I can make the service work with mercurius as well, but it's a bit of an hack. I'll leave things unchanged or move to something else like graphql-yoga.

Thank you
