### ISSUE TITLE
Should the defaultErrorFormatter output info logs?

### ISSUE THREAD

**Issue by EDjur** [mercurius-js/mercurius#912]
Hi and thanks for the great project!

I was recently looking into why all errors I throw are logged as `info` level and eventually stumbled upon this line in the default error formatter.

I might be misunderstanding something here, but wouldn't it make more sense for this to have error level logs?

I can of course override the behaviour by using my own custom formatter, but I'm just slightly hesitant to do so when all I need to replace is the log level of errors.

https://github.com/mercurius-js/mercurius/blob/32dc3183464e0d78c27c58ee7dec97405f671958/lib/errors.js#L58

**Comment by mcollina** [comment]
Those are graphql errors - mostly application from your own application. I wouldn't want to log those as Error because they are not really actionable for the developer.
