### ISSUE TITLE
Federated mode using light my request

### ISSUE THREAD

**Issue by zekth** [mercurius-js/mercurius#928]
Hello,

Currently make a prototype for a specific case within a constrainted environment and i was able to make `mercurius` work with a `lightmyrequest` using `inject`. It doesn't seem to be possible to use federated mode with the same approach am i right?

I know this is some sort of hacky, do you have some leads on how to achieve it?

**Comment by mcollina** [comment]
It's not possible right now, but there is nothing that prevents it... just a lot of work.

Frankly, if everything is running on the same Node I would develop it using schema stitching or similar, federation is a significant overkill.

**Comment by zekth** [comment]
Okay thanks for the lead. I'll work on it :)
