### ISSUE TITLE
Create a contribute section in the website

### ISSUE THREAD

**Issue by simoneb** [mercurius-js/mercurius#941]
Now that this project is being split up into multiple repos and various plugins, it would be good to have a contribute section in the website similar to https://www.fastify.io/contribute/, which besides documenting contribution guidelines also integrates the list of open issues across all the repos.

The codebase of the API that's exposing the issues lives in https://github.com/fastify/gh-issues-finder

**Comment by simoneb** [comment]
@mcollina I thought as much. Nevertheless, this idea still holds regardless of which doc framework we'll use right?

**Comment by mcollina** [comment]
Absolutely

**Comment by jonnydgreen** [comment]
> I think we might want to move to docusaurous

Very happy to help out with this where needed as I've used docusaurus extensively

**Comment by simoneb** [comment]
@Eomm what's the status of porting fastify docs to docusaurus?

**Comment by Eomm** [comment]
We did 30% of the total.
The project status is here https://github.com/orgs/fastify/projects/5

Note that the target is to rebuild the current website; the next project will be focused on TONS of improvements, such as integrating plugins' documentation into the main website

**Comment by simoneb** [comment]
Thanks @Eomm, then I guess we'll try to go ahead with this and integrate this feature in the existing mercurius website. We should probably wait until the work on the fastify one is done before applying the same approach to mercurius.

**Comment by simoneb** [comment]
@jonnydgreen if you want to help with the docusaurus migration you can talk to @Eomm then!

**Comment by syedfarhanNF** [comment]
#948

**Comment by jonnydgreen** [comment]
> @jonnydgreen if you want to help with the docusaurus migration you can talk to @Eomm then!

Had a chat with @Eomm - I'll help out with the fastify stuff for sure!

> We should probably wait until the work on the fastify one is done before applying the same approach to mercurius.

Wonder if it's worth creating a GH project/repo in preparation for this and to start to track and plan this work? I'm happy to create these if there are no objections

**Comment by simoneb** [comment]
currently the docs are in the same repo as the source code, is having a standalone repo the same approach we're taking for fastify too? in that case, I guess we can do the same for mercurius

**Comment by mcollina** [comment]
> is having a standalone repo the same approach we're taking for fastify too? in that case, I guess we can do the same for mercurius

Yes, after Fastify finishes the move to Docusaurus, I would copy the same setup.

**Comment by syedfarhanNF** [comment]
Currently, there are two APIs running for the https://github.com/fastify/gh-issues-finder repo:

- https://gh-issues-finder-backend-k44evywkza-ew.a.run.app/
- https://goodfirstissue.fastify.io/

We need to decide on one API to use and remove the other.

Additionally, there is a rate limiting issue where we are quickly reaching the limit due to not setting a GitHub token for issues requests. This can be observed by refreshing the fastify.io/contribute page multiple times.

So we need to up a secret in whichever API we chose to stick with to fix this.

@mcollina What are you thoughts on the above?

**Comment by mcollina** [comment]
Oh I forgot we were running a server for that. I'll set up something soon on my infrastructure.

**Comment by simoneb** [comment]
@mcollina I think you already are. I believe that you're running the code in the repo https://github.com/fastify/gh-issues-finder on a server which is exposed via https://goodfirstissue.fastify.io/ (and which we don't have access to, at NearForm).

Instead, https://gh-issues-finder-backend-k44evywkza-ew.a.run.app/ is our (NearForm) hosted instance which is not supposed to be used.

**Comment by mcollina** [comment]
Mercurius is not part of the Fastify organization, I'll get something deployed asap.

**Comment by simoneb** [comment]
@mcollina note that the API hosted at fastify.io can work for any org, it's not specific to fastify. the org is provided in the search params

**Comment by mcollina** [comment]
I understood we couldn't use that because we are rate-limited

**Comment by simoneb** [comment]
My understanding is that it's not exactly that we can't use it, we have the same problem in fastify already I believe, but I am not 100% sure because I don't know where the API is deployed and how it's configured. If it is configured with a GH token, which the app source supports, then we shouldn't be rate limited (on any org, not just fastify), but since we are, it feels like the app is running without a GH token.

**Comment by mcollina** [comment]
I think we can use the Fastify one and configure that one properly: https://github.com/fastify/gh-issues-finder/issues/129.

**Comment by Eomm** [comment]
Here I did the contribution component, any feedback would be appreciated 🙌🏼  - https://github.com/fastify/website-next/pull/72

**Comment by simoneb** [comment]
@codeflyer this is now superseded by #964 right?

**Comment by codeflyer** [comment]
> @codeflyer this is now superseded by #964 right?

Yes

**Comment by simoneb** [comment]
@codeflyer can we close this issue?

**Comment by codeflyer** [comment]
Yes, I 'll do it
