### ISSUE TITLE
doc: documentation for federation is incorrect

### ISSUE THREAD

**Issue by marco-ippolito** [mercurius-js/mercurius#953]
documentation is federation.md:
https://github.com/mercurius-js/mercurius/blob/cbe637d34ef994cc2f5ba051c69f88f6ad2acc30/docs/federation.md?plain=1#L27-L29
is incorrect it should be:

`const { mercuriusFederationPlugin } = require('@mercuriusjs/federation')`
or we should fix the export on mercurius-federation and export it as default:
https://github.com/mercurius-js/mercurius-federation/blob/26894effa137bb4c6e8ae21b9b3247345b906245/index.js#L2-L6

also to keep consistency between plugins (gateway has default export)

**Comment by mcollina** [comment]
I would fix mercurius-federation.

**Comment by marco-ippolito** [comment]
fixed by https://github.com/mercurius-js/mercurius-federation/pull/13
