### ISSUE TITLE
DOC: docs don't have a favicon

### ISSUE THREAD

**Issue by capaj** [mercurius-js/mercurius#978]
for tab hoarders like me seeing this 
![image](https://user-images.githubusercontent.com/1305378/231977955-be7af81e-01fe-4d0c-9d85-051d3e2661fc.png)
makes it hard to find in a sea of other tabs.
Expected output:

title should be "Mercurius" or if it could even include the section, that woul be even better, so "Mercurius Install"
and icon should be set to this one: 
![image](https://user-images.githubusercontent.com/1305378/231978526-1c4466df-04e9-41e2-8b7a-ed037bace46e.png)

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by capaj** [comment]
I will try!

**Comment by Tony133** [comment]
Hi 👋🏻 ,this issue can be closed, the favicon has been added in this PR: https://github.com/mercurius-js/mercurius/pull/1085
